### ISSUE TITLE
Tears of the Moon  quest

### ISSUE THREAD

**Issue by Ralna1991** [FireFly-WoW/FireFly-IssueTracker#102]
http://www.wowhead.com/quest=2518/tears-of-the-moon

Missing a monster

**Comment by JunkyBulgaria** [comment]
what monster is missing?

**Comment by Ralna1991** [comment]
I have no idea where it is. The quest helper shows this place and there is no such spider. Just big ordinary ones

**Comment by Ralna1991** [comment]
![wowscrnshot_042217_222840](https://cloud.githubusercontent.com/assets/27869362/25307528/0b768f38-27ab-11e7-8178-a51639fa0837.jpg)

**Comment by Ralna1991** [comment]
Aha! Found her!. Thanks!
