### ISSUE TITLE
MovementGen/IsAccessibleToPlayer, read desc for more info

### ISSUE THREAD

**Issue by JunkyBulgaria** [FireFly-WoW/FireFly-IssueTracker#103]
Creatures with swim flag(not sure if just this or global) would follow player in air, they are not supposed to.
As sniffed from retail:

if - is not accessible to player (los) it sent evade packet but still in combat, after 6-8s it returned to spawn pos and left combat
/evade thingy can be customized (non-blizzlike)/

could be pathfinding related, idk..

**Comment by frytik** [comment]
It should try to follow player, if is not in IsAccessibleToPlayer it should return, but don't know how is handled evade in core.

**Comment by JunkyBulgaria** [comment]
now it checks if there is path, need to implement a method for the evade function

**Comment by JunkyBulgaria** [comment]
finally finished this system..
 current behavior: IF player is unreachable for the NPC it will try to go to the player and evade(return to spawn pos) after 8 secconds.
