### ISSUE TITLE
Dungeon: Drak'Tharon Keep: King Dred boss

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#107]
**Description:**

He is supposed to use: "Raptor Call" abilityl to call a nearby raptor to assist him.

**Current behaviour:**

He is not using his ability "Raptor Call" abilityl to call a nearby raptor to assist him.

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

He is supposed to use "Raptor Call" abilityl to call a nearby raptor to assist him.

**Comment by WarlordTF** [comment]
If I recall the Raptor Call actually spawns a raptor add, although my memory of this instance may be smeared with later expansions.

**Comment by starrheld** [comment]
Note:
http://www.wowhead.com/spell=59416/raptor-call
is a heroic only spell, does not apply to normal mode

**Comment by JunkyBulgaria** [comment]
works as intended, try heroic
