### ISSUE TITLE
Dungeon: Drak'Tharon Keep : The Prophet Tharon'ja boss

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#108]
**Description:**

At certain intervals he is supposed to use "**Decay Flesh**" during whole fight. Currently he use it only once at about 50% of his HP. He should use it more offen. 

Source: http://wowwiki.wikia.com/wiki/The_Prophet_Tharon%27ja

Video: https://www.youtube.com/watch?v=L691DSTPicQ

**Comment by JunkyBulgaria** [comment]
he starts to use it after he is below 80%, chance of casting every 3s

**Comment by Deathtremor** [comment]
@junkyBulgaria

So need testing or its working properly the way as it is now or?

**Comment by JunkyBulgaria** [comment]
@Deathtremor you can test if you want, i tried and it seem to be fine for me.

**Comment by Deathtremor** [comment]
@junkybulgaria

Ok will Re-tested today.

**Comment by Deathtremor** [comment]
@JunkyBulgaria 

Re-tested. 

He cast it on me only once at about 80% He didn't cast it second time.

**Comment by JunkyBulgaria** [comment]
i removed my fixes, encounter works as intended.

[CASTED ONLY ONCE IN P1] Decay Flesh - Stuns all player for a short amount of time. During this time, he will no longer attack or cast spells. He enters phase 2 immediately after the end of the channeling.
[CASTED ONLY ONCE IN P2]  Return Flesh - Stuns all player for a short amount of time. During this time, he will no longer attack or cast spells. He returns in phase 1 immediately after the end of the channeling.
