### ISSUE TITLE
Creature/Object Pool (dynamic spawn system)

### ISSUE THREAD

**Issue by JunkyBulgaria** [FireFly-WoW/FireFly-IssueTracker#110]
This 'system' is implemented in blizzard, not sure if they call it 'pooling' or not, it doesn't matter.
The functionality is to reduce the spawn/respawn time of ores, herbs, creatures and make more pools depending on players in the current area. 
The maximum value is yet to be decided, maybe 15-25% is good, idk.

TODO: 
- [x] Creatures pool
- [x] Ores pool
- [x] Herbs pool
- [x] Fishing pool

For Specific:
- [x] Area
- [x] Zone
- [ ] Continent // might be useless?

>This issue is just a WIP and a "TODO" task, most of the comments are non-player (to be tested) related.

**Comment by JunkyBulgaria** [comment]
implemented tc's system and simplified it a lot

**Comment by JunkyBulgaria** [comment]
might be used for reference / reopened in the future due to 3rd point in "for specific"

**Comment by Siderbas** [comment]
This definitely needs to be looked into again. Both number of node clustered together as well as respawn time of nodes seems way too high. Just run through 1k needles for example. I had 6 nodes "around me" on the minimap once. But it effects every zone apparently.

**Comment by JunkyBulgaria** [comment]
@Siderbas this is not related to the pool system, the node spawns are blizzlike and sniffed from retail it's just that no one has run trough that zone to mine them.
