### ISSUE TITLE
Quest: Free your mind

### ISSUE THREAD

**Issue by hairysiv** [FireFly-WoW/FireFly-IssueTracker#113]
**Description:**
The player is supposed to kill three mobs - a banshee, an abomination and a geist.

CHANGEME: Describe the issue here
"the leaper", "lady nightswood" and "vile" are where they are supposed to be, however, they can't be killed. As soon as they reach 1 health point they start evading and then re-enter combat or despawn. 

Since they are impossible to kill, I'd say the quest chain to unlock "knights of the ebon blade" isn't possible to complete.

**Current behaviour:**
The mobs evade and reset combat or despawn once they reach 1 health point.

CHANGEME: Explain to us (if/how) it currently works.
It does not work.

**Expected behaviour:**
The player is supposed to kill these three mobs in order to use a "sovereign rod" on the corpses, to make them stop following the Lich King.

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
Make sure it's possible to kill the Leaper, Vile and Lady Nightswood.
2. Step 2
Make sure it's possible to use Sovereign rod on their corpses.
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by starrheld** [comment]
Can't confirm this without access to the quest, but mostly due to smart scripting error.

**Comment by JunkyBulgaria** [comment]
fixed http://prntscr.com/f2348d
