### ISSUE TITLE
GM island Robot problem

### ISSUE THREAD

**Issue by Kristrox** [FireFly-WoW/FireFly-IssueTracker#114]
**Robot (repair) on GM Island can be attacked :**

CHANGEME: Describe the issue here

**By clicking robot with right button of your mouse robot can be attacked:**

CHANGEME: Explain to us (if/how) it currently works.

**Repair robot should be friendly to both sides:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
no big deal, it is placed only for the beta there
