### ISSUE TITLE
the quest "the battle for the ebon hold" of dk's is impossible

### ISSUE THREAD

**Issue by Minimoth1** [FireFly-WoW/FireFly-IssueTracker#115]
Description:

The radius of detection of all the monsters in this server is too high, I had already noticed in other missions
but in this one, once you attack one of the enemies, they catch you all with their hooks and it is impossible to free you.

**Comment by JunkyBulgaria** [comment]
tested and confirmed, reduced it slightly, by ~15%, should be fine now

**Comment by Minimoth1** [comment]
Well, they keep throwing you from side to side with their hooks, but at least this time I could complete it without the firefly damage trick. I have been following the chain of missions of the death knights to confirm that it can be done without tricks, however now that I finish this mission I should be able to go to orgrimmar through the portal but i can't used it. I think I read in another issue that they had already solved it but to me it doesn't work.

**Comment by JunkyBulgaria** [comment]
some players completed it without issues, that's strange

**Comment by Minimoth1** [comment]
I'm playing now, ¿do you want to see it for yourself?

**Comment by Minimoth1** [comment]
I will wait here until the problem is fixed, so I can confirm that it works

**Comment by JunkyBulgaria** [comment]
no need, will make a new issue for it, thanks
