### ISSUE TITLE
Client crashes in Eversong Woods

### ISSUE THREAD

**Issue by TazzG** [FireFly-WoW/FireFly-IssueTracker#117]
**Description:**

It happened twice in a row : my client crashed when i got aggroed by an Elder Springpaw beneath ground.
Edit : It happens every time, making this area almost unplayable.
Edit2 : It happens with any Springpaw

**Current behaviour:**

I suppose the problem is related to the Springpaws.

**Steps to reproduce the problem:**

1. Walk around the area i am on screenshot and get aggro by a springpaw beneath ground.

**Screenshots:**

http://imgur.com/eyB5J2Z
http://imgur.com/ZjLzRb7

**Comment by JunkyBulgaria** [comment]
fix applied
