### ISSUE TITLE
Arcane Disturbances

### ISSUE THREAD

**Issue by dannehh1918** [FireFly-WoW/FireFly-IssueTracker#118]
**Description:**

After you fill the Crystal at the well 2 invisible ghost will start attacking you 

**Current behaviour:**

After you fill the Crystal at the well 2 invisible ghost will start attacking you 

**Expected behaviour:**

They Should be visable

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

![wowscrnshot_042617_154059](https://cloud.githubusercontent.com/assets/27703814/25437521/ed61d342-2a96-11e7-9af6-b5ca78500223.jpg)

https://www.youtube.com/watch?v=QxlCMQZk7wg

**Comment by starrheld** [comment]
This is incorrect, there are two mobs visible before the vial is filled.

> However, there might be missing spawns of the **Wailing Spectre**

**Comment by Demmye** [comment]
Confirmed. This is bugged, because Underground Well Credit Marker(this thingie http://i.imgur.com/eihD5dX.jpg ) is aggresive for some reason, therefore attacking everyone close.
