### ISSUE TITLE
Malygos mechanics

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#119]
**Description:**

After Vortex ends, you get suspended in the air or drop through the platform and die (both happened at different attempts)

**Current behaviour:**

After Malygos finishes spinning the raid, you get glitched on top of him without being able to reach the floor (or if you do, you go right through it), and also the boss visual "freezez" in his current position altho he is actually facing and attacking you, it seems like he is attacking an invisible target.

**Expected behaviour:**

After the Vortex ability ends, you should drop on the ground and the boss should continue attacking the player with most aggro.

**Steps to reproduce the problem:**

1. Step 1
Start the boss encounter
2. Step 2
Wait <1 minute for the boss to cast Vortex
3. Step 3
Observe how the spell ends and you remain suspended in the air with the boss attacking you but looking as it is attacking an invisible target
**Screenshots:**

http://imgur.com/4FQ8x3l
http://imgur.com/T2mrJE4
http://imgur.com/L91PLs9

**Comment by JunkyBulgaria** [comment]
it requires more players, we will see how it would be in actual raid on live realm
