### ISSUE TITLE
Defias Traitor quotes

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#120]
**Description:**

Minor chat bubble glitch during the escort of the defias traitor npc for the quest The Defias Brotherhood (part 6)

**Current behaviour:**

When the Defias Traitor is being attacked by mobs in Moonbroke he at some point says "%s coming in fast! Prepare to fight"

**Expected behaviour:**

Instead of "%s" there should be the name of the mob he is engaged in combat with (eg. Defias looter coming in fast! Prepare to fight)

**Steps to reproduce the problem:**

1. Step 1
Start the chain quest The Defias Brotherhood in Sentinel Hill from npc Gryan Stoutmantle
2. Step 2
Keep doing the quest chain until the Defias Traitor npc quest giver is available
3. Step 3
Escort the Defias Traitor to Moonbroke and wait for him to engage in combat
**Screenshots:**

http://imgur.com/a/J1K8b

**Comment by starrheld** [comment]
This might be due to a missing s after the percentage-sign like "%s"

```SQL
-- Defias Traitor
DELETE FROM `creature_text` WHERE `entry`=467 AND `groupid`=3 AND `id`=0;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextID`, `TextRange`, `comment`) VALUES (467, 3, 0, '%s coming in fast! Prepare to fight!', 12, 0, 100, 0, 0, 0, 489, 0, 'defias traitor SAY_AGGRO_1');
```

**Comment by JunkyBulgaria** [comment]
%s is for self target, $N is for target, e.g the enemy

**Comment by starrheld** [comment]
This is not correct on currect rev AC and TC, $N if for player with the quest, test it before.

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/f22vca

**Comment by starrheld** [comment]
If it works great, guess it's not same in the core as current TC and AC then!
