### ISSUE TITLE
Fishing from high ground

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#121]
**Description:**

Unable to cast fishing pole from high grounds.

**Current behaviour:**

Tried fishing in Booty Bay from atop the platform. Works if i go down the ramp tho. Same for bridges in Stormwind. If i am closer to the water level then it works fine.

**Expected behaviour:**

You should be able to cast your fishing pole from at least a high enough ground as a bridge like the ones in Stormwind

**Steps to reproduce the problem:**

1. Step 1
Try to fish from a bridge or other high above water level spots
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/Rmy30
http://imgur.com/a/OYET3
http://imgur.com/a/n95PK

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/f27tlj fixed

**Comment by sarlic1337** [comment]
![wowscrnshot_052917_131221](https://cloud.githubusercontent.com/assets/28652031/26547688/8ae1d804-4470-11e7-83b8-fae8d271fb57.jpg)
Is this the same bug or should I make new Thread.
