### ISSUE TITLE
Class: Warrior: Hit rating 

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#122]
**Description:**

With 10.58% hit rating from gear + 2% hit from [Precision] talent, overal 12,58% hit rating I'm still missing. There is about 5-10% chance you will miss. Hit cap for Warrior is 8%. With 8% hit rating you should not be missing (or at least very very low posibility you will miss).

![wowscrnshot_042817_174744](https://cloud.githubusercontent.com/assets/27430839/25519624/f4398952-2c3b-11e7-8d01-51af922dbf5a.jpg)

**Comment by JunkyBulgaria** [comment]
Have you used .maxskill?

**Comment by Deathtremor** [comment]
@JunkyBulgaria 

Yes i have. Have 450/450 skill.

**Comment by JunkyBulgaria** [comment]
With 11% i had only 3 misses from 30+ attacks /melee only/, so i'd say it's 1:10 which seems normal to me but i'll leave this open so other players can say their opinion as well.

**Comment by DaRealBoss** [comment]
8% hit is the cap for SPECIAL attacks. dual wielding hit cap is something like 27%, so yes it is normal to miss  white hits... do a simple google search on issues before posting them

**Comment by Deathtremor** [comment]
@DaRealBoss 

No need to be that offensive. I do always research before reporting. I'm not the most active tester for doing nothing ^^ I didn't have much time last night so i put it simply like this. I was going to do more research this morning. You could at least provide some information to back it up. Never mind. You was right.

![bez nazvu](https://cloud.githubusercontent.com/assets/27430839/25550614/ea1b1c9c-2cbd-11e7-97bf-7c208e6578a0.png)

This can be closed since there is nothing wrong with hit rating.
