### ISSUE TITLE
Class: Warrior: Charge pathfinding

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#124]
**Description:**

* When you charge on top of a sharp hill ( or on on a difficult terrain ) you will in some cases end up under texture & ground and you will die.

* When you jump and you charge right after you will end up too far from the target ( about5 - 20ft) and you will still be able still attack the target or at least pull it without doing any damage. This also applies even if you don't jump! **ALSO** you will in most cases get stuck inside of the target without able to move.  This applies anytime you are above ground & not staying with your feet on the ground. 

Stuck inside of the target:

![wowscrnshot_042817_184638](https://cloud.githubusercontent.com/assets/27430839/25522419/220a0050-2c46-11e7-9d62-7d54a71065d4.jpg)

Falling through texture:

![wowscrnshot_042817_183920](https://cloud.githubusercontent.com/assets/27430839/25522408/16a27e7c-2c46-11e7-98a7-0e3e492baa5c.jpg)

Fighting target **from range** (about 20ft away) and **above the ground** after charge right after jump. 

![wowscrnshot_042817_191144](https://cloud.githubusercontent.com/assets/27430839/25522991/64f6c22a-2c48-11e7-9e43-9a004c20028d.jpg)

**Comment by WarlordTF** [comment]
This is a common issue with trinity core versions, if I recall (and this is quite dated solution) it was a degree of Vmaps issue (again, VERY dated.)

**Comment by JunkyBulgaria** [comment]
works as intended, we do not support pathfinding on junk maps like gm island, dev box, testarea etc
about the 2nd issue we are rewriting aggro handle
