### ISSUE TITLE
Zeppelin Bug

### ISSUE THREAD

**Issue by Noxx551** [FireFly-WoW/FireFly-IssueTracker#126]
Description

I just got on the zeppelin from durotar to tirisfal. However jumping on it makes you stuck and may result that you are not taken away.

Current behaviour

Jumping on it makes you stuck and may result that you are not taken away.

Expected behaviour

You should be able to walk and jump on the zeppelin.

Steps to reproduce the problem

1. Step Go on the zeppelin
2. Step Jump around
3. Step Enjoy getting stuck

**Comment by JunkyBulgaria** [comment]
fixed
