### ISSUE TITLE
Mulgore res locations back to front

### ISSUE THREAD

**Issue by Fenris95** [FireFly-WoW/FireFly-IssueTracker#129]
**Description:**

The resurrection locations depending on where you die are backwards it seems.

**Current behaviour:**

When I died in Brambleblade Ravine I was spawned at the res point to the north and had to walk a long way back along the wall infront of red cloud mesa. When i died north of that res point, to the east of Bloodhoof Village, I spawned next to Red Cloud Mesa.

**Expected behaviour:**

The opposite of this.

**Steps to reproduce the problem:**

1. Die in brambleblade ravine, specifically outside the chieftan's hut
2. Die to the east of bloodhood village around 64, 60

**Screenshots:**
http://i.imgur.com/p5uWRjb.jpg

**Comment by Demmye** [comment]
Confirmed, resurrection points seem mixed up.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Killed myself north of Death's Stand. Spawned at the nearest spirit healer.

Seems alright.
