### ISSUE TITLE
(Quest) Magistrix Landra Dawnstrider: "Saltheril's Haven"

### ISSUE THREAD

**Issue by TheOddTruth** [FireFly-WoW/FireFly-IssueTracker#131]
**Description:**

Magistrix Landra Dawnstrider (Fairbreeze Village; Eversong Woods) is supposed to offer the quest titled "Saltheril's Haven" at Level 8 for Horde. The quest is currently unobtainable for my level 9 Blood Elf. 

**Current behaviour:**

NPC Magistrix Landra Dawnstrider does not offer the quest "Saltheril's Haven" at the appropriate progression level.

**Expected behaviour:**

NPC Magistrix Landra Dawnstrider should offer the quest "Saltheril's Haven" at level 8.

**Steps to reproduce the problem:**

1. Reach level 8 on a Blood Elf or any Horde character.
2. Get denied access to "Saltheril's Haven" quest by NPC Magistrix Landra Dawnstrider

**Comment by TW3TY** [comment]
> This is due to the requirement of completing a previous quest.
> Order: **Unexpected Results**, **Research Notes** and finally **Magistrix Landra Dawnstrider** will have **Saltheril's Haven** available.

![IMG1](http://i.imgur.com/D8PBmOi.jpg)
![IMG2](http://i.imgur.com/TG1Phgk.jpg)
![IMG3](http://i.imgur.com/M40TX6M.jpg)

**Comment by TheOddTruth** [comment]
Thanks for getting back to this @TW3TY ! I guess I should have done a bit more research. Wowhead totally misled me. I have to remind myself this isn't retail. A master list of quest-chains from the WotLK era would be handy! The completionist in me thanks you. 👍

**Comment by TW3TY** [comment]
Issue can be closed down, thanks.
