### ISSUE TITLE
[NPC] Zenn Foulhoof watches the tree

### ISSUE THREAD

**Issue by Teezrlord** [FireFly-WoW/FireFly-IssueTracker#132]
**Description:**

He's looks in the wrong direction.

**Current behaviour:**

He just watches the tree...

**Expected behaviour:**

Stares at the path, where players are walking by to Dolanaar.

**Steps to reproduce the problem:**

1. Walk to him
2. Watch him
3. get triggered

**Screenshots:**

http://imgur.com/a/uSNcr

**Comment by TW3TY** [comment]
> I assume you can just adjust the orientation of the creature.

```SQL
UPDATE `creature` SET `orientation` = 4.00441 WHERE `id` = 2150;
```

![IMG](http://i.imgur.com/7jVCl52.png)

**Comment by JunkyBulgaria** [comment]
applied
