### ISSUE TITLE
Anti-Cheat is to strikt.

### ISSUE THREAD

**Issue by Teezrlord** [FireFly-WoW/FireFly-IssueTracker#133]
**Description:**

The Anticheat is to strikt so you will get setback'd very much.

**Current behaviour:**

You are not allowed to jump on a boat and players reporting that charge (the warrior's charge) sets you back some times.

**Expected behaviour:**

You are free to jump on boats anytime and charge every mob there is without getting set back. 

**Steps to reproduce the problem:**

1. Go on a boat
2. Wait until it starts to move
3. Jump and get setback'd 

**Screenshots**

**Comment by JunkyBulgaria** [comment]
fix applied
