### ISSUE TITLE
[NPC] Defias prisoner and guards

### ISSUE THREAD

**Issue by Teezrlord** [FireFly-WoW/FireFly-IssueTracker#134]
**Description:**

A Defias Prisoner is walking from Stormwind Harbour to Stormwind Stockades.

**Current behaviour:**

The Prisoner is guarded by 4 guards and isnt handcuffed.

**Expected behaviour:**

There should only be 2 guards, 1 on the left, 1 to the right. The Prisoner should wear handcuffs.

**Steps to reproduce the problem:**

1. Go to Stormwind
2. Search for the Prisoner
3. Watch 4 men guarding 1 dude...

**Screenshots:**

http://imgur.com/a/zM7XQ

**Comment by JunkyBulgaria** [comment]
where did you get the data that 2 guards are guarding him?
