### ISSUE TITLE
(Bug-Quest) "Swift Discipline"

### ISSUE THREAD

**Issue by TheOddTruth** [FireFly-WoW/FireFly-IssueTracker#137]
**Description:**

The Quest "Swift Discipline" (NPC Instructor Antheol; Eversong Woods) has a bug that renders the quest not completable.

**Current behavior:**

The quest requires the player to take "Antheol's Disciplinary Rod" (Quest Item) and use it on NPC Apprentice Meledor (Eversong Woods) and NPC Apprentice Ralen (Eversong Woods). Currently, the "Antheol's Disciplinary Rod" WORKS on NPC Apprentice Ralen, allowing objective completion. However, the "Antheol's Disciplinary Rod" DOES NOT WORK on NPC Apprentice Meledor, rendering the quest not completable. 

**Expected behaviour:**

Utilizing Quest Item "Antheol's Disciplinary Rod" on NPC Apprentice Meledor should result in credit toward completion of quest "Swift Discipline"

**Steps to reproduce the problem:**

1. Pick up Quest "Swift Discipline" (Min. Level 4) from NPC Instructor Antheol (Eversong Woods).
2. With Quest Item "Antheol's Disciplinary Rod" in inventory, attempt to "cast" it on NPC Instructor Meledor.
3. No quest credit toward "Swift Discipline" results from this action.

**Screenshots:**

![wowscrnshot_042917_190959](https://cloud.githubusercontent.com/assets/28205995/25560079/8ae4d568-2d0f-11e7-893b-d2659274d024.jpg)
![wowscrnshot_042917_191003](https://cloud.githubusercontent.com/assets/28205995/25560082/92ea1728-2d0f-11e7-8af9-dce8b686a2fd.jpg)

**Comment by TW3TY** [comment]
> Most likely missing smart script, did the text appear upon using the item on **Apprentice Ralen** @TheOddTruth ?

```SQL
-- Apprentice Meledor SAI
DELETE FROM `smart_scripts` WHERE `entryorguid`=15945 AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(15945,0,0,1,8,0,100,0,27907,0,15000,15000,33,15945,0,0,0,0,0,7,0,0,0,0,0,0,0,"Apprentice Meledor - On Spellhit 'Disciplinary Rod' - Quest Credit 'Swift Discipline'"),
(15945,0,1,0,61,0,100,0,27907,0,15000,15000,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"Apprentice Meledor - On Spellhit 'Disciplinary Rod' - Say Line 0");
```

> If the creature texts are missing, this is the fix for that.
```SQL
DELETE FROM `creature_text` WHERE `entry` IN (15945,15941);
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`) VALUES
(15945,0,0,'You can''t do this to me! We had a deal!',12,0,0,0,0,0,''),
(15941,0,0,'What? Oh, not this again!',12,0,0,0,0,0,'');
```

**Comment by JunkyBulgaria** [comment]
fixed, issue was incorrect id

**Comment by TheOddTruth** [comment]
Actually, I'm fairly certain that the text did appear. Regardless, it wouldn't hurt to test it again to make certain. Thanks @TW3TY for replying.
