### ISSUE TITLE
Gurf's Dignity

### ISSUE THREAD

**Issue by brandanquinn** [FireFly-WoW/FireFly-IssueTracker#140]
**Description:**

Gurf's Dignity is an item that, when clicked, should give you a quest to accept. But, when clicked on, you receive an error message that says you do not meet the requirements.

**Current behaviour:**

When you right-click the item, you get a yellow error message in the chat box that says, "You don't meet the requirements for that quest."

**Expected behaviour:**

Quest should be given, if the player is above level 7 (Level 10 at time of testing)

**Steps to reproduce the problem:**

1. Kill Murgurgula
2. Pick up Gurf's Dignity
3. Right-click Gurf's Dignity

**Screenshots:**
None

**Comment by TW3TY** [comment]
> This is Blizzlike, you have to complete a previous quest before you can accept the quest **Gurf's Dignity (9564)** called **Murlocs... Why Here? Why Now?(9562)**.
> However, there should be a condition that disallows player to loot the item **Gurf's Dignity(23850)** before completing the required quest.

**Comment by TW3TY** [comment]
> This will do, you can customize it however you like.
> Unless player already completed the quest **Murlocs... Why Here? Why Now?** the item **Gurf's Dignity** won't drop from *Murgurgula*.
```SQL
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=1 AND `SourceGroup`=17475 AND `SourceEntry`=23850 AND `SourceId`=0 AND `ElseGroup`=0 AND `ConditionTypeOrReference`=8 AND `ConditionTarget`=0 AND `ConditionValue1`=9562 AND `ConditionValue2`=0 AND `ConditionValue3`=0;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (1, 17475, 23850, 0, 0, 8, 0, 9562, 0, 0, 0, 0, 0, '', 'ONLY DROP ITEM IF QUESTREWARDED 9562');
```

**Comment by frytik** [comment]
Summoning @JunkyBulgaria

**Comment by JunkyBulgaria** [comment]
applied
