### ISSUE TITLE
Frost Nova Evasion Bug

### ISSUE THREAD

**Issue by Cqwertyuiop75** [FireFly-WoW/FireFly-IssueTracker#142]
If you pull more than two mobs, one of those 3+ mobs will almost always evade. I have tested this and was able to reproduce this.

Frost Nova is supposed to root every single enemy near you unless it either resists or it is a boss for example that is immune to crowd control.

**Steps to reproduce the problem:**

1. Pull 3 or more mobs and a good percentage of the time 1/3 of them will resist. The only one time that they didn't all evade was when I had my Frost Armor on which could have effected the mob in question with Frostbite effectively rooting it and making the Frost Nova look as if it were successful with all of them.

**Comment by JunkyBulgaria** [comment]
related to aggro range, should be fixed now, if it doesn't work please re-open/comment on this issue
