### ISSUE TITLE
Root/Sheep Root Bug

### ISSUE THREAD

**Issue by Cqwertyuiop75** [FireFly-WoW/FireFly-IssueTracker#143]
**Description:**
When you polymorph an enemy their pathing seems to get messed up for a good two seconds and they just tend to stand in place until they resume their normal routine of chasing you which allows you to get free shots in on an immobilized target that should otherwise be moving to your position when the root or polymorph effect wears off. This seems to sometimes happen with Frostbite and Frost Nova as well but not as consistently as with polymorph.

**Expected behaviour:**

When a root or polymorph is broken, the enemy should immediately start coming to attack you.

**Steps to reproduce the problem:**

1. Sheep an enemy
2. Hit it with any projectile
3. The enemy will most likely fail to move towards you for 2 or so seconds after the effect is broken allowing for a few free hits.

(I'm not sure if this is the case with other classes and their roots)

**Comment by frytik** [comment]
It is done only for player's ?

**Comment by Demmye** [comment]
Seems to work fine on PTR, both with Root spells and Polymorph, however, when you polymorph a caster creature, it sometimes doesn't cast spells instantly after it breaks. The delay varies from 0.5 to 1.5 seconds.
