### ISSUE TITLE
[Quest][1k needle] Free at Last (Tauren escort)

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#146]
Issue description

Escort npc got stuck under the bridge. As you can see in the screenshots

What i did:  Walked the way till the last bridge. Then encountered an enemy npc. Fought him. The escort tauren lady joined the fight. After the fight she went under the bidge. Didn't continue to walk

**Screenshots:*

![wowscrnshot_043017_125942](https://cloud.githubusercontent.com/assets/24325735/25564090/1276a92a-2dab-11e7-8bf3-975a350adb20.jpg)

![wowscrnshot_043017_125945](https://cloud.githubusercontent.com/assets/24325735/25564052/5bcd1632-2daa-11e7-9dee-61bca721c0a6.jpg)

http://db.vanillagaming.org/?quest=4904

**Comment by TW3TY** [comment]
Could be due to movement maps

**Comment by TheOddTruth** [comment]
The quest doesn't have any pathing issues. However, she does like to bug out around the suspension bridges.. I find there is a lot of issues with the 1k needles suspension bridges in regard to NPCs such as hunter pets. I'll make a separate report later for this purpose.
