### ISSUE TITLE
Common item drops

### ISSUE THREAD

**Issue by Sherrilyn** [FireFly-WoW/FireFly-IssueTracker#147]
There definitely is too much common item drops from mobs.

Im now lvl 12 and i've noticed that mobs drop common items almost everytime.

For example last mobs i killed were Greater Plainstriders near Grossroads and got 5 Disciple's Cloaks and 3 Warrior's Boots from them when i had my quest at 4/7 complete.

Same happened all the time while leveling from almost all kinds of mobs. First didn't really pay attention to it but then I noticed I had my bags filled with same common item and noticed it was dropping again and again.

Expected behaviour is that they do drop common items but far less commonly so that bags wont fill up from the same item.

I don't know what the drop chances really are but now it seems like 60% or something.

Here is a screenshot from my bags with 5 Disciple's Cloaks.

![commonitems](https://cloud.githubusercontent.com/assets/28221475/25564415/8bf56042-2dbb-11e7-842f-f834ee9f3cc0.png)

and here im looting and got both Disciple's Cloak and Warrior's Boots and you can see my bags having lots of common items.

![morecommonitems](https://cloud.githubusercontent.com/assets/28221475/25564476/aa61bc00-2dbc-11e7-8c4a-4307dd0427e3.png)

**Comment by TheOddTruth** [comment]
I noticed the same thing and thought it was a bit unusual. From my perspective this has only occurred with mobs around the crossroads thus far.

**Comment by Siderbas** [comment]
Can also confirm this for alliance side <lvl24 (but can't remember which mobs exactly)
