### ISSUE TITLE
Quest item + drop + stuck at looting + skin

### ISSUE THREAD

**Issue by tjukoela** [FireFly-WoW/FireFly-IssueTracker#148]
**Description:**

When we are into group and we drop quest items on mobs, sometimes we can't skin because the mob has not been 'looted', in the fact, others players has loot everything on the mob, but it stuck at 'loot' mode, it's like there is something else to drop.

**Current behaviour:**

Group with others members, kill mobs to get items quest from them, and sometimes try to loot and try to skin

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
fix applied

**Comment by sarlic1337** [comment]
Bug is still live. Leveling Guild says for alot of them it worked, for a few not. 
I'm Pala Dwarf and it's not working. Same  Problems as tjukoela
