### ISSUE TITLE
Zeppelins are effected heavily by anti cheat as well

### ISSUE THREAD

**Issue by Cqwertyuiop75** [FireFly-WoW/FireFly-IssueTracker#149]
**Description:**

Walking down the stairs of a moving zeppelin ended up getting me clipped out of the zeppelin and stuck standing mid air by the anti cheat.

**Current behavior:**

Whatever you do, do not jump in them either or you're tempting fate even more than walking down the stairs.

**Expected behavior:**

Jump in the zeppelin/walk down the stairs and you remain in your zeppelin unless you actively jump/walk off of it.

**Steps to reproduce the problem:**

1. Jump in the Zeppelin or walk down the stairs mid flight though walking down the stairs doesn't always do it.

**Screenshots:**

http://tinypic.com/view.php?pic=34j9b0o&s=9

One of the lower points of my character's existence.

**Comment by JunkyBulgaria** [comment]
fixed
