### ISSUE TITLE
[quest] Frostmane Hold

### ISSUE THREAD

**Issue by PolarCookie** [FireFly-WoW/FireFly-IssueTracker#151]
quest: Frostmane Hold is missing the "Fully explore Frostmane Hold" objective in the quest log.
http://wow.gamepedia.com/Quest:Frostmane_Hold

**Comment by TW3TY** [comment]
Could be due to missing **AreaDescription**
```SQL
UPDATE `quest_template` SET `AreaDescription` = "Fully explore Frostmane Hold" WHERE `ID` = 287;
```

> Is the objective still required? @PolarCookie or is it completed upon killing X5 **Frostmane Headhunters** ?

**Comment by PolarCookie** [comment]
Should be completable, heading there now, it just Zygor's quest addon spamming the entire chat window with "quest has no such goal"

**Comment by TW3TY** [comment]
Thank you for your swift reply, tell me if you still have to explore Frostmane Hold! :1st_place_medal:

**Comment by PolarCookie** [comment]
can't find the explore location, still doesn't say that quest is complete

**Comment by TW3TY** [comment]
Would help you out, call for a Game Master in Discord would be advised.

**Comment by Maxteralex** [comment]
I have the same problem with this quest. Already explored the whole Frosmane Hold (I went from one side of the cave to the other one and went through the "village"). Btw, I already checked with the NPC who gave me the quest and it show as if it was not done.

**Comment by TW3TY** [comment]
> Getting in touch with a GM would be advised at this point @Maxteralex until this issue gets resolved. Thanks for confirming this issue nonetheless.

**Comment by Demmye** [comment]
The objective is still not shown, but the quest can be completed by exploring on PTR.

**Comment by JunkyBulgaria** [comment]
quest now works fine, if it doesn't give you credit if you already explored please go to the hold again and it will count

**Comment by bassuraaj** [comment]
Tested on Live Realm, Working.
