### ISSUE TITLE
No guards in Undercity

### ISSUE THREAD

**Issue by Iazneznam** [FireFly-WoW/FireFly-IssueTracker#152]
Thats it, there are no guards in Undercity from which you can ask for directions.

**Comment by TW3TY** [comment]
> Not a single **Kor'kron Overseer** ? @Iazneznam

**Comment by Iazneznam** [comment]
Nope only the Royal guard but they dont give directions.

**Comment by JunkyBulgaria** [comment]
kor'kron overseers were added in 3.3x after undercity attack

**Comment by JunkyBulgaria** [comment]
closed as it works as intended (part of the progressive content) please make new issue with information about the old guards
