### ISSUE TITLE
[quest] The Fargodeep Mine

### ISSUE THREAD

**Issue by PolarCookie** [FireFly-WoW/FireFly-IssueTracker#153]
quest: The Fargodeep mine completable but quest log is missing exploration objective, similar to https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/151.

maybe?
```sql
UPDATE `quest_template` SET `AreaDescription` = "Scout through the Fargodeep Mine" WHERE `ID` = 62
```

**Comment by TW3TY** [comment]
> This could be more advanced than that, could be with **areatrigger involvedrelation(s)** to do. Unfortunately I have no way to test this.

**Comment by JunkyBulgaria** [comment]
merge with #154
