### ISSUE TITLE
[quest] The Jasperlode Mine

### ISSUE THREAD

**Issue by PolarCookie** [FireFly-WoW/FireFly-IssueTracker#154]
quest: The Jasperlode mine is completable but quest log is missing exploration objective, similar to https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/151.

maybe?
```sql
UPDATE `quest_template` SET `AreaDescription` = "Scout through the Jasperlode Mine" WHERE `ID` = 76
```

**Comment by TW3TY** [comment]
> This could be more advanced than that, could be with **areatrigger involvedrelation(s)** to do. Unfortunately I have no way to test this.

**Comment by JunkyBulgaria** [comment]
ref: #153 ;; missing areatrigger with quest credit at end of mine, need to sniff position

**Comment by TW1NKLET** [comment]
@JunkyBulgaria are you sure that **trigger** 88 is not there?
> .go trigger 88
```SQL
-- THE FARGODEEP MINE
DELETE FROM `areatrigger_involvedrelation` WHERE `id`=88;
INSERT INTO `areatrigger_involvedrelation` (`id`, `quest`) VALUES (88, 62);
```

**Comment by Demmye** [comment]
The quest is working now on PTR.

**Comment by Siderbas** [comment]
Reopened to due ticket Number 471.

**Comment by Demmye** [comment]
The quest is working on PTR.
