### ISSUE TITLE
Skinning "attempt failed"

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#156]
**Description:**

When skinning a beast it will sometimes fail. You can keep skinning it until it finally does.

**Current behaviour:**

A "Attempt failed" message pops up. Then you can try to skin again.

**Expected behaviour:**

It should just skin the corpse.

**Steps to reproduce the problem:**

1. Kill a beast.
2. Loot the corpse.
3. Try to skin it. If you are unlucky it will give an error.

**Screenshots:**
https://i.imgur.com/J8AO0iO.gifv

**Comment by TW3TY** [comment]
Did some research and thought, this might be Blizzlike... BUT!
> Patch 3.1.0 (14-Apr-2009): You can no longer fail when Mining, Herbing, and Skinning

**Comment by TheOddTruth** [comment]
Rarely, it happens on any creature randomly for me.

**Comment by TW3TY** [comment]
### UPDATE
> Need this confirmed by one of the devs, if the server is currently in a **progression** state at patch **3.0.2**. Then this is blizzlike, and this is an invalid issue report.

@TheOddTruth & @davidmurcia

**Comment by davidmurcia** [comment]
It is random. Not connected to a specific creature.

**Comment by JunkyBulgaria** [comment]
it's progression related, will be fine in 3.1x
