### ISSUE TITLE
WC Event Boss Unscripted

### ISSUE THREAD

**Issue by achristy93** [FireFly-WoW/FireFly-IssueTracker#157]
**Description:**

WC Event boss unscripted/bugged.

**Current behaviour:**

The adds and boss spawn all at once instead of in waves.

**Expected behaviour:**

Adds should spawn in waves before boss appears.

**Steps to reproduce the problem:**

1. Complete WC
2. Talk to Tauren at front of instance
3. Escort him to boss room

**Screenshots:**

Got cucked too hard. Forgot to ss.

**Comment by Siderbas** [comment]
Is this still happening?

**Comment by Demmye** [comment]
It works as it should now.
