### ISSUE TITLE
[CORE] Tooltip (Quest Objective)

### ISSUE THREAD

**Issue by TW1NKLET** [FireFly-WoW/FireFly-IssueTracker#158]
**Description:** Duplicate in tooltip

**Current behaviour:** Duplicate entry in tooltip

**Expected behaviour:** There should only be one objective which is the one at the top in the screenshot. The other one is missing the objective progress regardless.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

![TOOLTIP](http://i.imgur.com/wmH9MV4.png)

**Comment by Siderbas** [comment]
Can confirm this report.

**Comment by JunkyBulgaria** [comment]
#314
