### ISSUE TITLE
Razormane Stalker crashing the game

### ISSUE THREAD

**Issue by Morganl32** [FireFly-WoW/FireFly-IssueTracker#159]
**Description:**

Razormane Stalkers in Southern Barrens (Blackthorn Ridge) crash the game when exiting stealth and attacking.

**Current behaviour:**

When the Razormane Stalkers exit stealth and attack the player the client will crash.

**Expected behaviour:**

The client should not crash.

**Steps to reproduce the problem:**

1. Go to Southern Barrens
2. Find Razormane Stalker
3. Receive crash

**Screenshots:**

N/A

**Comment by JunkyBulgaria** [comment]
fixed
