### ISSUE TITLE
Did not receive the "Giddy Up!" achievement as a level 20 Orc

### ISSUE THREAD

**Issue by Morganl32** [FireFly-WoW/FireFly-IssueTracker#160]
**Description:**

I recently leveled up to level 20 and learned the Apprentice Riding skill but was not provided the "Giddy Up!" achievement. I am an Orc, Protection Warrior.

**Current behaviour:**

I did not receive the achievement when learning the Apprentice Riding skill.

**Expected behaviour:**

You are supposed to receive the "Giddy Up!" achievement when learning Apprentice Riding.

**Steps to reproduce the problem:**

1. Reach level 20+.
2. Learn Apprentice Riding.
3. Do not receive achievement.

**Screenshots:**

http://i.imgur.com/WtoDMJ9.jpg

**Comment by JunkyBulgaria** [comment]
have you tried relogging?

**Comment by Morganl32** [comment]
That seems to have done the trick. After logging back on just now I can see I have it. Thank you for the help!

**Comment by JunkyBulgaria** [comment]
yw
