### ISSUE TITLE
Monster Escape pathing+speed 

### ISSUE THREAD

**Issue by Marvin11354** [FireFly-WoW/FireFly-IssueTracker#161]
**Description:**
I was in deadmines and killed some mobs, after they were low they escaped but the pathfinding of them was terrible , they walked into the air to the other pirates instead of walking the way 
In general the speed of the monsters who escape is way to fast and is terrible because they pull fast another group of monsters. 

The monster should escape like in a normal speed ( walking slowly ingame)
The "Escapers" go their normal ways to the other monsters.

**Screenshots:**
http://imgur.com/a/775oY

on this picture the pirate went in the air to reach the other monsters

**Comment by JunkyBulgaria** [comment]
confirmed, the pathing on ship is terrible (as seen of the recast map)

**Comment by Siderbas** [comment]
I think overall escaping speed of mobs is too high, not Only the ones in deadmines.

**Comment by JunkyBulgaria** [comment]
should be fixed with the new mmaps update
