### ISSUE TITLE
(Quest) Tree's Company

### ISSUE THREAD

**Issue by DigitalDevil** [FireFly-WoW/FireFly-IssueTracker#162]
**Description:**

After locating the Naga Flag in Traitor's Cove, I get close enough to apply the tree disguise. After the disguise is applied I wait for the "meeting" to begin, but it never does. Once the disguise wears off I can see the gnome on the rocks to the North East, though he just sits there and if I move in closer, he vanishes. NPC's name is Engineer "Spark" Overgrind.

**Current Behavior:** 

The meeting doesn't take place once disguised.

**Expected behaviour:**
The meeting to initiate after becoming disguised.

CHANGEME: Explain to us how the issue is supposed to work.
Once reaching the Cove and finding that the Naga Flag is present (meaning there will be a meeting present) you are to disguise yourself using the mask/ quest item (tree) and wait patiently for the "meeting" to occur.

**Steps to reproduce the problem:**

1. Step 1 Obtain quest.
2. Step 2 Walk to the quest location.
3. Step 3 Become tree.
4. Step 4 Cry when NPC doesn't move and or doesn't appear.

**Screenshots:**

![wowscrnshot_050117_093800](https://cloud.githubusercontent.com/assets/28262429/25582289/0663aa78-2e52-11e7-9cc8-ba2fb0846f54.jpg)

![wowscrnshot_050117_093809](https://cloud.githubusercontent.com/assets/28262429/25582290/0e0ea3b8-2e52-11e7-94ad-198d53561b73.jpg)

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/f30zlu works fine for me

**Comment by frytik** [comment]
For me too. Closing.

**Comment by frytik** [comment]
Pathing problem's.
