### ISSUE TITLE
Water Walking Bug

### ISSUE THREAD

**Issue by Craankism** [FireFly-WoW/FireFly-IssueTracker#163]
**Description:**
I tried Water Walking as a Shaman and it **only** works when I jump out of the water and press my ablility.
So i doesn't work if I just activate it and try to jump out of the water or activate it before I go in the water. Also it stops working sometimes when you jump or even worse when you mount up.

**Expected behaviour:**
You should be able to activate it while in water and just jump out.
Jumping should work too, while waterwalking.

**Steps to reproduce the problem:**

1. Step 1 Activate Water Walking
2. Step 2 Jump out of the water
3. Step 3 Still not able to waterwalk

For more clarification just contact me on Discord or In-Game.

**Comment by JunkyBulgaria** [comment]
false/positive from anticheat, fixed
