### ISSUE TITLE
(Mailbox) Issue

### ISSUE THREAD

**Issue by DigitalDevil** [FireFly-WoW/FireFly-IssueTracker#164]
**Description:**

Yesterday I had listed a few things on the AH. I noticed one thing in my mailbox a while later that told me transfer pending so I left and came back later on. Unfortunately I didn't think to screen shot that message, but when I went back to check on it, the letter had disappeared from my mailbox so I lost out on 22s. About an hour later I had the same message for a different item pending transfer so I made sure to screen shot it this time, as to not lose out on any more funds. After logging in today, same issue... no message, no funds :( 

**Current behaviour:**
Mailbox seems to be screwy.

Not receiving transfered funds, as the messages with money disappear from mailbox before receiving them.

**Expected behaviour:**
I expect to open my mailbox and receive funds from transactions that took place via the AH.

You look on the top left of your screen and gasp in excitement, as you notice this lovely envelope just begging to be gotten to. You finish up your questing and run over to the nearest town and find the mailbox. After opening the mailbox, you see tons of letters with money attached and shriek in enjoyment as you rack up money to save in order to buy your first mount.

**Steps to reproduce the problem:**

1. Step 1 Sell something on AH
2. Step 2 Wait for a buyer
3. Step 3 Go to mailbox in excitement just to realize that your letter is *poof* gone.
4. Step 4 (Mind you I believe this to be random, though someone else in my guild also said the same exact thing happened to them) Rush to mailbox to receive funds, just to discover the letter with said funds is just randomly gone.
5 Step 5 Cry uncontrollably before logging out and go to bed just to dream of that awesome mount you could buy if said money had been attached to that letter as it should be.

**Screenshots:**

![wowscrnshot_050117_000259](https://cloud.githubusercontent.com/assets/28262429/25586668/f17a5788-2e65-11e7-8f46-003e6c1b8385.jpg)

(Like said above, I don't have the second screen shot of the other transaction letter which poofed before giving me my funds as I didn't expect for the letter to vanish out my box before I was able to grab my funds out)

**Comment by JunkyBulgaria** [comment]
needs testing as i couldn't reproduce it neither dread

**Comment by JunkyBulgaria** [comment]
it didn't gave you the money or?

**Comment by TheOddTruth** [comment]
@JunkyBulgaria .. The money was not and still has not been received. It has been well past the ~00:00 svt as it has now been well over 24 hours since the transaction.

**Comment by DigitalDevil** [comment]
Sorry for the confusion, the money (funds) never made it to me even though the items were sold.  Been waiting since early yesterday evening for the first one to come through. I highly doubt either transfer will make it to me at this point. Its very upsetting and I have since not posted ANYTHING to AH due to fear of just losing not only the funds to list them, but also the item and the funds I would get once the item sold. I really hope this issue can be resolved as soon as possible so I can rest assure if I list anything else, I will receive the transaction funds! Thank you to the staff team for further looking into this issue :)

**Comment by JunkyBulgaria** [comment]
still needs testing after current updates
