### ISSUE TITLE
Smelting link not showing

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#165]
**Description:**

Mining/Smelting proffession link button not showing

**Current behaviour:**

When i open my smelting menu, the link symbol is not showing

**Expected behaviour:**

Smelting should be linkable in chat, meaning the golden colored link symbol should be present.

**Steps to reproduce the problem:**

1. Step 1
Learn smelting and open the menu.

2. Step 2
3. Step 3

**Screenshots:**
![asas](https://cloud.githubusercontent.com/assets/5167458/25588675/ef11b148-2eb1-11e7-93a8-c55c37f326c0.jpg)

**Comment by JunkyBulgaria** [comment]
aren't you supposed to link it trough SHIFT+left click while your chat is open? i haven't seen this UI option on retail
