### ISSUE TITLE
Game freezez in STV

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#168]
**Description:**

Game freezez, can't even alt tab, have to restart.

**Current behaviour:**

Whenever i get to zones where stealthed panthers are, my game freezes over and over, and i have to restart the pc since i can't even alt tab to task manager.

**Expected behaviour:**

Your game should not freeze. ever xD

**Steps to reproduce the problem:**

1. Step 1
Go to Stv near the mound where the white panther Bangalash is or south-west of Mosh'Ogg Ogre Mound and just run around where you know stealthed panthers are.
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
global stelth issue freezing the client by sending too many unit flag updates, fixed
(fix will be applied @ 5am SVT when we restart for daily updates)
