### ISSUE TITLE
Corpse despawn time.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#169]
**Description:**

Corpses of slain enemies despawn too fast. This leads to possible lost loot if you fight multiple mobs and don't loot infight.

**Current behaviour:**

If you engage a fight with 2-3 mobs it's possible that the corpse of the first killed mob despawns before you killed the other mobs.

**Expected behaviour:**

After talking with RL friends and players ingame we came to the conclusion that mob corpses shouldn't despawn that quick.

**Steps to reproduce the problem:**

1. Kill mob
2. See how fast the corpse despawns
3. Cry about lost loot because it despawned so fast.

**Comment by JunkyBulgaria** [comment]
they despawn in atleast 3 minutes by default, which mobs have you treid?

**Comment by Siderbas** [comment]
Pretty much every alliance mob up till lvl24, definitely not 3min. Last mobs I killed and noticed that were gnolls in wetlands. Will test this issue further later today. (maybe it had sth to do with clipping range)

**Comment by Ruedigervanhorn** [comment]
I can confirm this. Despawn time (without looting) is 1 minute for me.

Video:
https://www.youtube.com/watch?v=iqvhJNnEtWY

**Comment by TW1NKLET** [comment]
### DEFAULT TIMER(S) IF CREATURE IS NOT LOOTED (DECAY RATE)
* NORMAL CREATURES DECAY AFTER **60 SECONDS**
* RARE CREATURES DECAY AFTER  **300 SECONDS**
* ELITE CREATURES DECAY AFTER  **300 SECONDS**

**Comment by Siderbas** [comment]
well, just "felt" a bit off then i guess, cause masspulling mobs, and not beeing able to loot the first killed was strange.

**Comment by JunkyBulgaria** [comment]
currently it is set to the default as @TW1NKLET mentioned so i don't see any issues

**Comment by TW1NKLET** [comment]
> Yes, it's easily miss understood with the re-spawn system; most creatures are set to re-spawn within 5 minutes.
