### ISSUE TITLE
walk/run toggle stuck on walk after fighting?

### ISSUE THREAD

**Issue by MINDGAM3** [FireFly-WoW/FireFly-IssueTracker#17]
log in and can run around.
get in a fight
afterwards i can only walk
doesnt happen every fight
the walk/run toggle "numpad /" (works before a fight but not when u get stuck walking) 
but i need to log out and log back in to run again.

anyone else getting stuck on walk after being in a fight?

**Comment by MINDGAM3** [comment]
i think it maybe after being bashed or stunned i get stuck in walk

**Comment by tjukoela** [comment]
I confirm

**Comment by JunkyBulgaria** [comment]
Needs testing to confirm if still bugged after today's update.

**Comment by JunkyBulgaria** [comment]
closing it as it works as intended, if there are any issues feel free to comment/re-open this issue
