### ISSUE TITLE
Warrior stuck after charging

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#170]
**Description:**

Character beeing stuck after charging to an enemy/jumping on the train between SW and IF.

**Current behaviour:**

My (human - female) warrior gets stuck and warps weirdly around for a few seconds after charging to an enemy. This has occured only sometimes - I haven't found a clear pattern yet.

The same happened when jumping while beeing on the train between SW and IF - got stuck in the air for a few seconds and fell to the ground while the train kept on driving.

**Comment by JunkyBulgaria** [comment]
fixed
