### ISSUE TITLE
Quest Red Snapper - Very Tasty!

### ISSUE THREAD

**Issue by Nasuuna** [FireFly-WoW/FireFly-IssueTracker#171]
Murloc Spawns

When you trigger the murlocs running away, they instead despawn.

Simple to reproduce, just spawn a murloc, trigger it to run away.

Happened about 8-9 times.

**Comment by TW3TY** [comment]
I don't quite understand the issue? Is the quest complete-able?  When you run away from the creature? They despawn? Is that the issue? @Nasuuna

**Comment by Nasuuna** [comment]
When you get the murlocs to 10-15% (the trigger for them to runaway), they despawn

**Comment by TW1NKLET** [comment]
> I'm not sure if they're missing their SAI
```SQL
DELETE FROM `smart_scripts` WHERE (source_type = 0 AND entryorguid = 17102);
INSERT INTO `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) VALUES
(17102, 0, 0, 0, 2, 0, 100, 1, 0, 15, 0, 0, 25, 1, 0, 0, 0, 0, 0, 7, 0, 0, 0, 0, 0, 0, 0, 'Angry Murloc - Between 0-15% Health - Flee For Assist (No Repeat)');
```

**Comment by Nasuuna** [comment]
ya its kind of odd, i should of tried to see if dragging them away from their spawn pool causes a despawn as well but it didn't cross my mind.

**Comment by Nasuuna** [comment]
Also, is there a specific way you guys would like bugs ticketed, I have been notepadding the surprisingly few (amazing job btw) that I see.

**Comment by JunkyBulgaria** [comment]
we already got this SAI line, couldn't reproduce this issue

**Comment by TW1NKLET** [comment]
Could it be the threat radius that got fixed earlier? Some reported on Discord that mobs of evaded easily.
