### ISSUE TITLE
[Paladin] Hammer of justice and interrupts.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#172]
**Description:**

If you use the Paladin spell "Hammer of justice" to interrupt a spell from a mob (not tested in pvp) and you miss the spell, the casted spell will get interrupted even though the mob didn't get stunned.

**Current behaviour:**

Spell interrupts without stunning.

**Expected behaviour:**

There shouldn't be a spell interrupt from a missed Stun spell.

**Steps to reproduce the problem:**

1. Find Caster mob.
2. Cast Hammer of Justice
3. Miss the spell.
4. Still Interrupt the enemy spell without stun.

**Comment by JunkyBulgaria** [comment]
fix applied

**Comment by Hotshot333** [comment]
WoW Hotfix (2009-06-08): "When immune to the stun of following abilities, Maim, Bash, and Hammer of Justice will no longer cause player spells to be interrupted but they will still interrupt NPCs.

Wrath Patch 3.0.3 (04-Nov-2008): The interrupt from this ability will also be redirected when the stun is redirected. In addition, the interrupt will now work on targets immune to stun.

From what i see, the stun and interrupt from this spell are 2 separate things. As the tooltip also says "Stuns the target for X seconds and interrupts non-player spellcasting for 3 seconds" If you do manage to land the stun on an npc who is casting, the spellcasting will obviously be interrupted but then what's the point of specifying in the tooltip that it stuns AND interrupts? It seems to me that in case you miss the 5 second stun, you still interrupt the spell casting non the less. This is how it worked on most servers that i've played on at least.

**Comment by Siderbas** [comment]
If what you researched is correct, and by thinking about it a second time I also think that it is. Then this is working as intended and can be closed :)

**Comment by JunkyBulgaria** [comment]
not really, i saw the exact same text and i confirmed that the hammer did not interrupt npcs so it's fixed now and needs testing
