### ISSUE TITLE
Warrior: Talent: Stance Mastery

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#173]
**Description:**

Talent "Stance Mastery" which is suppose to give you 10 rage points when you change stances doesn't work.

**Current behaviour:**

Whenever you change stances you wont get 10 rage!

**Expected behaviour:**

You should get 10 rage whenever you change stances.

**Comment by Ruedigervanhorn** [comment]
You _retain_ up to 10 rage whenever you change the stance. For this, you have to have at least 10 rage in the first place. You won't get any additional rage for changing the stance.

**Comment by Deathtremor** [comment]
Oh it's retain. I was reading obtain. Sorry. 

It's works. 

Can be closed.
