### ISSUE TITLE
Global: Global pathfinding issues.

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#174]
**Description:**

There is several pathfinding issues that need a lot of polishing.

**Current behaviour:**

Mobs&NPC are not properly following ground if the surface isn't flat.- Flying, going through texture, odd jumping off from hills...etc. 

I've seen this globaly. Even in Dungeons.

I'm not a Dev, but this feel like critical Core issue, since happening everywhere and it's complately random.

It's hard to reproduce and capture these issues since they are happening very randomly. These 3 pictures are very basic example of what i've seen in game so far and i managed to capture.

NPC's walking through texture

![wowscrnshot_050117_151854](https://cloud.githubusercontent.com/assets/27430839/25605454/36e584d0-2f4e-11e7-8625-663d589a9e06.jpg)

After I get of tram i ended up like this. On the other side of the room in the air.

![wowscrnshot_050117_150347](https://cloud.githubusercontent.com/assets/27430839/25605456/3c46478e-2f4e-11e7-8271-79bed9aabab2.jpg)

This mob was kinda jumping & flying instead of properly walking on the ground. 

![22](https://cloud.githubusercontent.com/assets/27430839/25605697/129a1b20-2f50-11e7-92a3-c90aadd880f3.jpg)

**Comment by Deathtremor** [comment]
These two issues are related. https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/188

**Comment by Deathtremor** [comment]
These Skeletons followed me through ground everytime I pull them to the tomb. 

![wowscrnshot_050317_210947](https://cloud.githubusercontent.com/assets/27430839/25659118/9aaa431a-3049-11e7-9599-0e9d943a3fb4.jpg)

**Comment by frytik** [comment]
Should be fixed soon. Fix is done. :1st_place_medal:
