### ISSUE TITLE
Loot issues

### ISSUE THREAD

**Issue by sarkubocael** [FireFly-WoW/FireFly-IssueTracker#177]
Loot tables are a bit messy it seems. Items RAre that are sopose to be hard to drop from mobs and dungeons drop way too easy while simple stuff with high loot chance wont drop.
Iwe mined about 20+ copper ores so far not a single rough stone droped, and they are sopose to be plentyfull, and i get alot of gems with the ore instead that are sopose to be rarer and ore is spawning one atop another...

https://puu.sh/vCXd5/6c800035f6.png
https://puu.sh/vCXpR/076b085a2a.png
https://puu.sh/vCXqQ/ed62afcf14.png
https://puu.sh/vCXsa/80eaa33187.png

**Comment by TW1NKLET** [comment]
### Update 1
> Quantity and drop chance of **Rough Stone** / **Coarse Stone** from **Copper Vein** and **Tin Vein**.

```SQL
UPDATE `gameobject_loot_template` SET `Chance`=50, `MaxCount`=6 WHERE `Item`=2835 AND `Entry` IN (1502, 1735, 2626, 18092);
UPDATE `gameobject_loot_template` SET `Chance`=50, `MaxCount`=8 WHERE `Item`=2836 AND `Entry` IN (1503, 1736, 2627, 18093);
UPDATE `gameobject_loot_template` SET `MaxCount`=4 WHERE `Item` IN (2770, 2771) AND `Entry` IN (1502, 1503, 1735, 1736, 2626, 2627, 18092, 18093);
```

**Comment by Deathtremor** [comment]
Strange. I farmed already over 700 copper ore and every single node dropped rough stone.

**Comment by JunkyBulgaria** [comment]
fixed
