### ISSUE TITLE
Buged quest "Tomber's Supplies"

### ISSUE THREAD

**Issue by sarkubocael** [FireFly-WoW/FireFly-IssueTracker#178]
The quest tells you to go pick up a crate that hold a quest item, the crate doesnt have the usuall quest item glow and once somebody loots it it doesnt re-appear till server restart...

https://puu.sh/vCXvN/bf2874597f.png

https://puu.sh/vCXwY/5c9df2a27d.jpg

https://puu.sh/vCXyo/05b4890007.png

**Comment by TW1NKLET** [comment]
> Possible fix
```SQL
-- SET RESPAWN TIMER TO 120 SECONDS
-- SET "ANIMPROGRESS" TO 100 FOR CHESTS
-- SET STATE TO 1 FOR CHESTS

UPDATE `gameobject` SET `spawntimesecs` = 120, `animprogress` = 100, `state` = 1 WHERE (id = 181133) AND (guid IN (27464));
```
