### ISSUE TITLE
Quest: Portals of the Legion

### ISSUE THREAD

**Issue by LucasHell** [FireFly-WoW/FireFly-IssueTracker#179]
**Description:**

The portals work and after killing the guardian you get the quest credit but the portals can be reused immediately.

**Current behaviour:**

The portals does not despawn/become inactive after using them.

**Expected behaviour:**

The portals should despawn (for about five minutes according to wowhead comments) after using them.

**Steps to reproduce the problem:**

1. Get quest "Portals of the Legion"
2. Click portals in Mannoroc Coven
3. Kill guardian that spawns from portal

**Screenshots:**

Not sure how a screenshot will help in this issue but here is one where you can see the corpse of the guardian by the not despawned portal.
http://imgur.com/a/MDcRJ

**Comment by Demmye** [comment]
Confirmed, the portal should despawn instantly after the guardian is killed, and it doesn't.
