### ISSUE TITLE
Game freezes when engaged by stealthed targets

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#181]
**Description:**

Game freezes when attacked by panthers in stv and humanoids in alterac, both stealthed.

**Current behaviour:**

Game freezes and the only solution is to force shut down

**Expected behaviour:**

I am aware that you guys were working on this issue. It doesn't seem to happen everytime now, but it still happens offten.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
fixed

**Comment by Siderbas** [comment]
Does not seem to be entirelyfixed on the current built. Just had a freeze on the mob: "Syndicate Spy" loc: 63, 46 in Alterac Mountains.
