### ISSUE TITLE
Quest ''An Unusual Patron''

### ISSUE THREAD

**Issue by Merilol** [FireFly-WoW/FireFly-IssueTracker#182]
**Description:**

Quest: An Unusual Patron. If u try to summon the NPC ''Naias'' he doesn't appear or the item can't be used

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: I should use the item ''Gift of Naias'' on Altar of Naias and he should appear

**Steps to reproduce the problem:**

1. Step 1 Fix the quest (?)
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by TW1NKLET** [comment]
Can you just confirm he doesn't spawn behind you? @Merilol
