### ISSUE TITLE
Deeprun Tram - Falling through ground->ported to a cage

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#183]
**Description:**

I don't think it's a bug really worth mentioning as it only occurred once, but after jumping of the deeprun tram while the tram was still moving at the IF station, it looked like I was falling through the ground for a second, but then I was ported to the ticket counter nearby where I was caged.

**Current behaviour:**

This bug only occurred to me once, so except that one time it works as intended.

**Video:**

https://youtu.be/B0rAS4dmu3M

**Comment by JunkyBulgaria** [comment]
fixed
