### ISSUE TITLE
Auction house not sending mail when someone buys

### ISSUE THREAD

**Issue by Fenris95** [FireFly-WoW/FireFly-IssueTracker#185]
**Description:**

Put up 7 cured light hide for 74s99c buyout, three medium leather for 49s99c. All have been gone from the AH listings for other six hours, have received no mail.

**Current behaviour:**

No mail received with gold when items are bought from me on the AH.

**Expected behaviour:**

Should receive my 6G 74S 9C.

**Steps to reproduce the problem:**

1. Put something on the AH as a single item, not a stack, and set a bid and buyout price.
2. Have another account buyout the item.
3. Wait the usual hour and then check mail.

**Screenshots:**

http://imgur.com/a/SNtFA

**Comment by JunkyBulgaria** [comment]
i can't confirm it, needs testing from staff/players

**Comment by TheOddTruth** [comment]
I've heard of a few instances of people randomly not getting funds from auction house transactions in the mail. More often than not it seems to work with some inconsistent instances of the issue.

**Comment by Fenris95** [comment]
Seems it moves / moved the items to the neutral AH.

**Comment by JunkyBulgaria** [comment]
in case of gm restart/crash it moves them, yes
