### ISSUE TITLE
[King of the foulweald]

### ISSUE THREAD

**Issue by Mastertuck** [FireFly-WoW/FireFly-IssueTracker#187]
**Description:**

Mobs doesnt despawn after death.

**Current behaviour:**

When you put down the banner, mobs spawn. WHen you die they stay there.
**Expected behaviour:**

Mobs should despawn after player death.

**Steps to reproduce the problem:**

1. Place flag
2. See mobs spawn
3. Die.
4. See mobs still there
**Screenshots:**

url...
url...
url...

**Comment by TW1NKLET** [comment]
### This quest needs rework, will post when I have time.

- Mobs are currently not attacking the banner.

**Comment by TW1NKLET** [comment]
UPDATE
