### ISSUE TITLE
Mobs running through object

### ISSUE THREAD

**Issue by achristy93** [FireFly-WoW/FireFly-IssueTracker#188]
**Description:**

CHANGEME: Noticed in several places, when fleeing they can run through things sometimes. 

**Current behaviour:**

Runs through terrain objects when fleeing

**Expected behaviour:**

..Shouldn't be running through terrain objects...

**Steps to reproduce the problem:**

1. Find something that flees, bring to low hp and let flee
2. Has to be near an object that normally they couldn't go through

**Screenshots:**

Can't see the body because of the thorn so I marked it in the black box. This has happened several times with this mob spawn.  Sure it's happening in other places too.

43.4, 52.6 in the Barrens

http://i.imgur.com/XzFYBqz.jpg

**Comment by frytik** [comment]
Should be fixed soon. Fix is done. :1st_place_medal:

**Comment by achristy93** [comment]
Working good, thanks
