### ISSUE TITLE
[Quest][Feralas] A Strange Request

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#189]
**Description:**

Description of current behavour:

The questmarker for the quest "A Strange Request" points to the wrong direction.

What it does:

The questmarker points us to the post 3.2 location (north of camp mojache)

How it should be:

Since the game is 3.0.x you have to go to Neeru Fireblade ( Located in Orgrimmar, cleft of shadow) in order to complete the quest instead of northern Feralas, but the Questmarker is still pointing you there.

Wups... forgot to make screenshots in the hurry :(

http://www.wowhead.com/quest=3121/a-strange-request

**Comment by JunkyBulgaria** [comment]
updated to 3.2 locations, use them instead
