### ISSUE TITLE
Flying Trainer and Vendor in honor hold are bugged.

### ISSUE THREAD

**Issue by darzeon** [FireFly-WoW/FireFly-IssueTracker#190]
**Flying trainer doesn't respond to right clicks, and vendor is selling nothing:**
https://ibb.co/g462wQ

**Comment by TW1NKLET** [comment]
- NPC is placed in the wrong location.
```SQL
UPDATE `creature` SET `position_x` = 2741.08, `position_y` = 93.9097, `position_z` = 4.61598, `orientation` = 300 WHERE (id = 35101) AND (guid IN (202334));
```
- Missing items
```SQL
-- Grunda Bronzewing
DELETE FROM `npc_vendor` WHERE (entry = 35101);
INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`, `VerifiedBuild`) VALUES
(35101, 0, 25470, 0, 0, 0, 0),
(35101, 0, 25471, 0, 0, 0, 0),
(35101, 0, 25472, 0, 0, 0, 0),
(35101, 0, 25473, 0, 0, 0, 0),
(35101, 0, 25527, 0, 0, 0, 0),
(35101, 0, 25528, 0, 0, 0, 0),
(35101, 0, 25529, 0, 0, 0, 0);
```

### Not sure what you mean by right click, you are interacting with it - just empty vendor-list. @darzeon

**Comment by TW1NKLET** [comment]
> **NOTE** Hargen Bronzewing is the <Riding Trainer> in **Honor Hold**.

**Comment by darzeon** [comment]
What I mean is even if you right click on it, it doesn't respond or it didn't at least, and by the way, both npcs are gone again.

**Comment by TW1NKLET** [comment]
> @JunkyBulgaria could check that the npc flag is 80 then

**Comment by JunkyBulgaria** [comment]
fixed in ptr
