### ISSUE TITLE
Minor Healing Potion and Auto Attacks

### ISSUE THREAD

**Issue by Okktopod** [FireFly-WoW/FireFly-IssueTracker#191]
**Description:**

After hitting level 10, in Tirisfal Glades, when ever I pick up a Minor Healing Potion and right click on it, nothing happens, and then I can't auto attack anything. The potion was working flawlessly earlier.

**Current behaviour:**

Right clicking on the potion does nothing and disables the ability to auto attack

**Expected behaviour:**

The healing potion should restore lost health and not cause any problems with auto attacks

**Comment by JunkyBulgaria** [comment]
i couldn't reproduce it, needs testing from staff/players

**Comment by balazskvr** [comment]
Happened the same with me using a Lesser Healing Potion -> not able to autoattack (even after switching forms). It seems to be a rare issue, since in most occasions it works perfectly.

**Comment by Demmye** [comment]
Tried to reproduce in various manner, but couldn't. My guess would be that this issue(if still existant) is connected with all 'use' items.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Modified my level to 10, used a Minor Healing Potion. I received the small healing and was able to auto-attack.

Seems alright.
