### ISSUE TITLE
Stealthed quest giver NPC keeps attacking and dying.

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#192]
Dalinda Malem is a questgiver in Desolace (54.9,26.1). She is inside a hostile fort. She is supposed to be stealthed in it and wait until the player accepts the quest chain "Search for Tyranis"and finally escort her to the nearby allied settlement. 
Well, she becomes aggresive towards any enemy units in the area, as soon as she spawn she will start attacking the NPCs around her and end up dead.

She should instead spawn stealthed and only be aggresive AFTER the player accepts the quest to scort her outside.

![wowscrnshot_050317_043832](https://cloud.githubusercontent.com/assets/2714797/25646671/fef827d6-2fba-11e7-9175-1a179edc5b22.jpg)

**Comment by Demmye** [comment]
Seems to be working perfectly fine on PTR and does not aggro anything before the quest is taken.
