### ISSUE TITLE
Dart doesn't drop pet. His nest isn't around either

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#194]
This NPC http://www.wowhead.com/npc=14232/dart should drop the pet in the current patch. This was changed in 3.3.0 where it would no longer drop the pet but spawn in as a world-object http://www.wowhead.com/object=202080/darts-nest

Also Dart's respawn timer is wrong. it took 5 minutes for him to spawn, instead of several hours.

**Current behaviour:**

Dart doesn't drop the pet. I couldn't find the nest either

**Expected behaviour:**

Dart should drop the pet

**Steps to reproduce the problem:**

1. Find Dart.
2. Kill and loot him.

**Screenshots:**

https://i.imgur.com/Sc6FREf.png

**Comment by TW1NKLET** [comment]
> DELETE GAME OBJECTS
```SQL
-- DELETE OBJECTS FROM WORLD, ADDED IN PATCH 3.3.0.10958
DELETE FROM `gameobject` WHERE `id` = 202080;
```

> ADD ITEM TO CREATURES LOOT TABLE
> DEVELOPERS WILL HAVE TO CHANGE THE VALUE **X** FROM THE PERCENTAGE
```SQL
-- ADD ITEM "Darting Hatchling" TO CREATURE "Dart\'s" LOOT TABLE
DELETE FROM `creature_loot_template` WHERE (Entry = 14232) AND (Item IN (48112));
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(14232, 48112, 0, X, 0, 1, 0, 1, 1, '');
```

**Comment by TW1NKLET** [comment]
### THERE ARE MORE THAN ONE CREATURE THAT THIS APPLIES TO - FIX ABOVE IS ONLY FOR ONE CREATURE

> Hatchlings: Leaping, Darting, Razormaw, and Ravasaur Hatchlings no longer drop from their associated rare creatures. Instead, there are now rare nests that spawn which contain these hatchlings. For example, the Leaping Hatchling can now be found in Takk’s Nest rather than as a drop from Takk the Leaper.

**Comment by JunkyBulgaria** [comment]
fixed
