### ISSUE TITLE
[Quest] Prisoners of the Grimtotems

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#195]
http://www.wowhead.com/quest=27245/prisoners-of-the-grimtotems

Most of the NPCs are not in cages.... Its very hard to open them if they are not there. 

How are they even keeping them hostage?! WHy dont they run away! /s

**Screenshots:**
![image](https://cloud.githubusercontent.com/assets/2714797/25650814/bce2d862-2fdf-11e7-9452-6c8415d50c84.png)

**Comment by TW1NKLET** [comment]
Hello there! I can see you still got credit for them, did they despawn correctly? @davidmurcia 
> I believe there's an issue with the spawn locations, since the creatures got their texts and most likely their SAI.

**Comment by davidmurcia** [comment]
THere are just barely any cages around, and the keys drop rate also seems to be low. Anyways, the problem I was describing is the fact that most of the NPCs are placed OUTSIDE any cages. there should be cages around them... As you need to open the cage. (I only found that single one... waited 5 minutes for others to respawn, as they didn't I dropped the quest)

**Comment by davidmurcia** [comment]
ALso, yes, they did despawn correctly :)

**Comment by Demmye** [comment]
It works fluently now, plenty of cages and they despawn just like they did in retail.
