### ISSUE TITLE
Redridge Mountains: Bugged Enemies

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#196]
**Description:**

At 38.36, 41.10 at Redridge Mountains there are two bugged enemies.

**Current behaviour:**

They only interact with the player if they are in direct melee range - they don't move if you are further away.

**Expected behaviour:**

Those enemies should behave like the other Blackrock Outrunner/Grunts in the area (normal aggro range, moving towards a player, ...)

**Steps to reproduce the problem:**

1. Go to 38.36, 41.10 at Redridge Mountains
2. Move a step away and confirm that they won't follow.

**Screenshots:**

http://imgur.com/a/pTpce

**Comment by Siderbas** [comment]
Can confirm this behaviour

**Comment by JunkyBulgaria** [comment]
fixed on ptr
