### ISSUE TITLE
Stonetalon Mountains: Bugged Enemy

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#197]
**Description:**

Bugged Pridewing Wyvern in Stonetalon Mountains at 47.09, 47.42.

**Current behaviour:**

The Pridewing Wyvern can't be clicked nor does it interact with the player in any way - it just floats at the same position. 

I've tried relogging but it was still there.

**Steps to reproduce the problem:**

1. Go to Stonetalon Mountains at 47.09, 47.42.
2. Stand there and study the a Pridewing Wyvern from close, as it will not react in any way. :>

**Screenshots:**

http://imgur.com/a/MNHYB

**Comment by JunkyBulgaria** [comment]
fixed on ptr
