### ISSUE TITLE
Able to enter stealth with debuffs that doesnt allow stealth

### ISSUE THREAD

**Issue by arnioo** [FireFly-WoW/FireFly-IssueTracker#198]
**Description:**

Debuffs that doesnt allow you to stealth like Faerie Fire and Touch of Zanzil doesnt work.

**Current behaviour:**

You can enter stealth as a rogue

**Expected behaviour:**

You shouldnt be able to enter stealth

**Steps to reproduce the problem:**

Duel a druid let him cast Faerie fire on you and enter stealth.

**Screenshots:**

http://prnt.sc/f3pc0i

**Comment by TW1NKLET** [comment]
> SpellInfo.cpp
```C++
// Touch of Zanzil (Rogue quest spell)
if (Id == 9991)
    return AURA_STATE_FAERIE_FIRE;
```

**Comment by frytik** [comment]
Faerie Fire - That's should be working. Touch of Zanzil should be fixed on next restart.
