### ISSUE TITLE
Wetlands: High drop chance at Whelgar's Excavation Site

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#199]
**Description:**

While doing quests at Whelgar's Excavation Site in the Wetlands (33.66, 47.58), I've had an unusual high drop chance of blue items from Mottled Scytheclaw and Mottled Razormaw.

**Current behaviour:**

Multiple blue items were dropped during the time I've completed the quests there.
I've discussed this situation with Siderbas(Github)/Sunshi(ingame) who has done this quest earlier today/yesterday, he didn't have any unusual drop rate of blue items while doing quests in this area.

**Expected behaviour:**

Mottled Scytheclaw: http://db.vanillagaming.org/?npc=1022
Mottled Razormaw: http://db.vanillagaming.org/?npc=1023

**Steps to reproduce the problem:**

1. Go to Whelgar's Excavation Site in the Wetlands (33.66, 47.58)
2. ???
3. Profit

Regarding the items, could a GM please contact me ingame at my character "Subster".

**Screenshots:**

http://imgur.com/a/XuFxw

**Comment by Siderbas** [comment]
Can confirm this, was in voice with him when it happened.
