### ISSUE TITLE
Maraudon doors

### ISSUE THREAD

**Issue by Fenris95** [FireFly-WoW/FireFly-IssueTracker#200]
**Description:**

When you right click the doors outside of Maraudon they open and then instantly start closing.

**Current behaviour:**

^

**Expected behaviour:**

They should stay open for a bit.

**Steps to reproduce the problem:**

1. Just right click the doors outside Maraudon at 38.43, 57.98

**Screenshots:**

**Comment by Demmye** [comment]
Confirmed, if clicked on once, they start closing instantly without even opening fully, but if it is clicked on second time before it closes, it opens completely and stays open for few seconds.
