### ISSUE TITLE
Redridge Mountains: Jumping out of water

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#201]
**Description:**

In Redridge Mountains at Render's Rock (27.59, 8.87) there is a little pond. When trying to jump out of the water, it bugs.

**Current behaviour:**

It looks like you're hitting an invisible wall when jumping out of the pond (see video).

**Steps to reproduce the problem:**

1. Go to Redridge Mountains, Render's Rock (27.59, 8.87)
2. Get wet for me

**Video:**

https://www.youtube.com/watch?v=hbgSGSqmkHo

**Comment by l1z1xmd** [comment]
Hello,
Can confirm the same behavior in the Blackfathom Deeps dungeon, in the waters at the beginning of the instance.

**Comment by frytik** [comment]
Tested. Don't have any problem. Can you re-test that ? Also @l1z1xmd Can you give coords.

**Comment by Ruedigervanhorn** [comment]
Second test: https://youtu.be/kEn_Dgispac

**Comment by frytik** [comment]
Looks like related to anticheat summoning @JunkyBulgaria

**Comment by l1z1xmd** [comment]
@frytik, after you enter the instance, you walk a bit straight ahead through the cave, and then you get to some water that you have to swim through. That's the place I'm talking about.

**Comment by JunkyBulgaria** [comment]
#216
