### ISSUE TITLE
[A-Quest]: Missing In Action

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#202]
**Description:**

The escort quest Missing In Action in Redridge Mountains at Render's Rock (~27.59, 8.87) doesn't seem to behave correctly.

**Current behaviour:**

When the escorted guy moves out of the clipping range, he completely dissappears, even when you move closer again where he would be.

**Expected behaviour:**

Shouldn't disappear when 30m from you, I think.

**Steps to reproduce the problem:**

1. Accept the Alliance escort quest Missing In Action.
2. Let him move out of the clipping range.
3. Run back where he would be.

**Video:**

https://www.youtube.com/watch?v=SclRcJfFNz8

**Comment by Siderbas** [comment]
Can confirm this, had it happen while still in the cave after he engaged the first mobs.
