### ISSUE TITLE
Bugged quest "Boulderslide Ravine"

### ISSUE THREAD

**Issue by malideno** [FireFly-WoW/FireFly-IssueTracker#208]
**Description:**Bugged quest in Stonetalon Mountains 

CHANGEME: Describe the issue here I have 10 Resonite Crystals but it doesn't register them or something...

**Current behaviour:** 

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url... https://ibb.co/bD8SVk
url...
url...

**Comment by MummieSenpai** [comment]
i can confirm quest turn in @ 
Stonetalon Mountains (47, 64)
npc : Mor'rogal

turn in button stays gray and reward is not given
reward on Quest log 
10 Silver
800exp

Quest guy and inv
http://i.imgur.com/Yyz0IRc.jpg

Quest log
http://i.imgur.com/evFhPHL.jpg

**Comment by JunkyBulgaria** [comment]
have you tried relogging after quest is completed?
