### ISSUE TITLE
The Nexus: Grand Magus Telestra boss

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#21]
**Description:**

Her spell which is supposed to put you to the air is broken.

* When you get to the air she complately resets.
* You not always start flying in the air once she casts it on you.
* Sometimes when you get to the air you just stay there stucked - you wont fall down as you are supposed to,

**Comment by JunkyBulgaria** [comment]
Applied fix for point 1 and 3.

Point 2 needs additional testing (from my side).

**Comment by Deathtremor** [comment]
Confirmed. All 3 points fixed.
