### ISSUE TITLE
[Quest] Rescue oox17tn will bug if you abandon it.

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#210]
I failed the quest, I runned forward too much and the chicken despawned. 
I abandoned the quest, and have tried to grab it again where the chicken spawns 2 times, but the chicken isnt there, I cant pick the escort mision again....

**Comment by Siderbas** [comment]
Despawning escort/protect npc, seems to be related to #202 and #203.
