### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Kruger287** [FireFly-WoW/FireFly-IssueTracker#211]
Missing Texture

The textures on the doorways to the trams have blacked out textures

No texture loading

Its a black texture that covers the bulbs on the end of the bars

Should have texture

Texture should not be black

Fix Texture?

![wowscrnshot_050517_020240](https://cloud.githubusercontent.com/assets/28427739/25735122/f455c0e0-3136-11e7-833f-94c68ae65bc9.jpg)

**Comment by JunkyBulgaria** [comment]
we can't fix client-side issues from the server side, could be your client with the s hd wod models
