### ISSUE TITLE
[A] Missing Quest: Kurzen's Mystery

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#212]
**Description:**

The Quest http://db.vanillagaming.org/?quest=207 is Missing from the NPC Brother Nimetz.

**Current behaviour:**

Finished Both Quests http://db.vanillagaming.org/?quest=203 and http://db.vanillagaming.org/?quest=204, Brother Nimetz doesn't offer Kurzen's Mystery. 

**Expected behaviour:**

After finishing the two above mentioned Quests, Brother Nimetz should offer the Quest "Kurzen's Mystery".

**Steps to reproduce the problem:**

1. Finishd "The Second Rebellion" and "Bad Medicine"
2. Check Brother Nimetz
3. See that he doesn't offer "Kurzen's Mystery"

**Screenshots:**

none needed.

**Comment by JunkyBulgaria** [comment]
fixed, you need to complete http://www.wowhead.com/quest=202/colonel-kurzen

**Comment by Siderbas** [comment]
Tested and working, Brother Nimetz is now offering the Quest if you did all the needed prequests!
