### ISSUE TITLE
Walking off the Deeprun Tram train teleports me to the roof and makes me stand on air. 

### ISSUE THREAD

**Issue by svedizz** [FireFly-WoW/FireFly-IssueTracker#215]
CHANGEME: Explain to us how the issue is supposed to work.

It shouldn't throw me into the air whenever I walk off the tram.

**Comment by Siderbas** [comment]
Afaik this only happens while the tram is still moving. And I think that this will probably be fixed with the anticheat overhaul.

**Comment by JunkyBulgaria** [comment]
fixed on ptr
