### ISSUE TITLE
Shaman spell : Water Walking 

### ISSUE THREAD

**Issue by TazzG** [FireFly-WoW/FireFly-IssueTracker#216]
**Description:**

Buggs 1/2 times, it works in the beginning then your character acts as if there was a step and then fall in water, it can't get back onto it unless you debuff the recast the spell.

**Steps to reproduce the problem:**

1. Cast the spell on yourself
2. Run into water
3. It's even more obvious when mounted

**Screenshots:**

**Comment by JunkyBulgaria** [comment]
fix applied, available on ptr realm
