### ISSUE TITLE
[Quest] Bone Collector, missing behavior

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#217]
**Description:**

While looting the Kodo Bones there should be a chance for a Kodo Apparation to spawn after looting.

**Current behaviour:**

Nothing happens after looting the Kodo Bones.

**Expected behaviour:**

After looting there should be a pretty high chance of a "Kodo Apparation" to spawn.

**Steps to reproduce the problem:**

1. Get http://db.vanillagaming.org/?quest=5501
2. Loot http://db.vanillagaming.org/?item=13703
3. See that no http://db.vanillagaming.org/?npc=11521 spawns.

**Screenshots:**

not needed.

**Comment by frytik** [comment]
Need testing after next restart.

**Comment by JunkyBulgaria** [comment]
fixed

**Comment by Siderbas** [comment]
[PTR] Did the Quest 2 times (20x loot) - no Kodo Apparation spawn.
