### ISSUE TITLE
[Desolace] Mobs Magram Stormer and Windchaser missing abilities.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#218]
**Description:**

The mobs Magram Stormer http://db.vanillagaming.org/?npc=4642#abilities and Magram Windchaser are not using all of their abilities. (Stormer only uses Lightning Shield)

**Current behaviour:**

Behave like normal melee mobs, not casters.

**Expected behaviour:**

Both mobs should use their Spells

**Steps to reproduce the problem:**

1. Go to ~69/77 in Desolace
2. Find Magram Stormer and Windchaser
3. See that they are not using their abilities.

**Screenshots:**

not needed.

**Comment by frytik** [comment]
Should be fixed after new restart.

**Comment by JunkyBulgaria** [comment]
fixed
