### ISSUE TITLE
[Quest] Centaur Bounty wrong droprate of Questitem.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#219]
**Description:**

The Questitem http://db.vanillagaming.org/?item=6067 for the Quests "Centaur Bounty" http://db.vanillagaming.org/?search=Centaur+Bounty have a 100% droprate currently

**Current behaviour:**

Questitem has 100% Droprate.

**Expected behaviour:**

Droprate of the ears shouldn't be 100%, more like somewhat between 10% and 20% reading the old Wowhead comments.

**Steps to reproduce the problem:**

1. Go to Magram Village in Desolace.
2. Kill Magram Mobs.
3. Wonder about a 100% Questitem droprate.

**Screenshots:**

not needed.

**Comment by frytik** [comment]
Should be fixed after new restart.

**Comment by JunkyBulgaria** [comment]
fixed
