### ISSUE TITLE
[Desolace] Mob "Outcast Necromancer" missing abilities

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#221]
**Description:**

The mob Outcast Necromancer http://db.vanillagaming.org/?npc=11559 in Desolace is missing his 2 abilities.

**Current behaviour:**

Does not cast or summon, only attacks in melee.

**Expected behaviour:**

Should cast a shadowbolt and occasionally summone a Undead ravager. Abilities from live servers because the vanilla DB doesnt show them, but these are they same they were back then (http://www.wowhead.com/npc=11559/outcast-necromancer#abilities)

**Steps to reproduce the problem:**

1. Go to 64/89 in Desolace.
2. Find a Outcast Necromancer.
3. See that he doesn't use abilities.

**Screenshots:**
 
none needed.

**Comment by JunkyBulgaria** [comment]
fixed
