### ISSUE TITLE
Howling Fjord elevator bug

### ISSUE THREAD

**Issue by Injectionx** [FireFly-WoW/FireFly-IssueTracker#222]
**Description:**
The first horde elevator of Howling Fjord is bugged

CHANGEME: Describe the issue here
When you up in the elevator and you try to pass to the other side it teleports back to the original side

**Comment by JunkyBulgaria** [comment]
thanks

**Comment by JunkyBulgaria** [comment]
need to make sure if it's not anticheat fp tomorrow

**Comment by Demmye** [comment]
It does not teleport you anymore, but I have noticed one strange thing about elevators: once the elevator is almost down and you jump out of them, you get Going Down?(id=964) achievement.
