### ISSUE TITLE
[Dustwallow Marsh] Mob "Defias Conjuror" not using spell.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#223]
**Description:**

Mob Defias Conjuror (http://www.wowhead.com/npc=23590/defias-conjuror#abilities) is not casting Fireball.

**Current behaviour:**

Doesn't cast, only engages in melee.

**Expected behaviour:**

Should cast Fireball.

**Steps to reproduce the problem:**

1. Go to Dustwallow Marsh loc ~63/27.
2. Find a Defias Conjuror.
3. See that he doesnt cast.

**Screenshots:**

none needed.

**Comment by JunkyBulgaria** [comment]
fixed
