### ISSUE TITLE
Quest Helper Bug

### ISSUE THREAD

**Issue by l1z1xmd** [FireFly-WoW/FireFly-IssueTracker#224]
**Description:**
You're quest objectives disappear after taking quests [Investigate the Camp] from NPC Krazek, and/or [The Stone of the Tides] from NPC Baron Revilgaz in Booty Bay.
**Current behaviour:**
After getting the quest [Investigate the Camp] from NPC Krazek, and [The Stone of the Tides] from NPC Baron Revilgaz in Booty Bay, when you look in World Map, and you also have checked "Show quest objectives", most of your quest objectives will disappear as soon as you left click them on the world map.
**Expected behaviour:**

Your quest objectives should still be visible even though you took this quest.

**Steps to reproduce the problem:**

1. Take quest [Investigate the Camp] from NPC Krazek and/or, and [The Stone of the Tides] from NPC Baron Revilgaz.
2. Open World Map.
3. Make sure you have "Show quest objectives" checked.
4. Start by left clicking several quest objectives.
5. Soon most of your quest objectives will disappear.

**Screenshots:**
![wowscrnshot_050617_232858](https://cloud.githubusercontent.com/assets/28388741/25775704/e104a730-32b3-11e7-8169-36fdc9129420.jpg)

Same behavior happens after taking Northern, Eastern and Western Pylons quest from Un'Goro Crater.

**Comment by Deathtremor** [comment]
An addon couse this issues. It happens everywhere. Not sure what addon tho.

**Comment by Siderbas** [comment]
Do you use the wow-pro addon?

**Comment by davidmurcia** [comment]
A workaround is to install Carbonite - It will change the world map and quest log, to ones not bugged.

(And its a great addon anyways, im leaving a v3.34 here)
[AddOns.zip](https://github.com/FireFly-WoW/FireFly-IssueTracker/files/981337/AddOns.zip)

**Comment by l1z1xmd** [comment]
I'm not using that addon, and i didn't meet this bug up until now.

**Comment by JunkyBulgaria** [comment]
related to #314 , probably incorrect packets sent server-side
