### ISSUE TITLE
Portal to Orgrimmar in Acherus not working

### ISSUE THREAD

**Issue by Grodous113** [FireFly-WoW/FireFly-IssueTracker#225]
Description:
After Completing the DK Starting Zone you take a portal to Orgrimmar or Stormwind (based on faction). The portal to Orgrimmar does not work

Current behaviour:
After taking the quest "Warchief's Blassing." When you right click the portal it doesn't work at all.

Expected behaviour:
The portal should take you to Orgrimmar.

Steps to reproduce the problem:

1. Pick up quest "Warchief's Blessing" or the Alliance equivalent.
2. Right Click Portal

**Screenshots:**

![wowscrnshot_050617_203452](https://cloud.githubusercontent.com/assets/28494433/25776952/8894112a-329b-11e7-88f6-b27a8f5aea51.jpg)

**Comment by Siderbas** [comment]
#55 #115 #116 Players still getting blocked here. Last GM Ticket from 1 day ago.
