### ISSUE TITLE
[Quest] Shy-Rotam - NPC not spawning?

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#226]
While doing the quest to slay: http://www.wowhead.com/quest=28742/shy-rotam it seems that the NPC does not spawn. Spent 10 minutes in the area and I didnt see her.

http://www.wowhead.com/quest=28742/shy-rotam

https://i.imgur.com/B5QieCX.jpg

**Comment by JunkyBulgaria** [comment]
should work now
