### ISSUE TITLE
Dungeon: The Oculus: Mage lord Urom - Pre-boss fights

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#23]
**Description:**

The pre-boss fights on the platforms doesnt work properly. 

* Mobs that are supposed to show up once you agro Mage lord Urom are already there. ( Mobs are suppposed to show up after you aggro Mage lord Urom )

* Instead of teleport him self on the other platforms he sometimes "flyes" there. (picture)
![aaa](https://cloud.githubusercontent.com/assets/27430839/25040050/b97493b4-2139-11e7-96b0-f7e1ef9c619c.jpg)

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/ezivz1 at first mobs are not spawned, he blinked on the other isle and then mobs started to come to me (which is not supposed to be..), confirmed.
working on a fix.

**Comment by JunkyBulgaria** [comment]
i'm not sure if it's going to work, i haven't tested the code..
expected behavior:
- he should teleport fine trough all 3 platforms
- mobs won't attack player unless he is on their platform

**Comment by Deathtremor** [comment]
* He seems to teleport fine now.

Issue 1: Mobs start to come to you (flying in the air) from other platforms - **They are supposed to be spawned once you pull him.** 

Issue 2: On the last platform no adds will come at all.

**Comment by JunkyBulgaria** [comment]
teleport fixed, mobs fixed as well. issue 2 will be moved and merged with #105 
thanks
