### ISSUE TITLE
STV: Bugged Enemy - "Bloodscalp Mystic"

### ISSUE THREAD

**Issue by Ruedigervanhorn** [FireFly-WoW/FireFly-IssueTracker#230]
**Description:**

At 26,11 in STV, the Bloodscalp Mystic are bugged.

**Current behaviour:**

They don't move towards you, but you still get damage even if you are further away. Only if you are LOSing them, they begin to move.

**Expected behaviour:**

Moving I guess.

**Steps to reproduce the problem:**

1. Go to 26,11 in STV
2. Get in combat with Bloodscalp Mystic

**Video:**

https://www.youtube.com/watch?v=sWJO6QcQRsE&feature=youtu.be

**Comment by JunkyBulgaria** [comment]
@frytik  movement gen?

**Comment by Demmye** [comment]
This is working completely fine, they are not moving because they are using thrown.

**Comment by Siderbas** [comment]
Not correct @Demmye, they shouldnt use Throw, they should use their abilities, see http://www.wowhead.com/npc=701/bloodscalp-mystic#abilities.

**Comment by Demmye** [comment]
My mistake, apologies. However, after some testing I can see that they are using thrown instead of Lightning Bolt, and they use every other ability correctly(Quick Flame Ward at the start of combat, Healing Wave when they need to heal and Enrage ~20% hp or so).
