### ISSUE TITLE
[Gadgetzan water survey]

### ISSUE THREAD

**Issue by Mastertuck** [FireFly-WoW/FireFly-IssueTracker#233]
**Description:**

Mobs everywhere

**Current behaviour:**

Can only fill flask in middle of lake and mobs doesnt despawn and evade and dont attack

**Expected behaviour:**

Mobs shouldnt evade, should attack and should despawn after an amount of time

**Steps to reproduce the problem:**

It's just there.

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Able to fill the flask, 2 "Centipaar Tunneler" spawn, they are attack,- and killable. - working
