### ISSUE TITLE
Through the Dark Portal! - RIP

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#235]
**Description:**

The Demon NPCs at the bottom of th dark portal are wreacking havok on the horde and ally bases...

**Current behaviour:**

THe Demons attack the Ally and Horde NPCs and overpower them, making it quite hard to make the quests around the area.

**Expected behaviour:**

The demons should be confronted on the second stairs, and the guards should be able to hold them there, allowing for the players to do the initiation quests.

**Steps to reproduce the problem:**

1. Go through the dark portal
2. wait for the demons to rape the guards and proceed to rape you.

**Screenshots:**

https://i.imgur.com/QAADa9o.jpg

**Comment by JunkyBulgaria** [comment]
reduced for the zone, needs testing
