### ISSUE TITLE
Greens Blues and Epix

### ISSUE THREAD

**Issue by Mastertuck** [FireFly-WoW/FireFly-IssueTracker#239]
**Description:**

The drop rate is just too damn high

**Current behaviour:**

Greens Blues and Epix seems to drop at a alarming rate.

**Expected behaviour:**

They shouldnt drop at an alarming rate

**Steps to reproduce the problem:**

1. Step 1 Farm,
2. Step 2 Look at drop behaviour
3. Step 3 Be flappergasted

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment]
Also noticed an overall high droprate but thought it's due to Vanilla Content beeing buffed in any of the patches leasing to 3.3.5

**Comment by Deathtremor** [comment]
True! The drop rate is ridiculously way to high. Feeling when a green, blue or epic item drop is that way complately broken. Wish the drop rate of these items were truly blizz.

**Comment by JunkyBulgaria** [comment]
fixed in #261
