### ISSUE TITLE
Log in & Relog issue

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#242]
**Description:**

After you disconnect due to afk or proper log-out you get teleported from you last known position to position where your HS is set!

**Comment by Fenris95** [comment]
PC crashed in the middle of blasted lands, tp'd to HS location in Orgrimmar. Pusikurac was in shimmering flats, tp'd to HS location in Undercity. Wilhemina was in Duskwallow, tp'd to HS location in Kargath.

**Comment by Siderbas** [comment]
Logged out in Badlands, logged back in in IF.

**Comment by Fenris95** [comment]
Happened again when I used exit game, from blasted lands to org again.

**Comment by Sherrilyn** [comment]
Happened to me too two times in a row when i logged off in the inn in Tranquiellien in Ghostlands and when I logged back in I was where my HS is set in Fairbreeze Village in Eversong Woods.

**Comment by Siderbas** [comment]
Thanks for your reports. Our Developers are aware of this issue and are working on a fix. Sorry for any inconveniences this issue may have caused you.

**Comment by wheezyrabbit** [comment]
Same here. Can't log out without completing quests in a certain area.

**Comment by JunkyBulgaria** [comment]
added several debug lines in core for it, if it happens to someone please notify me here by tagging me or at discord so we can fix it asap

**Comment by JunkyBulgaria** [comment]
If this happens to you after today's update please let me know here so i can fix it.

**Comment by Sherrilyn** [comment]
Seems to be working normally now. Logged in and my character was in a Tranquillien inn where i left it and not in Fairbreeze village where i kept my HS just to test this.

**Comment by Deathtremor** [comment]
Now it doesnt. Still the same issue for me here.

**Comment by JunkyBulgaria** [comment]
fixed
