### ISSUE TITLE
[Quest] Study of the Elements: Rock (Part1)

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#243]
**Description:**

The Quest  Study of the Elements: Rock (Part1) (http://db.vanillagaming.org/?quest=710) currently has a 100% droprate on the Questitem http://db.vanillagaming.org/?item=4626#wh-comments. See comments about bad Droprate.

**Current behaviour:**

100% Droprate on the Questitem.

**Expected behaviour:**

Should have lesser Droprate.

**Steps to reproduce the problem:**

1. Go to Badlands and get the Quest  Study of the Elements: Rock (Part1).
2. Kill Lesser Rock Elemental (http://db.vanillagaming.org/?npc=2735).
3. See that it is 100% droprate.

**Comment by Soockee** [comment]
example of wotlk database (80% there)

http://wotlk.evowow.com/?item=4626
