### ISSUE TITLE
[Mob Behaviour] Kiting backwards after casting.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#245]
**Description:**

Currently casting mobs will kite backwards after finishing the cast even if you are engaged in melee mode and they have LoS to you.

**Current behaviour:**

Running away for a few feets while within LoS/meleerange.

**Expected behaviour:**

Caster mobs should stand still and cast if they have LoS, even if they are in melee.

**Steps to reproduce the problem:**

1. Find any caster mob.
2. Be in LoS with the mob and in melee range.
3. mob turns away for a few feet and starts casting.

**Comment by Deathtremor** [comment]
I can also confirm this. It seems to be related to some but not all npcs which use range spells & abilities.

I would also add that if the npc is out of sight (you standing behind a wall or an object) the npc won't try to go near you on melee range. The npc will just stay at one spot. Once you are within LoS again the npc will shoot / cast on you again.

**Comment by JunkyBulgaria** [comment]
@frytik  could it be movement generator related?

**Comment by frytik** [comment]
Looking at it guys.

**Comment by frytik** [comment]
Fix done. Morning it should be applied.

**Comment by Siderbas** [comment]
While this issue is now better than before it is still persisting on the live realm. Caster mobs are still steping back a bit after each cast. How much they go back seems to be connected to the current latency. while a high latency will make them walk back further, a low latency will make them only step back a bit.

https://youtu.be/yX6pD6yt7Bk

**Comment by thestranger064** [comment]
While caster mobs are somewhat managable, hunter range mobs are really painful to deal with.
