### ISSUE TITLE
Stuck in casting animation

### ISSUE THREAD

**Issue by Fenris95** [FireFly-WoW/FireFly-IssueTracker#246]
**Description:**

Tried to use Cerebral Cortex Compound after completing the quest to receive it in Blasted Lands, character just got stuck in the casting animation. Screenshot below.

**Current behaviour:**

^

**Expected behaviour:**

Should just use the potion.

**Steps to reproduce the problem:**

1. Complete the quest
2. Get the Cerebral Cortex Compound
3. Try to use it

**Screenshots:**
http://i.imgur.com/jevfnrH.jpg

**Comment by Fenris95** [comment]
Happens with the other rewards in the screenshot too

**Comment by Demmye** [comment]
Could not reproduce, seems to be working perfectly.
