### ISSUE TITLE
NPC: Jaedenar Cultist: Missing Abilities

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#248]
**Description:**

NPC: Jaedenar Cultist is missing abilities:

_Curse of Weakness
Shadow Bolt
Shadow Word: Pain_

Source: http://www.wowhead.com/npc=7112/jaedenar-cultist#abilities

**Comment by TW1NKLET** [comment]
> Kind of a duplicate of #249 - 
> All of the **Jaedenar** SAI is posted there and when #249 is closed this can be closed.

Thank you for your report.
