### ISSUE TITLE
Ancient Core Hount untameable with Hunter

### ISSUE THREAD

**Issue by tjukoela** [FireFly-WoW/FireFly-IssueTracker#25]
**Description:**

CHANGEME: Ancient Core Hount is actually untameable with Hunter

Ancient Core Hount is actually untameable with Hunter

CHANGEME: Explain to us (if/how) it currently works.

It should be tameable 

CHANGEME: Explain to us how the issue is supposed to work.

Go to MC and try to tame it

**Comment by JunkyBulgaria** [comment]
Exotic Beasts requires beastmastery. http://prntscr.com/ewgujx
Works as intended http://prntscr.com/ewgutz
