### ISSUE TITLE
Pendant of the Sea Lion

### ISSUE THREAD

**Issue by wheezyrabbit** [FireFly-WoW/FireFly-IssueTracker#250]
For Druids, during the quest "Trial of the Sea Lion", the chest with the "Half Pendant of Aquatic Endurance" in Westfall isn't spawning and making the quest impossible to complete.

**Comment by Spydoc** [comment]
This issue is still present.

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/gatl2y
