### ISSUE TITLE
Quest: A Little Slime Goes a Long Way

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#251]
**Description:**

**Current behaviour:**

The provided quest items "_Empty Tainted Ooze Jar_" and "_Empty Cursed Ooze Jar_" can be used on alive Oozes as many times you want. You can simply finish this quest on a single Ooze without even killing it.

**Expected behaviour:**

To use the provided quest items you are supposed to kill the Ooze first. The Ooze must be dead so you can use the quest item. After you use it, the Ooze is supposed to disappear so can't use it on the Ooze again!

![wowscrnshot_050917_121518](https://cloud.githubusercontent.com/assets/27430839/25836836/690784fc-34cd-11e7-83ff-40813e207663.jpg)

**Comment by TW1NKLET** [comment]
> I'm working on this, will report back with fix. 
Thank you for your report.

**Comment by JunkyBulgaria** [comment]
applied
