### ISSUE TITLE
NPC: Haldarr Felsworn: Missing Abilities

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#252]
Description:

NPC: Haldarr Felsworn is missing abilities:

_Shadow Bolt_

Source: https://wotlk-twinhead.twinstar.cz/?npc=6127#abilities

**Comment by TW1NKLET** [comment]
> Does it currently summon its Imp? @Deathtremor

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Has its Imp summoned but itself doesnt use any ability and only melee attacks.

**Comment by JunkyBulgaria** [comment]
we don't have data for wotlk and what they casted back then so i'd say just imp is enough
