### ISSUE TITLE
Missing cages in Blackhoof Village in Dustwallow Marsh.

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#254]
**Description:**

Cages in which Theramore Prisoners are supposed to be locked are missing!

![wowscrnshot_050517_210253](https://cloud.githubusercontent.com/assets/27430839/25836487/7b1cf774-34ca-11e7-9ad5-dd7116494dac.jpg)

**Comment by TW1NKLET** [comment]
Duplicate of #195
