### ISSUE TITLE
Skoll not spawning - need a check

### ISSUE THREAD

**Issue by tjukoela** [FireFly-WoW/FireFly-IssueTracker#26]
**Description:**

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
He is spawned and working as intended, just killed it. http://prntscr.com/ewgvug
