### ISSUE TITLE
Quest: Rescue from Jaedenar

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#262]
**Description:**

Quest: _Rescue from Jaedenar_ is complately broken.

**Current behaviour:**

There is several broken mechanics!

1. As she she walks, she will not attack anyone. She will just walk and pass all mobs without trying to attack any of them.

2. When she get to a certain place she get stuck and she won't move forward. 

3. When you abandon the quest while she is stuck at the certain place and you accept the quest again she start flying through wall somewhere. 

4. The cage where you're supposed to find her seems to be unlocked, You can open it even without having key: A Strange Red Key (quest item), 

5. After you abandon the quest she should disappear and respawn in the cage again where you can get the quest again. Not enywhere else.

**Expected behaviour:**

* She should walk and attack mobs who attack her or you. 
* She is not supposed to get stuck in any way.
* She is not supposed to fly.
* The cage is supposed to be locked and the only way how you can open is with: "_A Strange Red Key_"

**Steps to reproduce the problem:**

1. Get "A Strange Red Key"
2. Accept the quest
3. Go talk to Arko'narin 
4. Accept: Rescue from Jaedenar
5. **Try do the escort quest.** 

The place where is gets stuck.

![wowscrnshot_050917_231449](https://cloud.githubusercontent.com/assets/27430839/25856195/a2dc15a8-3518-11e7-9e02-78116ac5fd4d.jpg)

The place where she gets stuck and offfer you the quest even tho she is in the middle of escort quest.

![wowscrnshot_050917_232501](https://cloud.githubusercontent.com/assets/27430839/25856209/ad13d588-3518-11e7-98d1-a07c5b634e60.jpg)

When she starts flying.

![wowscrnshot_050917_231605](https://cloud.githubusercontent.com/assets/27430839/25856225/be2231da-3518-11e7-9048-1c6bc77ccfa8.jpg)

**Comment by JunkyBulgaria** [comment]
needs testing on ptr

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Ok so, 

1. Its still possible to open the cage without the key.
2. She is still not beeing attacked by mobs around her, not trys to "help" if the player gets attacked.
3. Pathing seems fine until she gets to the chest in the screenshot, then she just stops there.

**Comment by thestranger064** [comment]
I did this today aswell and it appears everything is not working. 
She does not support players, 
or get attacked by mobs,  
and she just stands at the chest at the end.
I couldnt finish this, and I am just confirming all of this as well, by today on live realm.

**Comment by frytik** [comment]
Fix soon applied.
