### ISSUE TITLE
Razormane Pathfinders

### ISSUE THREAD

**Issue by Okktopod** [FireFly-WoW/FireFly-IssueTracker#263]
**Description:**

Razormane Pathfinders in southern Barrens are running away when you get in melee range.

**Current behaviour:**

They are endlessly running away when you get into melee range making it impossible to kill them without pulling more mobs that are near.

EDIT: not every pathfinder, but most of them
**Expected behaviour:**

They are expected to stay in place

**Comment by Deathtremor** [comment]
Duplicate

https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/245
