### ISSUE TITLE
Randomly Disconnect and return to StormWind 

### ISSUE THREAD

**Issue by JeremyCC95** [FireFly-WoW/FireFly-IssueTracker#266]
Description: Hello, im playing as mage in duskwood but when i arrive at the cementery to do some quests, the game automatically disconnects and when i log in back again i am not where i was disconnected it returns me always to stormwind. I've been sent to StormWind without reason 2 times in 20 min, also, when i disconnect from the game by myself i am returned back to StormWind again ! Since yesterday the game does not let me go out of StormWind.

Current behaviour: Explain to us (if/how) it currently works.

I just suffered this issue two times in the same places but people in my guild are suffering the same problem

**Expected behaviour:**

Expected behaviour: It is easy to know how it must work, the game must not disconnect randomly  taking back you to your hearthstone point also the game must remember where you was disconnected the last time and start there the next time you log in

**Steps to reproduce the problem:**

1. Step 1- Go anywhere from your hearthstone
2. Step 2- walk
3. Step 3- wait to be disconnected and returned back to your hearthstone place

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
fixed

**Comment by JeremyCC95** [comment]
yes, thank you
