### ISSUE TITLE
Teleport to HS location after logging out @ innkeeper

### ISSUE THREAD

**Issue by Arthilas** [FireFly-WoW/FireFly-IssueTracker#267]
Teleport TO HS Location after logging out @ innkeeper / resting area

Everytime (or nearly everytime) you log out @ an innkeeper / resting area, you get teleported to your hearthstones location, which can be quite obnoxious. I do not know what's causing this bug, but it sure is frustrating.

**Comment by Arthilas** [comment]
*UPDATE*

It is now confirmed, that it is EVERYTIME you log out at a resting place, that you get teleported to your hearthstones location

**Comment by Stadics** [comment]
Are you being ported immediately, or after a certain period of time? 
I can't reproduce the issue on the PTR if I log back in within 30 minutes.

**Comment by Arthilas** [comment]
After you log out in an resting area, you get teleported IMMEDIATELY. I tested it several times, and it happened instantly everytime. I logged back in within seconds.

**Comment by JeremyCC95** [comment]
Yes im being teleported in every log in too

**Comment by Stadics** [comment]
I can't reproduce the report on the live realm either. Set HS in Kharanos, logged in IF - still in IF. 
Can you give me specifics of where your HS is set and where you did get ported from?

**Comment by JeremyCC95** [comment]
Doesnt matter where i am, if i log out and i come back the game always send me to Stormwind (HS)

**Comment by Arthilas** [comment]
@Stadics 

For instance. When I logged out @ Southshore inn, I got teleported to Feathermoon Stronghold (Feralas). I attempted to do the same thing, flying to Aerie Peek Inn, logged out. Got teleported to Southshore.

**Comment by Atheras** [comment]
sends me to SW too after every logout when i get back in the game im in SW doesnt matter where I am

**Comment by Arthilas** [comment]
I can confirm, it also happens outside of resting areas. I logged out in Gadzetgan (not innkeeper) and was tped to Feathermoond Stronghold in Feralas.. 👎

**Comment by JunkyBulgaria** [comment]
fixed
