### ISSUE TITLE
[Quest][Northrend][Sholazar Basin] The Mosswalker Savior

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#268]
The Mosswalker Savior cannot be completed

## Issue Description:
The NPC's "Mosswalker Victim" are just laying around. Not interactive at all.

## How it Should be

The "Mosswalker Victim" should somehow be connected to the Undead in this area. After killing the undead, you should be able **to talk** the the victim to release him. This process should proceed the questprogression.

Video at how it could look like - *not sure about blizzlike*:
https://www.youtube.com/watch?v=hd3BcCSDNr4

## How to reproduce

Go into the area and try to interact with the mosswalker victims.

Enemy Npc's may connected to the Quest (See screenshot on wowhead you can see the chain):

 | Blighted Corpse  |
 | ------------- |
 | `28101` |
 |http://www.wowhead.com/npc=28101/blighted-corpse|

**Screenshots:**

![wowscrnshot_051017_143713](https://cloud.githubusercontent.com/assets/24325735/25899640/e0ff30ae-3590-11e7-91f4-c1d0e476c564.jpg)

![wowscrnshot_051017_143727](https://cloud.githubusercontent.com/assets/24325735/25899643/e4668a1c-3590-11e7-80b9-e019c852a043.jpg)

![wowscrnshot_051017_145708](https://cloud.githubusercontent.com/assets/24325735/25899659/faf4d932-3590-11e7-9c3a-38b3a698952a.jpg)

![wowscrnshot_051017_145717](https://cloud.githubusercontent.com/assets/24325735/25899664/fd57f646-3590-11e7-8964-f8ed0269934a.jpg)

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
They are now interactable and the quest ist completeable.
