### ISSUE TITLE
[Items][Arenapoints] Arena Vendor and items

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#269]
The arenavendor in dalaran is still selling ilvl 277 Stuff for arenapoints. I guess that is not intended.
*If it's not intended:*

please check the following vendors aswell:

http://wotlk.evowow.com/?npc=34093

http://wotlk.evowow.com/?npc=34094

http://wotlk.evowow.com/?npc=34095

![wowscrnshot_051017_202255](https://cloud.githubusercontent.com/assets/24325735/25914574/0874538e-35bf-11e7-87ba-21f2dc07438b.jpg)

![wowscrnshot_051017_202311](https://cloud.githubusercontent.com/assets/24325735/25914577/0bea8218-35bf-11e7-880e-bcbb7a104e54.jpg)

**Comment by Stadics** [comment]
Can confirm. Arena gear vendors sell Season 8 gear, and Season 7 gear is available for honor.

**Comment by JunkyBulgaria** [comment]
will be removed after restart, thanks

**Comment by Siderbas** [comment]
See internal Discord for additional info. Reopened to keep track.

**Comment by JunkyBulgaria** [comment]
needs testing as we lost track of it, current issue is solved
