### ISSUE TITLE
Infernal

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#27]
**Description:**

Summon Infernal 

CHANGEME: Describe the issue here

Broken damage&Canceling the main daemon call

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

http://wowwiki.wikia.com/wiki/Summon_Infernal
p.s I think, doomguard broken too, and all battle pets.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/ZKWbu
url...
url...

**Comment by JunkyBulgaria** [comment]
Nothing is broken, in WoTLK you can have only 1 pet despite of it's category (guardian or not). In Cataclysm as warlock you can have 2 active at the same time.
Damage is correct for all of them as well.

**Comment by JunkyBulgaria** [comment]
Closing as this report is invalid, if you have more questions/issues related to this issue feel free to comment/re-open it.

**Comment by Fearevius** [comment]
https://www.youtube.com/watch?v=4owolp7UdSo - Watch the video from 4:40 - this offical wow 3.3.5 patch. On our server, the damage is too low.

**Comment by JunkyBulgaria** [comment]
It scales with master's stats, the warlock from the video has S8, you are testing with Tier 7.5.

**Comment by Fearevius** [comment]
I know that when calling, the character's spd should be checked + 200 damage. Yes, my mistake - I'm sorry.
