### ISSUE TITLE
Wrath totem affects ennemies

### ISSUE THREAD

**Issue by TazzG** [FireFly-WoW/FireFly-IssueTracker#272]
**Description:**

Elemental Shaman's Wrath totem seems like buffing also ennemies while it should affect only raid and party members of the caster.

**Steps to reproduce the problem:**

1. Cast wrath totem in range of an ennemy
2. Check ennemy's buffs

**Screenshots:**

![capture d ecran 2017-05-10 a 21 07 41](https://cloud.githubusercontent.com/assets/27713068/25922455/94b455dc-35d9-11e7-9054-adc5e96105df.png)

url...
url...

**Comment by philoudu16** [comment]
Is that not the "Chance to be critically hit increased by 3%." debuff?

**Comment by TW1NKLET** [comment]
This is working as intended.
> The totem increases spell power by X for all party and raid members, and **increases the critical strike chance of all attacks by 3% against all enemies within 40 yards**. Lasts 5 min.

This issue can be closed.
