### ISSUE TITLE
[Quest][The Storm Peaks] Valkyrion Must Burn

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#273]
The Valkyrion Harpoon Guns shouldn't move.

In this Quests you have to shoot strewbundles with a Valkyrion Harpoon Gun. They are placed around Valkyrion in the storm peaks

**Comment by TW1NKLET** [comment]
> I can't tell for sure if this will do, but to disable the movement seems logical.

--
UPDATE `creature_template` SET `unit_flags` = 4 WHERE (entry = 30066);

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Working now, they no longer move around.
