### ISSUE TITLE
The Grizzled Den not dropping quest item

### ISSUE THREAD

**Issue by Virtanen69** [FireFly-WoW/FireFly-IssueTracker#276]
**Description:**

The Grizzled den doesnt drop Wendigo Manes from young wendigos or Wendigos.

**Current behaviour:**

It doesnt work.

**Expected behaviour:**

They're supposed to drop Manes, dont know about the drop chance but atleast 1 every third kill or something. Now it doesnt drop any.

**Steps to reproduce the problem:**

1. Kill Wendigo or Young Wendigos.
2. Loot
3. Profit???

**Screenshots:**

url...
url...
url...

**Comment by TW1NKLET** [comment]
> This could be missing in **creature_loot_template**.

```SQL
--
DELETE FROM `creature_loot_template` WHERE (Entry = 1134) AND (Item = 2671);
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(1134, 2671, 0, 38, 1, 1, 0, 1, 1, NULL);

DELETE FROM `creature_loot_template` WHERE (Entry = 1135) AND (Item = 2671);
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(1135, 2671, 0, 38, 1, 1, 0, 1, 1, NULL);
```

**Comment by JunkyBulgaria** [comment]
38% as intended, works for me

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Working as intented. Took me 18kills to loot 8 manes and finish the quest.
