### ISSUE TITLE
Hit chance stat is not behaving as expected?

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#278]
**Description:**

Check the hit rating stat in my character to find some non-sensical %... 37 rating->98% hit chance (lvl 68)

**Expected behavior:**

The hit rating should update with your level correctly... 37 rating is not a 98% increased hit chance.

**Screenshots:**

https://i.imgur.com/7QUDTFN.jpg

**Comment by JunkyBulgaria** [comment]
it's normal, you can do the same in retail as well, for example 19 twinks

**Comment by Demmye** [comment]
I believe this is bugged, since at level 68 `1% hit chance=14 hit rating`

**Comment by Siderbas** [comment]
The thing is, would it be a mechanical or only a visual bug.

**Comment by Demmye** [comment]
Tested it on a druid just now, that probably is just visual, because hit scales properly at any level.
