### ISSUE TITLE
[Quest] Finding the phylactery

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#280]
**Description:**
http://www.wowhead.com/quest=11956/finding-the-phylactery

**Expected behaviour:**

https://www.youtube.com/watch?v=4MMADrtadZM

**Screenshots:**
https://i.imgur.com/6doF54D.jpg

**Comment by davidmurcia** [comment]
Yeh, missing object.

**Comment by Hotshot333** [comment]
Missing object confirmed

**Comment by Siderbas** [comment]
[QM] Testing on PTR now.

**Comment by Siderbas** [comment]
Working as intented. Object is there, after clicking the guards and the questmob spawns and drops the questitem.

**Comment by Hotshot333** [comment]
Still can't see the object for some reason

**Comment by JunkyBulgaria** [comment]
it is fixed on ptr, will be on live realm within few minutes

**Comment by Siderbas** [comment]
reopened to due Tickter Number 523. - no object spawned on live realm.

**Comment by JunkyBulgaria** [comment]
should be working now

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Working 100% fine.

**Comment by frytik** [comment]
@Hardcore-FireFly Is the gameobject respawning ?

**Comment by frytik** [comment]
When you try to-do quest 2 times in row.

**Comment by Hardcore-FireFly** [comment]
After completing the quest the first time, I abandoned and retook it using the .quest add command. Waited for like 15 minutes. But it didn't spawn.
