### ISSUE TITLE
[Quest]Into the World of Spirits

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#281]
**Description:**

http://www.wowhead.com/quest=11333/into-the-world-of-spirits
**Current behaviour:**

Missing the pickup item.
**Expected behaviour:**

https://www.youtube.com/watch?v=9ZjR3h1Vg88

**Screenshots:**

![image](https://cloud.githubusercontent.com/assets/2714797/25954850/bdd90a32-3667-11e7-951e-9fd4492ac114.png)

**Comment by TW1NKLET** [comment]
> .go object 56732
```SQL
--
DELETE FROM `gameobject` WHERE (id = 186662);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(56732, 186662, 571, 0, 0, 1, 1, 1032.58, -5153.86, -51.1602, -1.64061, 0, 0, 0, 1, 300, 100, 1, 0);
```

**Comment by davidmurcia** [comment]
Update: The item spawn is on another location, not on a shit where it should have been. Can probably fix the location.

**Comment by TW1NKLET** [comment]
> Location can be solved with the submitted query above.

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/f932kp

**Comment by Siderbas** [comment]
[QM] Testing on PTR now.

**Comment by Siderbas** [comment]
While it's possible to find the pouch more to the north on another ship, comments from wowhead suggest the location on retail was on loc ~62,58.

**Comment by JunkyBulgaria** [comment]
it's fine as is
