### ISSUE TITLE
Quest: Bringing Down Heb'Jin

### ISSUE THREAD

**Issue by LucasHell** [FireFly-WoW/FireFly-IssueTracker#282]
**Description:**

Heb'Jin does not follow his bat down after using the drum. And sometimes the bat does not spawn at all.

**Current behaviour:**

When using the drum (Heb'Jin's drum) Heb'Jin's Bat will fly down without Heb'Jin or not spawn at all.

**Expected behaviour:**

Heb'Jin is supposed to fly on his bat down and attack the player.

**Steps to reproduce the problem:**

1. Use drum

**Screenshots:**

http://imgur.com/a/9E2kR
http://imgur.com/a/dEuYl

**Comment by LucasHell** [comment]
So I tried again and this time he rode the bat down but didn't jump off and returned back to the top of the building. (http://imgur.com/a/6PM6i)

**Comment by Siderbas** [comment]
[QM] Testing on PTR now.

**Comment by Siderbas** [comment]
Working as intented: Hit Drum, Heb'Jin jumps on the bat, flys down, use the net, Heb'Jin dismounts and attacks together with his bat.

**Comment by Shadoki** [comment]
quest is still bugged, he is just stuck midair

**Comment by Siderbas** [comment]
Worked on PTR already, needs retest on current PTR.

**Comment by thestranger064** [comment]
Not working, Nothing happens from the bat, and sometimes he does not spawn
I can even see Heb'Jin but cant interact with him

Ofc he should only drop down from the bird after using the net on the bat.
Screenshots to see the messed up situation.
http://imgur.com/a/Ltdwa

**Comment by Hardcore-FireFly** [comment]
I remember completing this quest on live realm.
Also tested on PTR, working fine.
The only thing is that using the trap on Heb'Jin's bat won't stop it from moving, which is a small issue, and it does not make the quest undoable.
