### ISSUE TITLE
Client freeze on various locations

### ISSUE THREAD

**Issue by l1z1xmd** [FireFly-WoW/FireFly-IssueTracker#283]
**Description:**

Client freezes on flight path and in Stormwind.

**Current behaviour:**

1. Getting the flight path from Ironforge to Stormwind, somewhere in Burning Steppes, near the Altar of Storms (NW of Burning Steppes), may cause the client to freeze unexpectedly. Also after restarting the game, my character was teleported back to my current hearthstone location.
2. I was on my mount on the Canal path from Cathedral Square to Trade District and my game suddenly freeze for no apparent reason. And again my character teleported back to it's current hearthstone location.

**Expected behaviour:**

1. Getting on the flight path from Ironforge to Stormwind should not freeze my game client, nor should teleport my character back to it's current heartstone location on game restart.
2. Game client should not freeze if I wonder around Stormwind, nor should teleport my character back to it's current heartstone location.

**Steps to reproduce the problem:**

1. Get flight path from Ironforge to Stormwind.
2. Wait until your character is somewhere in the NW part of Burning Steppes, near the Altar of Storms.
3. Client may freeze.
OR
1. Get on mount
2. Walk from Cathedral Square on the Canal path towards Trade District.
3. Client may freeze.

**Comment by JunkyBulgaria** [comment]
are you using warmane's custom "hd" model patch?

**Comment by l1z1xmd** [comment]
No, I am not using that model patch, just the game client provided by your website. I also recently formated my computer so I guess it's not a PC issue. And about addons, I have been using these addons on other servers without having any problems.

**Comment by JunkyBulgaria** [comment]
needs testing from other players

**Comment by Siderbas** [comment]
I will look into it when I'm playing later, never experienced such a behaviour so far.

**Comment by Siderbas** [comment]
Couldn't reproduce any of this, anyone else?

**Comment by l1z1xmd** [comment]
I never experienced this thing before on the same routes till yesterday. I didn't even experience this thing today, so maybe it was just bad luck? Hopefully.

**Comment by Hotshot333** [comment]
My client also froze twice in 1 day, while on a FP from Howling Fjord -> Storm Peaks, when i was somewhere above Grizzly Hills client froze, only option was to restart the system. Second freeze was on my way back from Storm Peaks to Grizzly Hills, froze somewhere in Zul'Drak. I've been using the same client forever, this never happened on other servers. It's either something server related or addon related. Asked 2 other players, they also experience FP client freeze at least once.

**Comment by JunkyBulgaria** [comment]
visibility packet handling improved, this should be no longer an issue
