### ISSUE TITLE
[NPC] Coldarra Mage Slayer 

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#284]
**Description:**
Location: Outside of the nexus

The doges that follow the Coldarra Spellbinders will follow you after you kill the owner forever, until you stealth or relog or do something to force an aggro reset, and they will evade your attacks 4ever.

**Screenshots:**

https://media.giphy.com/media/3o7btYSkdrDzt7NCk8/giphy.gif

**Comment by JunkyBulgaria** [comment]
related to movement gens

**Comment by frytik** [comment]
@JunkyBulgaria No, General evade problem

**Comment by Demmye** [comment]
Could not reproduce, even after Spellbinders die they don't evade.
