### ISSUE TITLE
The Nexus meeting stone wont allow summons (And maybe others)

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#285]
**Description:**

I cant complete a summon to my party members.

**Current behaviour:**

The click icon will be blanked out, not allowing me to complete someones summon.
**Expected behaviour:**

I should be able to interact with the summoning ritual

**Steps to reproduce the problem:**

1. form a group
2. start to summon someone of the group
3. try to complete the summoning

**Screenshots:**

https://i.imgur.com/rsCeA1K.jpg

**Comment by JunkyBulgaria** [comment]
you are in combat with something

**Comment by davidmurcia** [comment]
Lul. Might be the bug I reported before.
