### ISSUE TITLE
Enemy ranged NPCs from Tanaris (at least) have pathfinding issues 

### ISSUE THREAD

**Issue by l1z1xmd** [FireFly-WoW/FireFly-IssueTracker#287]
**Description:**

Enemy ranged NPCs from Tanaris have pathfinding issues.

**Current behaviour:**

After getting aggro from a enemy ranged NPC in Tanaris (at least) they won't follow me even though I LoS them, they just stay put in a fixed position. Also when trying to reach them in melee range they begin to run from you, making it very difficult to kill them as they usually run towards other groups of mobs making me aggro them also.

**Expected behaviour:**

If you LoS a enemy ranged NPC from any zone, they should follow you so that they are able to attack you, and not stand still. Also if you run towards enemy ranged NPCs they should not run from you (at least not continuously).

**Steps to reproduce the problem:**

1. Find a enemy ranged NPC from Tanaris.
2. Aggro him.
3. LoS him.
4. The NPC will stand still, and not follow you to attack you.
5. Run towards the NPC to attack him in melee range.
6. He will continuously run from you.

**Screenshots:**

![wowscrnshot_051217_163843](https://cloud.githubusercontent.com/assets/28388741/26001263/76b8e924-3734-11e7-99f1-02c97bfbb011.jpg)

**Comment by Stadics** [comment]
Can confirm. Unusual combat and movement behavior. 
There is a general issue with physical range attack mobs, could be based on that.

**Comment by Siderbas** [comment]
Related to #245

**Comment by frytik** [comment]
Bad SAI. Should be fixed in new restart.

**Comment by Siderbas** [comment]
so you dont think its related to 245? because this behaviour (standing still while LoS) is with all mobs, not only with those in the SS.

**Comment by l1z1xmd** [comment]
As I leveled more, I can confirm that all enemy range NPCs from every zone I went through behave in the same manner.

**Comment by frytik** [comment]
Fix done. Morning it should be applied.

**Comment by frytik** [comment]
Any update of this ?

**Comment by Siderbas** [comment]
[QA] Just tested this on the PTR on the same spot seen in the Screenshot. Still not following after LoS. https://youtu.be/5Y65M-NIGp0

**Comment by frytik** [comment]
Should be fully fixed on live tommorow. @Siderbas

**Comment by JunkyBulgaria** [comment]
global issue with all SmartAI npcs, if they have throw-like spell they do not move

**Comment by frytik** [comment]
It is still done ?

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Aggroed a Shadow Adept (a ranged npc in Icecrown). She started following me as soon as I ran away and LoSed her.
