### ISSUE TITLE
[Quest] Rescue OOX-22/FE!

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#288]
**Description:**

Quest (quest=25476) won't complete when hitting the road, the chicken just keeps on running west.

**Current behaviour:**

Escort, test output, ambush spawn works perfetly but you wont get a complete message when you hit the road.

**Expected behaviour:**

The Quest should complete after the ambush once you hit the road. see video.

**Steps to reproduce the problem:**

1. Get the Quest.
2. Escort the chicken, defend it against the ambush, see no completion message at the road.

**Video:**

https://www.youtube.com/watch?v=DAuJLGV3TUk

**Comment by Siderbas** [comment]
Same with "Rescue OOX-09/HL!" (quest=836)

**Comment by JunkyBulgaria** [comment]
both fixed

**Comment by Siderbas** [comment]
[QA] Can't test right now to due missing .additem command.

**Comment by Demmye** [comment]
It now works on PTR.
