### ISSUE TITLE
[Quest] ... Or Maybe We Don't

### ISSUE THREAD

**Issue by iKlump** [FireFly-WoW/FireFly-IssueTracker#289]
**Description:**

http://www.wowhead.com/quest=12198/or-maybe-we-dont

**Current behaviour:**

The golem doesn't get energized after killing Lightning Sentries.

**Expected behaviour:**

https://www.youtube.com/watch?v=vez8QL_dnTY

**Comment by TW1NKLET** [comment]
> Duplicate of #257, thanks for your report however.
