### ISSUE TITLE
Frostweave Cloth

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#29]
**Description:**

Broken drop.

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

This item drops from mobs in Northrend, most often from humanoids or humanoid-like creatures. 

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/ZJOnD
url...
url...

**Comment by JunkyBulgaria** [comment]
Incorrect report, also it drops from this chest as well because the dungeon is lvl80.

**Comment by Fearevius** [comment]
I'm playing on the server warmane - there's exactly the same problem. I'm not sure how to correctly prove an error, but if you want an overabundance of this material - ignore this report.

**Comment by JunkyBulgaria** [comment]
http://www.wowhead.com/object=193597/dark-runed-chest
http://www.wowhead.com/object=190663/dark-runed-chest

The loot data is sniffed from official servers and is 100% correct, it's like that even in wowhead.

**Comment by Fearevius** [comment]
I'm not only about this trunk, but about the situation with the fabric as a whole. Later I will make a few more screenshots.

**Comment by JunkyBulgaria** [comment]
If there is an issue with a npc's loot from your screenshots it will be fixed, as of now i don't see anything bugged in this one so this issue stays closed till your new screenshots.
