### ISSUE TITLE
[Quest]: The Drakkensryd

### ISSUE THREAD

**Issue by LucasHell** [FireFly-WoW/FireFly-IssueTracker#290]
**Description:**

It is not possible to cast any spells on the Hyldsmeet Drakeriders.

**Current behaviour:**

It is not possible to cast any spells on the Hyldsmeet Drakeriders. They are always out of range for spells but melee attacks work.

**Expected behaviour:**

You should be able to cast spells on the drakeriders.

**Steps to reproduce the problem:**

1. Get quest "The Drakkensryd"
2. Use harpoon to jump to drake with rider on
3. Try to cast a spell

**Comment by TW1NKLET** [comment]
> Duplicate of #274, thanks for your report however.
