### ISSUE TITLE
[Quest]:  The Super Snapper FX

### ISSUE THREAD

**Issue by lineagedr** [FireFly-WoW/FireFly-IssueTracker#291]
**Description:**
The quest gives you the item: Super Snapper FX which you use to take a snapshot of 'Gammerita' the turtle mob

**Current behaviour:**
When using the Super Snapper FX on 'Gammerita' nothing happens.

**Expected behaviour:**
After using Super Snapper FX on 'Gammerita' the quest should complete.

**Steps to reproduce the problem:**

1. Get the quest "The Super Snapper FX"
2. Find the mob 'Gammerita'
3. Use Super Snapper FX

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Tested and working on the PTR.
