### ISSUE TITLE
Ironforge Lava

### ISSUE THREAD

**Issue by lineagedr** [FireFly-WoW/FireFly-IssueTracker#292]
**Description:**
Legit fell into the lava at the Great Forge in Ironforge and died, After dying I tried to release spirit but it doesn't send you to the spirit healer it just sends you to the place you died (in the lava). Also tried to unstuck while dead but after the cast nothing happens.

**Current behaviour:**
After dying in the lava at the Great Forge, and clicking on release spirit, it doesn't teleport you to the spirit healer.

**Expected behaviour:**
It should teleport you to the spirit healer.

**Steps to reproduce the problem:**

1. Go to Ironforge
2. Jump into the lava at the Great  Forge
3. Click Release spirit.

**Comment by Demmye** [comment]
Couldn't reproduce, seems to be working fine.
