### ISSUE TITLE
Into Utgarde! quest and no loot from the end boss

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#294]
**Description:**

Last boss in Utgarde Keep dropped no loot whatsoever, no items or quest item

**Steps to reproduce the problem:**

1. Kill Ingvar.

**Screenshots:**
https://imgur.com/uDIQOZZ

PS - FALL1N we really do love you.

**Comment by JunkyBulgaria** [comment]
fixed

**Comment by Soockee** [comment]
Still no loot in HC
![wowscrnshot_052017_160922](https://cloud.githubusercontent.com/assets/24325735/26276373/b88a035e-3d76-11e7-81e1-71acddd151d3.jpg)
![wowscrnshot_052017_160924](https://cloud.githubusercontent.com/assets/24325735/26276374/ba8f40f6-3d76-11e7-8635-2b244e9eebb5.jpg)
