### ISSUE TITLE
Razormane Hunters have two pets

### ISSUE THREAD

**Issue by Fenris95** [FireFly-WoW/FireFly-IssueTracker#297]
**Description:**

Razormane hunters have two wolf pets, one is a companion and one isn't, both follow them around.

**Current behaviour:**

Two pets.

**Expected behaviour:**

One pet.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://i.imgur.com/ePIsALH.jpg

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.
