### ISSUE TITLE
Quest: As the Crow Flies

### ISSUE THREAD

**Issue by Nasuuna** [FireFly-WoW/FireFly-IssueTracker#299]
After the automated flight around zangramarsh completes you are locked into crow form until you die.

This is purely cosmetic as you can cast and mount properly, but you are a crow.

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Still staying on crow form after landing.

**Comment by sifiuocz** [comment]
as of 30th of May this quest is still working improperly. After the flight is finished the player stays morphed. It now gives credit but even after you finish the quest it stays in your quest log.

**Comment by MummieSenpai** [comment]
as of 9th of June  you still stay morphed it gives you credit and its gone of you're quest log
you can still mount up and use your skills normaly 
http://i.imgur.com/TwRtQCF.jpg

**Comment by JunkyBulgaria** [comment]
should be fully working now, removed aura, morph and completing quest
