### ISSUE TITLE
Wolves Across the Border

### ISSUE THREAD

**Issue by svedizz** [FireFly-WoW/FireFly-IssueTracker#3]
**Description:**

The first thing I noticed is that Diseased Young Wolf in Northshire doesn't drop the Diseased Wolf Pelt you need to finish the quest.

**Current behaviour:**

I've killed over 30 of these wolves without a single drop.

**Expected behaviour:**

Well, they're supposed to drop to be able to complete the quest.

Quest: Wolves Across the Border

**Comment by masterfireyy** [comment]
Quest: Wolves Across the Border

**Comment by JunkyBulgaria** [comment]
As of http://wowwiki.wikia.com/wiki/Diseased_Young_Wolf : 
[FIX Applied] Patch 3.3.0 (08-Dec-2009): Replaces Young Wolf.
[FIX Applied] http://prntscr.com/evwcwa - They are spirit linked so they do attack back their attacker on groups.
[FIX Applied] Quest now requires 750 [8x] (Tough Wolf Meat) instead.

-- These were changed with the Lich King's infestation @ 3.3x

Will be available for test on next realm restart.

**Comment by svedizz** [comment]
I see that you have made it so they now drop Tough Wolf Meat. The problem now is that the quest is still asking you for Diseased Wolf Pelt and not Tough Wolf Meat. Is it even possible to use older quests in a more recent patch?

**Comment by JunkyBulgaria** [comment]
Have you tried deleteing cache?

**Comment by svedizz** [comment]
Yes, I did that. It works now, didn't know such a thing was client side. I noticed that there are still Diseased Timber Wolf mobs present as opposed to Timber Wolf that were present in pre-3.3.

**Comment by svedizz** [comment]
Also, are you going to change these things back when the server progresses in to 3.3?

**Comment by JunkyBulgaria** [comment]
Didn't knew about the timber ones, will swap them as well and yes, it will be reverted once firefly is at 3.3x as it will be blizzlike.

**Comment by svedizz** [comment]
Just a minor thing but I just noticed that the skull thingies that oozes from the diseased wolves are still there on the normal wolves. Just thought I'd mention that.

**Comment by svedizz** [comment]
![wowscrnshot_041317_140330](https://cloud.githubusercontent.com/assets/27390745/25003941/1713c208-2052-11e7-8a1c-11d54cc0b9dd.jpg)
I also noticed that the guy asks about the hunt of diseased young wolves. I know this is because of the patch 3.3 so I don't know if you guys care about such minor things, but still. I have some pictures from Vanilla so you can compare the texts with the post-3.3 quest.

**Comment by svedizz** [comment]
![wowscrnshot_041317_141459](https://cloud.githubusercontent.com/assets/27390745/25004276/d8372faa-2053-11e7-9d4c-13846035458e.png)
![wowscrnshot_041317_141507](https://cloud.githubusercontent.com/assets/27390745/25004286/e9d42a7e-2053-11e7-89df-eda1fa2d248b.png)

Pre-3.3.

![wowscrnshot_041317_140330](https://cloud.githubusercontent.com/assets/27390745/25004298/ffee60ae-2053-11e7-9234-64a4e1306556.jpg)
![wowscrnshot_041317_141525](https://cloud.githubusercontent.com/assets/27390745/25004300/0234a4ae-2054-11e7-97c3-c85ec6037a9b.jpg)

Post-3.3.

**Comment by JunkyBulgaria** [comment]
Updated quest texts, all wolves has proper look now as well.

**Comment by svedizz** [comment]
I see that you guys have put in Timber Wolf mobs now but they have the wrong textures. Basically they are just huge versions of the Young Wolf mob and both mobs still have the disease skull smoke thingy coming from them.

**Comment by svedizz** [comment]
This is the skull disease thing I'm talking about. 
![image](https://cloud.githubusercontent.com/assets/27390745/25021742/74b7f87a-2093-11e7-9deb-0c44edc03266.png)

**Comment by JunkyBulgaria** [comment]
The skull disease was aura, i removed it from both timber and young wolves. I'm not sure about their scale tho, i think i forgot to update it and i'm also not sure about the model as we don't have sniffs for 3.x<=

**Comment by JunkyBulgaria** [comment]
Scale normalized, everything should be working as intended now.

**Comment by masterfireyy** [comment]
we need test it again.

bugged stuff: 
- wolves are atacking in group
- skin of timber wolf are not correct + skull aura (3.3.3) content

http://wow.gamepedia.com/Timber_Wolf
http://wow.gamepedia.com/Diseased_Timber_Wolf

**Comment by JunkyBulgaria** [comment]
Sniffed some data from blizz, should be 1:1 with them now, sorry for it.

**Comment by svedizz** [comment]
I can confirm it is as it should be now :P Hopefully it won't be too much work resetting the changed you've made when you guys enter 3.3.

**Comment by JunkyBulgaria** [comment]
Nope, just few lines, it took so long because i didn't had any data related to the timber wolf. Thanks once again.

**Comment by svedizz** [comment]
Just thought I'd mention that the wolves still attack in groups which the are not supposed to, both Timber Wolf and Young Wolf.

**Comment by JunkyBulgaria** [comment]
Notes
They are socially linked to nearby Combat Mangy Wolves.
