### ISSUE TITLE
Felguard (warlock minion)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#30]
**Description:**

Broken damage.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

http://wowwiki.wikia.com/wiki/felguard_warlock_minion?oldid=2406889

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/BkHfq
url...
url...

**Comment by JunkyBulgaria** [comment]
Without glyph: http://prntscr.com/ewgl7w
With glyph: http://prntscr.com/ewgllj

works as intended.
