### ISSUE TITLE
[Quest] Wolfsbane Root

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#302]
**Description:**

http://www.wowhead.com/quest=12307/wolfsbane-root
The roots where scarce, but I did find 7 round an area. Couldn't find any more, so I guessed I should wait for the respawn. Over 20 min later, I come back and there are no more objects. 
My guess is that the object only spawns with the server restart, once all are taken, no more spawn, as there where no more ally characters on the area and ive still to encounter a horde.

**Screenshots:**
https://i.imgur.com/MTyQMv6.jpg

**Comment by frytik** [comment]
The respawn time is set to 5 minutes. Can you re-test please ?

**Comment by Stadics** [comment]
Tested on PTR. Not a single respawn after 15 minutes.

**Comment by JunkyBulgaria** [comment]
ptr fix applied

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Not working, no respawn after waiting 15min.

**Comment by frytik** [comment]
Should be fixed after new restart :1st_place_medal:
