### ISSUE TITLE
[Mob] Gordunni Warlock ability error

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#303]
**Description:**

The NPC Gordunni Warlock (https://vanilla-twinhead.twinstar.cz/?npc=5240#abilities) is spamming the ability "shrink" and is not casting shadow bolt.

**Current behaviour:**

Spamming Shrink.

**Expected behaviour:**

Should cast Shrink and then cast Shadow Bolts.

**Steps to reproduce the problem:**

1. Find a Gordunni Warlock
2. See him spamming "Shrink"

**Screenshots:**

**Comment by frytik** [comment]
Should be fixed on next restart.

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Working is intented. They no longer spam Shrink.
