### ISSUE TITLE
[Quest] we-have-the-power

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#305]
**Description:**

http://www.wowhead.com/quest=12197/we-have-the-power#comments

**Current behaviour:**

Kill the 2 guys, the items dont drop.

**Expected behavious**
https://www.youtube.com/watch?v=Cr1unGRhTmA&feature=youtu.be

**Screenshots:**
https://i.imgur.com/QeZ2cAL.png

**Comment by TW1NKLET** [comment]
> Drop rate does not appear to be 100 % for this quest. Instead it floats from 65-67 %.
```SQL
--
DELETE FROM `creature_loot_template` WHERE (Entry = 26409) AND (Item IN (36857));
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(26409, 36857, 0, 67, 1, 1, 0, 1, 1, NULL);

DELETE FROM `creature_loot_template` WHERE (Entry = 26410) AND (Item IN (36858));
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES
(26410, 36858, 0, 65, 1, 1, 0, 1, 1, NULL);
```

**Comment by TW1NKLET** [comment]
Does not make sense in my mind, but you'll have to ask developers about changing to 100 % instead of the suggested drop rates.

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Killed both mobs 10 times and let them .respawn. Had a 100% Dropchance on the questitems. - working.
