### ISSUE TITLE
[Quest] Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#306]
**Description:**

Ghost-o-plasm Round Up quest cannot be done cuz the item that you have to use to spawn the ghosts not working.

**Current behaviour:**

If i use the item Crate of Ghost Magnets it doesnt matter i'm on the correct place it does not spawn and cannot spawn ghosts to finish the quest

**Expected behaviour:**

Well it the item should spawn the ghosts or put some ghosts there to being able to finish the quest.

**Steps to reproduce the problem:**

1. Pick the quest
2. Go to location
3. Use the item and see nothing

**Screenshots:**

url...
url...
url...

**Comment by frytik** [comment]
Should be fixed on next restart.

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Not working, Error: "Requires The Dead Goliaths" - no matter where i try to place the item.

**Comment by JunkyBulgaria** [comment]
conditions

**Comment by frytik** [comment]
New update

**Comment by frytik** [comment]
Fix will be applied soon.
