### ISSUE TITLE
Gnomeregan [Rig Wars Quest]

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#307]
**Description:**

The item in the box after the last boss only lootable for 1 person.

**Current behaviour:**

You loot the item the box disappears and never spawns again or in horrible long time.

**Expected behaviour:**

The chest should be disappear or it should spawn quickly as possible.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by TW1NKLET** [comment]
> From what I can see the respawn time is 100 seconds / ≈ 1.5 minutes. 
```SQL
--
DELETE FROM `gameobject` WHERE (id = 142477);
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(32387, 142477, 90, 0, 0, 1, 1, -459.943, 634.926, -325.315, 2.6529, 0, 0, 0.970296, 0.241922, 300, 100, 1, 0);
```

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
After looting the chest it did not despawn at all. Destroyed the Questitem and i was able too loot the chest directly again. Should be working now.
