### ISSUE TITLE
[QUEST] Arikara 1K Needles

### ISSUE THREAD

**Issue by TheOddTruth** [FireFly-WoW/FireFly-IssueTracker#309]
**Description:**

Quest does not mark as complete when you have the required items... but only sometimes... Others have been able to complete it, it could be a fluke but worth investigating.

**Current behaviour:**

Explained above and below in screenshots

**Expected behaviour:**

Explained above and below in screenshots

**Steps to reproduce the problem:**

1. Get quest
2. "complete quest"
3. Get same result as screenshots below

**Screenshots:**

https://puu.sh/vSboh/205b5d9c9e.jpg
https://puu.sh/vSbsm/0565278119.jpg

**Comment by JunkyBulgaria** [comment]
did you "toss" the powder into the fire?

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Working as intented. (Use Item on Bonfire, Arikara spawns, loot Arika, Quest complete).
