### ISSUE TITLE
The Last Line Of Defense

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#31]
**Description:**
Fast spawn+low hp mobs=free xp.

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**
Unfortunately, the screenshot is not saved.
url...
url...

**Comment by frytik** [comment]
Need more info about times. I think, the spawn's are normal.

**Comment by frytik** [comment]
No XP on kill has been set for creatures.
