### ISSUE TITLE
Alot of Mobs on same Position spawned Zanga

### ISSUE THREAD

**Issue by sarlic1337** [FireFly-WoW/FireFly-IssueTracker#310]
**Description:**

Many many Mobs on the same Position in Zangarmashen at 44.67

If u get close it can cause lag. Saw it while making http://wowdata.getbuffed.com/quest/Zangarmarsh/-9803

I run in with Bubble and got 168 hits instant. So I guess 168 Mobs.

**Comment by Stadics** [comment]
Can't reproduce. Total of mobs in the area is 4.

**Comment by JunkyBulgaria** [comment]
couldn't reproduce as well

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Can't reproduce on PTR. Normal spawn.
