### ISSUE TITLE
Bug quest "free at last" in 1k needles

### ISSUE THREAD

**Issue by jfreky** [FireFly-WoW/FireFly-IssueTracker#311]
**Description:**
The npc is stuck
CHANGEME: Describe the issue here

**Current behaviour:**
When we arrive to the last bridge to get to the ground, the npc is stock under the bridge after fight one npc.
CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**
http://subefotos.com/ver/?8cce7b1b4e435711da9cbc1b9aa27232o.jpg
url...
url...

**Comment by frytik** [comment]
Probably bad calculation of Z position. Can you please re-test if it be done one more time ? If yes, i will set a unique flag for NPC. :100:

**Comment by frytik** [comment]
Any confirmation ?
