### ISSUE TITLE
[Quest] some-make-lemonade-some-make-liquor

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#312]
**Description:**

http://www.wowhead.com/quest=12634/some-make-lemonade-some-make-liquor

**Current behaviour:**
The game objects do not respawn, Managed to do most of the quest, but the orange only spawns in a single place, and it isnt there, checked 4 or 5 times in 6 hours.
**Expected behaviour:**

The world objects should just respawn...

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Working, fruits are respawning within 30-45secs.
