### ISSUE TITLE
Amphitheater of Anguish

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#313]
**Description:**

i cant pick up the quests of the amphitheater, probably marked for lvl 77 while they are lvl 75.

**Current behaviour:**
https://i.imgur.com/0PobrPj.jpg
no quests to accept

**Expected behaviour:**
http://www.wowhead.com/quest=12932/the-amphitheater-of-anguish-yggdras

**Comment by frytik** [comment]
In database it is set for 75 level.

**Comment by TW1NKLET** [comment]
And you have done the prerequisite? 
http://www.wowhead.com/quest=12974/the-champions-call

**Comment by Siderbas** [comment]
[PTR] Turned in the prequest with lvl72, could not take the followup between levels 72 and 80. (grey exclamation mark)

**Comment by Siderbas** [comment]
[PTR] Turned in the prequest with lvl72, was able to take the followup with lvl75.
