### ISSUE TITLE
Quest Map Markers bug!

### ISSUE THREAD

**Issue by ritwikthorat** [FireFly-WoW/FireFly-IssueTracker#314]
Quest Map Markers Vanish and it becomes difficult to track quests.

CHANGEME: if you use the map key twice the map markers for quests vanish and you cant figure out where the quests are.

**Current behaviour:**

CHANGEME: I think there is some problem with the quests being refreshed because completed quests are not being shown as completed and map markers once loaded stay the way they are till you log out and relog in.

Map markers should be seen and updated every time you use the map key or complete a quest partially or fully

to reproduce the problem simply 
1. get a bunch of quests on your character
2. press the map key to see where your quests are on map screen.
3. press escape key to get back to the main screen/play area.
4. (Optional) complete a quest fully/partially.
4. press the map key again.

frankly its becoming annoying and i think its one of those issues which you fix first.

**Comment by Siderbas** [comment]
Date: 2017-05-17 22:29:35
ID: 1
Error occured in: Global
Count: 1
Message: ..\FrameXML\QuestPOI.lua line 200:
   attempt to index local 'poiButton' (a nil value)
Debug:
   (tail call): ?
   [C]: ?
   ..\FrameXML\QuestPOI.lua:200: QuestPOI_HideButtons()
   ..\FrameXML\WorldMapFrame.lua:1633: WorldMapFrame_UpdateQuests()
   ..\FrameXML\WorldMapFrame.lua:1444: WorldMapFrame_DisplayQuests()
   ..\FrameXML\WorldMapFrame.lua:1521: WorldMapFrame_UpdateMap()
   ..\FrameXML\WorldMapFrame.lua:175:
      ..\FrameXML\WorldMapFrame.lua:168
   [C]: SetMapToCurrentZone()
   ..\FrameXML\WorldMapFrame.lua:142:
      ..\FrameXML\WorldMapFrame.lua:132
   [C]: ?
   [C]: Show()
   ..\FrameXML\UIParent.lua:1580: SetUIPanel()
   ..\FrameXML\UIParent.lua:1401: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1311:
      ..\FrameXML\UIParent.lua:1307
   [C]: SetAttribute()
   ..\FrameXML\UIParent.lua:1974: ShowUIPanel()
   ..\FrameXML\UIParent.lua:1958: ToggleFrame()
   [string "TOGGLEWORLDMAP"]:1:
      [string "TOGGLEWORLDMAP"]:1

Seems to be the related error

**Comment by JunkyBulgaria** [comment]
maybe packets are incorrectly sent same as stealth crash issue, i need to test it

**Comment by JunkyBulgaria** [comment]
added some issues as reference as they are linked to the packets as well

**Comment by philoudu16** [comment]
Only some quests are bugged, mainly escort quests... Those quests are the same which make Zygor spam some message about some goal not existing...

**Comment by ritwikthorat** [comment]
ok sorry for bothering you but i think the issue was from my side and not servers. i  just deleted the interface cache and WTF folders. turns out they were read only and the client has certain files which should have read/write properties and permissions instead of read only my bad. i guess its solved temporarily. im facing no problem at the moment.

**Comment by Siderbas** [comment]
This is still happening. And it seems to be somehow connected to opening the map while moving.

**Comment by balazskvr** [comment]
Some further, potentially useful info about this bug:
- not a general issue, some quests are affected, some are not
- mainly escort and explore quests are suspicious
- quests which break World Map seem to have **invalid objective POI**
- abandoning such quests and reloading UI fixes the issue (not reappearing until such quests are not obtained)

--> based on these info I would assume that some data is missing for such quests int the DB

**Comment by Tr4dY** [comment]
This is probably the most annoying bug and it's still live

**Comment by frytik** [comment]
Can you give guys example ID's of quests ?
