### ISSUE TITLE
Quest Ruthless Cunning

### ISSUE THREAD

**Issue by sarlic1337** [FireFly-WoW/FireFly-IssueTracker#315]
**Description:**

Use the Flag on Agents of Kil sorge doesn't work. It only gives the error "You can't do this now"

http://www.wowhead.com/quest=9927/ruthless-cunning

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
Ok so it's semi working. It works to place the Flag on "Kil'Sorrow Cultists" and "Kil'Sorrow Spellbinders" but it does not work on "Kil'Sorrow Deathsworn".

**Comment by JunkyBulgaria** [comment]
should work on all now

**Comment by bassuraaj** [comment]
Working On Live Realm.
