### ISSUE TITLE
Zul'Farrak Quest - Divino-matic Rod

### ISSUE THREAD

**Issue by Axxee** [FireFly-WoW/FireFly-IssueTracker#316]
**Description:**
The NPC named Seargent Bly it's not moving only casting battle stance so by saying that he cant also drop the quest item.

CHANGEME: Describe the issue here

**Current behaviour:**  Casting His battle stance again and again, doesnt move.

CHANGEME: Explain to us (if/how) it currently works. 

**Expected behaviour:** To kill him, but its impossible.

CHANGEME: Explain to us how the issue is supposed to work. 
We whould have to kill him to get the quest item.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Stadics** [comment]
Tested on PTR.
NPC behavior seems a bit wonky, but once the boss is dead I could talk to Bly, turn him hostile, and loot the rod.

http://i.imgur.com/xCzLHPa.jpg

**Comment by JunkyBulgaria** [comment]
there has been issues before for this encounter, needs re-testing as it worked before, nothing has changed

**Comment by Siderbas** [comment]
[QA] Testing on PTR now.

**Comment by Siderbas** [comment]
The Quest is completeable. The whole event isn't working as intented tho (no waves of mobs spawn, NPC dont go down the stair ect.). See Video: https://youtu.be/9enXDv7w7mE

**Comment by Axxee** [comment]
Happy to know everything is gonna be ok :D

**Comment by Siderbas** [comment]
#13 this was already working as intended in Beta as it seems.

**Comment by JunkyBulgaria** [comment]
tested 3 times, encounter worked fine for me, needs confirmation from QA team
