### ISSUE TITLE
[Quest] weapons-of-destruction

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#317]
**Description:**
Same bug as with many other quest. Game objects are not there.

http://www.wowhead.com/quest=12660/weapons-of-destruction

**Current behaviour:**

Game objects dont respawn

**Comment by JunkyBulgaria** [comment]
PTR fixed.

**Comment by Siderbas** [comment]
[PTR] No respawn after 10min.

**Comment by bassuraaj** [comment]
Working on Live Realm.
