### ISSUE TITLE
[Dungeon] Trial of the Champion

### ISSUE THREAD

**Issue by LucasHell** [FireFly-WoW/FireFly-IssueTracker#318]
**Description:**

The dungeon Trial of the Champion should be closed until patch 3.2 when the Argent tournament opened.

**Current behaviour:**

It is possible to enter and start the first encounter, although no mounts were available.

**Expected behaviour:**

It should not be possible to enter the dungeon or at least impossible to start the encounters.

**Steps to reproduce the problem:**

1. Enter the dungeon
2. Talk to Jaeren Sunsworn

**Screenshots:**

http://imgur.com/a/eHm5x

**Comment by JunkyBulgaria** [comment]
it is fixed on ptr
