### ISSUE TITLE
Azjol Nerub(hc)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#32]
**Description:**
Malfunctioning Anub'arak

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Anub%27arak_(tactics)

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**
http://imgur.com/a/zbNhR
url...
url...

**Comment by JunkyBulgaria** [comment]
Works as intended, closing this issue as it's invalid report. If you have any questions/additions to this issue please re-open/comment on this issue.
http://prntscr.com/ews7hv

**Comment by Fearevius** [comment]
The problem is not in the boss's murder, but in the absence of a protective barrier.

**Comment by JunkyBulgaria** [comment]
it was there for me

**Comment by Fearevius** [comment]
Maybe I did not have a speed modifier.
