### ISSUE TITLE
private hendel

### ISSUE THREAD

**Issue by erutharos** [FireFly-WoW/FireFly-IssueTracker#320]
**Description:**

This NPC keeps following me. he cant be defeated and i cant even get desconected or flay away

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

[IMG]http://i63.tinypic.com/mtumh5.jpg[/IMG]

http://es.tinypic.com/r/mtumh5/9
url...
url...

**Comment by Demmye** [comment]
Couldn't reproduce, Private Hendel acts just like any other NPC and can be killed or reseted by going far enough from his initial position.
