### ISSUE TITLE
Jaedaner Mobs in Felwood

### ISSUE THREAD

**Issue by Axxee** [FireFly-WoW/FireFly-IssueTracker#321]
**Description:**

Jaedaner Cultiest/Adept Teleportation issue.

**Current behaviour:**

Instead of running as they should, they have the tendancy to teleport where he usually would run when attacked, he would teleport.

**Expected behaviour:**

He should run ( not so sure if actualy run but whatever u guys know the best ) and then cast. NOT teleporting itself.

**Steps to reproduce the problem:**

1. Attack him (@everybody im a melee fighter idk how the behavior is for rangers)

**Comment by sifiuocz** [comment]
they are not teleporting, just using their blink ability. This behaviour is correct.

**Comment by Axxee** [comment]
I see, sorry :D
