### ISSUE TITLE
[Dungeon][Loot] Ingvar the Plunderer

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#327]
Still no loot.

#294 

![wowscrnshot_052017_160922](https://cloud.githubusercontent.com/assets/24325735/26276383/e8736970-3d76-11e7-991c-1b02669e3cbd.jpg)
![wowscrnshot_052017_160924](https://cloud.githubusercontent.com/assets/24325735/26276384/e9ffd954-3d76-11e7-85cf-a3bd1ab816aa.jpg)

**Comment by philoudu16** [comment]
Did he do his resurrection thing?

**Comment by Soockee** [comment]
He did enter p2.

**Comment by Soockee** [comment]
Fight was working fine. He just didn't drop anything.

**Comment by Demmye** [comment]
It now drops the loot on PTR.

**Comment by JunkyBulgaria** [comment]
live realm fix applied
