### ISSUE TITLE
[Dungeon][Bossmechanic][Utgarde Pinnacle] Svala Sorrowgrave

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#328]
Current Behavior:

 Ability: [Ritual of the Sword]
Doens't work properly.

She flys into the air but **doesn't** spawn the 3 shades which have to be kiled before letting the sacrifices free.
She also evades in the air which causes a liferegeneration.

How it should work:
https://www.youtube.com/watch?v=9tKsO6U6fVI

**Comment by JunkyBulgaria** [comment]
issue 1 is fine, it's from the pre-3.3.5 nerf, it is harder now (working as intended)
issue 2 should be fixed now

**Comment by Soockee** [comment]
By bad it. i mean she doenst do the first issue changed. Did it right now and she still doens't do the sacrifice thing

**Comment by JunkyBulgaria** [comment]
fix will be applied on ptr soon

**Comment by Demmye** [comment]
The encounter in PTR seems completely undoable, since when the boss'es hp hits 20% it teleports few yards above the ground, spawns the shades for a milisecond and then despawns and respawns momentarily.

**Comment by Siderbas** [comment]
There is no fix applied yet on the PTR so i will keep it labeled with "Needs Testing"

**Comment by JunkyBulgaria** [comment]
encounter partially works so that would suit it better (:

**Comment by Siderbas** [comment]
Oh yeah, thought Demmye tested before you applied anything to the PTR yet :D

**Comment by JunkyBulgaria** [comment]
evade issue completely fixed, about the 2nd it will work as well now
