### ISSUE TITLE
Raid entry level requirement

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#329]
**Description:**

It seems the level restrictions for entering dungeons/raids are not implemented correctly

**Current behaviour:**

You can enter certain dungeons/raids (only the ones i've tested at least) with a lower level than the minimum requirement set by Blizzard.

**Expected behaviour:**

Each dungeon/raid has it's own minimum level requirement to enter. Like the TBC raids, all require lvl 70 except for CoT and Kara which require a minimum of 68, or the WoTLK heroic dungeons and raids all require minumum of lvl 80. You can enter VoA for example at lvl 56.

Source: http://wowwiki.wikia.com/wiki/Instances_by_level

**Steps to reproduce the problem:**

1. Step 1
Make a level 1 toon and try to enter a Wotlk raid/heroic dungeon.
2. Step 2
3. Step 3

**Screenshots:**

![wowscrnshot_052017_195642](https://cloud.githubusercontent.com/assets/5167458/26278532/3a557804-3da5-11e7-9aa2-844c99ebc249.jpg)

**Comment by l1z1xmd** [comment]
Confirmed, as a level 57 I was able to enter UP heroic, and OS raid without even being in a raid group.

![wowscrnshot_052017_222130](https://cloud.githubusercontent.com/assets/28388741/26278751/bd4a6b7a-3daa-11e7-832e-9c2e31897180.jpg)
![wowscrnshot_052017_220347](https://cloud.githubusercontent.com/assets/28388741/26278752/bd505e9a-3daa-11e7-96a2-9408446c1a1e.jpg)

**Comment by JunkyBulgaria** [comment]
Fixed
