### ISSUE TITLE
[Raid Boss] Vesperon - The Obsidian Sanctum

### ISSUE THREAD

**Issue by davidmurcia** [FireFly-WoW/FireFly-IssueTracker#330]
**Description:**

The boss fight is completely broken. Being able to down it is up to luck, as damages are random.
**Current behaviour:**

The damage inside the portal is over the top. You cant survive inside.
The void zone explosions are completely unpredictable. Will hit you randomly, no matter if you are inside or not, or the distance from the blue circle.

**Expected behaviour:**

https://www.youtube.com/watch?v=xtDtR_gXcOI

**Comment by JunkyBulgaria** [comment]
fix will be applied on ptr soon

**Comment by JunkyBulgaria** [comment]
https://www.youtube.com/watch?v=So-vEjErvCg

all i see is a mob into the void zone /inside portal/, hits for ~400dmg/s = corrected
about the void zone it needs to be tested with 3+ players
