### ISSUE TITLE
Quest bug: WANTED Baron Vardus

### ISSUE THREAD

**Issue by jfreky** [FireFly-WoW/FireFly-IssueTracker#331]
**Description:**
The Baron Bardus, will be in the inn of Strahnbrad in Alterac mountains, but isn´t in there
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment]
The location of this mob is not always in the Inn of Strahnbrad in Alterac. Check the other possible spawn locations. (http://www.wowhead.com/npc=2306/baron-vardus#comments). - Spawn confirmed on PTR.
