### ISSUE TITLE
[Warlock] Felhunter missing spell.

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#332]
**Description:**

Player report about felhunters missing their starting ability "
Shadow Bite"

**Current behaviour:**

No Shadow Bite on Felhunters.

**Expected behaviour:**

Shadow Bite should be available with lvl30 without the need of training.

**Comment by JunkyBulgaria** [comment]
fix will be applied on ptr soon

**Comment by JunkyBulgaria** [comment]
needs confirmation if data is valid (e.g without training on 3.0x)
