### ISSUE TITLE
[Quest] The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by LucasHell** [FireFly-WoW/FireFly-IssueTracker#333]
**Description:**

The waves spawn but mobs "fly" up in the ceiling and despawn.

**Current behaviour:**

The waves spawn but "fly" up in the ceiling and despawn. My pet also had problems in the room and would get stuck constantly.

**Expected behaviour:**

The waves of mobs are supposed to spawn and then attack Nergeld.

**Steps to reproduce the problem:**

1. Enter Nergeld

**Screenshots:**

http://imgur.com/a/8GKs9

**Comment by bassuraaj** [comment]
Working on Live Realm.
