### ISSUE TITLE
Noggenfogger Elixir

### ISSUE THREAD

**Issue by firefly-bvlgari** [FireFly-WoW/FireFly-IssueTracker#334]
**Description:**

One of the three buff's don't working correctly. ("You've stopped breathing...")

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

if a player use the Item "Noggenfogger Elixir", will be get 1 of 3 possible buff's random.

Possible Buff's:
1. "You've stopped breathing..." (Undead)
spell-details: http://www.wowhead.com/spell=16591/noggenfogger-elixir
**working NOT correct**

2."You feel light..."
spell-details: http://www.wowhead.com/spell=16593/noggenfogger-elixir
**working correct**

3."You feel smaller..."
spell-details: http://www.wowhead.com/spell=16595/noggenfogger-elixir
**working correct**

**Steps to reproduce the problem:**

1. Step : use the Item "Noggenfogger Elixir"
2. Step : use it so often until get the buff "You stopped breathing..." 
3. Step : use a random mount of your choice... 

Bug: i can't mount ... mesage: "EureGestalt ist verwandelt [german]" (Your form has been transformed)
but with the effects of noggenfogger you can ride at any time!

**Screenshots:**

Screens from the buff's are avaible on "spell-deatails" link.

**Comment by Siderbas** [comment]
You weren't able to mount with the "You've stopped breathing..." (Undead)" this was patched way later (5.0.3+)

**Comment by firefly-bvlgari** [comment]
Okay (O.o) I didn't know that to be changed to bc ... and again changed in mop ...
