### ISSUE TITLE
Game crash in Stormwind

### ISSUE THREAD

**Issue by l1z1xmd** [FireFly-WoW/FireFly-IssueTracker#336]
**Description:**

Game suddenly crashed in Stormwind, giving me a critical error.

**Current behaviour:**

Game suddenly crashed in Stormwind, giving me a critical error, and closing the game client, while I was on docks near pathway to Northrend dock

**Expected behaviour:**
Game should not crash for whatever reason.

**Steps to reproduce the problem:**

1. Go in Stormwind, at the docks.
2. Walk towards Northrend dock, and hope for the worst.

**Screenshots:**

![crash](https://cloud.githubusercontent.com/assets/28388741/26283990/5c3ab480-3e3a-11e7-9447-c3a870336ecb.jpg)

**Comment by JunkyBulgaria** [comment]
can you paste the error log in pastebin.com and share the link here please?

**Comment by masterfireyy** [comment]
I couldn't reproduce the error. Walked for 20 minutes inside stormwind harbor and to the Northrend Docks. Nothing happened. An error log would be awesome.

**Comment by l1z1xmd** [comment]
https://pastebin.com/2BT0h61X

Thanks for the reply

**Comment by JunkyBulgaria** [comment]
I went to your coordinates, my game didn't crashed (-8372.42,1224.43,5.23049)

**Comment by l1z1xmd** [comment]
Ok, maybe I was unfortunate
