### ISSUE TITLE
Obsidian Sanctum

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#34]
**Description:**
Portals&Sartharion

CHANGEME: Describe the issue here
Tenebron - I could not enter the portal. (but maybe need more ppl in raid)
Sartharion - See screenshot.
**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Tenebron
http://wowwiki.wikia.com/wiki/Sartharion

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/GVDqQ
http://imgur.com/a/rDisW
http://imgur.com/a/sgnyJ

**Comment by JunkyBulgaria** [comment]
This is not how you test a raid, invalid report.
