### ISSUE TITLE
Empty Spot

### ISSUE THREAD

**Issue by sting1080** [FireFly-WoW/FireFly-IssueTracker#340]
**Description:**

When killing an enemy after you loot it, the mob is still "lootable" but once you click it again it says Empty Spot. This will not go away not allowing you to interact with the body example skin it.

**Current behaviour:**

Works on all mobs in all zones to my knowledge. 

**Expected behaviour:**

Explain to us how the issue is supposed to work.

Supposed to be able to interact with mob ie: skin or mine

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
![wowscrnshot_052117_133716](https://cloud.githubusercontent.com/assets/28846981/26287294/3f93a076-3e53-11e7-8728-6362aad05270.jpg)

url...
url...

**Comment by Siderbas** [comment]
Could not reproduce this. Anyone else able to reproduce?

**Comment by sting1080** [comment]
I was also in a group if that helps tho i don't think my buddy was close to me.

**Comment by JunkyBulgaria** [comment]
try to disable addons

**Comment by sting1080** [comment]
I tried and no luck. I was doing an run through stocks last night in a group and that seems to be when its happening most.

**Comment by Demmye** [comment]
Unable to reproduce, I suspect your interface might be at fault.
