### ISSUE TITLE
[Quest chain] Betrayal

### ISSUE THREAD

**Issue by Hotshot333** [FireFly-WoW/FireFly-IssueTracker#342]
**Description:**

Cannot start the chain quest

**Current behaviour:**

The starting quest for this chain is given by a quest starting item called Unliving Choker, which should have a 100% drop from Withered Troll that are roaming around the Ebon Watch camp. I've killed over 100 trolls, item did not drop. http://wowwiki.wikia.com/wiki/Unliving_Choker_(1)

**Expected behaviour:**

The item should drop. Players are usually introduced to it while doing the quest Kickin' Nass and Takin' Manes. http://www.wowhead.com/quest=12630/kickin-nass-and-takin-manes

**Steps to reproduce the problem:**

1. Step 1
Kill withered trolls around ebon watch camp
2. Step 2
Item will not drop.

Worth mentioning that some players did have the item drop a few days ago.

**Screenshots:**

**Comment by Erivanz** [comment]
can confirm

**Comment by JunkyBulgaria** [comment]
fix will be applied on ptr soon

**Comment by JunkyBulgaria** [comment]
http://www.wowhead.com/item=38660/unliving-choker has 100% droprate from http://www.wowhead.com/npc=28519/withered-troll now.
Currently on PTR, Live within 24h.

**Comment by Demmye** [comment]
It does drop from Withered Trolls now on PTR, but according to various sources, the drop rate should be 8-11%.

**Comment by JunkyBulgaria** [comment]
set to 11% then

**Comment by Tr4dY** [comment]
I've been bashing trolls for 30% xp and it's not dropping..
