### ISSUE TITLE
Dungeon Cyanigosa

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#343]
**Cyanigosa last Boss of Violet Hold (Heroic):**

Boss dissapears after somewhat 20 seconds

Boss disappears 

Boss shouldnt  disappear 

1. Attack the Boss
2. Wait until she resets
3. ???

**Comment by JunkyBulgaria** [comment]
should be fixed with the evade upate

**Comment by Demmye** [comment]
Doesn't work on PTR. What I have noticed though, she despawns when she casts [Arcane Vacuum](http://www.wowhead.com/spell=58694/arcane-vacuum) which is most likely the cause of the problem.

**Comment by JunkyBulgaria** [comment]
yeah, it was because of this spell, great job!

**Comment by Hardcore-FireFly** [comment]
Did VH hrc on live realm a week ago or two. She was working fine.
