### ISSUE TITLE
Killing Spree

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#344]
**Killing Spree:**

Getting kicked by the anticheat engine using Killing spree

Dont get kicked for using a regular talent.

1. Use Killing spree
2. Use Killing spree
etc.

Ask any of the combat rogues on the server. Pretty much most of the time someone gets kicked its a rogue.

**Comment by Demmye** [comment]
Anti-Cheat engine does not kick a player for using Killing Spree anymore in PTR.
