### ISSUE TITLE
Oculus Mage-Lord Urom

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#345]
**Mage-Lord Urom:**

Boss resets when using his ability Teleport which teleports him towards the middle of the instance.

**Boss doesnt reset and instead casts his arcane explosion:**

Steps to reproduce the problem

1. Start the fight with Mage-Lord Urom
2. Wait until he casts his Teleport
3. ???

**Comment by JunkyBulgaria** [comment]
closed as #105 contains more issues related to this encounter
