### ISSUE TITLE
The Amphitheater of Anguish

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#346]
**Description:**

Players are not able to start the follow up quests of "A Champions Call!" after turning it in and beeing lvl75+.

This issue seems to be fixed on the PTR and should be applied with the next update.

**Comment by JunkyBulgaria** [comment]
fixed on live

**Comment by JunkyBulgaria** [comment]
Fixed on PTR, will be available tomorrow on live realm.

**Comment by Demmye** [comment]
Confirmed, all the quests of the quest chain are available at level 75 on PTR.

**Comment by Siderbas** [comment]
Reopened to due ingame ticket 473.

**Comment by Siderbas** [comment]
#313 #463

**Comment by philoudu16** [comment]
The quest was not available for me on PTR.
