### ISSUE TITLE
Contagion of Rot

### ISSUE THREAD

**Issue by tuppii** [FireFly-WoW/FireFly-IssueTracker#347]
_**Description:**_
Contagion of Rot (ID7103) can stack to multiple debuffs per player.
_CHANGEME: Describe the issue here_
Contagion of Rot (ID7103) can stack to multiple debuffs per player.

Contagion of Rot is a debuff affected by mobs in Ruins of Aboraz, in Stranglethorn Vale.

_**Current behaviour:**_
It stacks to an infinite amount of debuffs.

_**Expected behaviour:**_
Only one disease per player should be allowed.

_**Steps to reproduce the problem:**_

1. Go to any mob in the descripted ruins.
2. Get hit.
3. Profit.

_**Screenshots:**_
http://imgur.com/a/wBaBH

**Comment by JunkyBulgaria** [comment]
#326
