### ISSUE TITLE
[Naxxramas] Maexxna

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#348]
After wiping at her we tried to walk back to her cave. The wall which appears after engaging should go away after wiping.

**Comment by JunkyBulgaria** [comment]
was she in combat?

**Comment by Soockee** [comment]
Everyone died in the fight. shaman did use ahnk afterwards. he attacked her again -> he died again -> still not open

**Comment by JunkyBulgaria** [comment]
alright, thank you

**Comment by JunkyBulgaria** [comment]
fix applied on PTR

**Comment by Demmye** [comment]
The wall does not appear at all on PTR anymore.

**Comment by Siderbas** [comment]
so if you start the fight there is no wall coming? that could potentially be abused with resetts?!

**Comment by Demmye** [comment]
At this state, it's not a gamebreaker, just that when she is brought out of the room, she dispawns and respawns few seconds after, so players can only avoid wiping completely and survive if things go south.
