### ISSUE TITLE
[Doublicate NPCs] Honor Hold

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#350]
**Description:**
[PTR and Live]

The NPCs "Hargen Bronzewing" (Entry: 53100) and "Grund Bronzewing" (Entry: 29610) are spawned twice in Honor Hold.
![wowscrnshot_052317_103206](https://cloud.githubusercontent.com/assets/1843515/26345936/cde87552-3fa4-11e7-8ea4-07829e4298dd.jpg)

**Comment by Demmye** [comment]
Everything seems good now in PTR.
