### ISSUE TITLE
Blackfathom Deeps missing mob

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#351]
In the instance Lorgus Jett is missing

The mob is just nowhere the instance i tried target macro etc

Well it should be inside it has some varies locations where he could be it.

Well it doesnt matter that he is on varius location or not just being inside the instance

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by thestranger064** [comment]
Confirming this checked all his spawn points. 
Quest: http://db.vanillagaming.org/?quest=6565

**Comment by Demmye** [comment]
Lorgus Jett is in the instance, but dead by default for some reason. The most interesting thing about this bug is that the adds are not agressive to him, so lord knows why he's dead.
