### ISSUE TITLE
Blackfathom Deep quest giver mob problems 

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#352]
Argent Guard Thaelrid mob is hostile (as horde dont know about alliance)

You cannot speak to the mob and does not gives a quest

Well should able to speak to him as horde and gives a quest.

It should be be Argent Dawn mob so everybody should be ablo to speak to him, does give a quest both to alliance and horde too

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by thestranger064** [comment]
Confirming this.

Quest: http://db.vanillagaming.org/?quest=6561

**Comment by Demmye** [comment]
Confirmed, the Argent Guard Thaelrid is hostile to everyone (even in GM mode).
