### ISSUE TITLE
Overall dungeon problem (classic)

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#353]
Now that've been in many classic dungeons and if there is a quest item which is an object that can be looted they never respawn. Some examples 
The Book of Ur in Shadowfang Keep, 
Compendium of the Fallen in Scarlat Monastery Library (Here u can also loot only 1 Scarlat Key)
Fathom Core in Blackfathom Deeps
Even after 10 minutes they did not respawned.

Experiencing this i think it totally the same in every dungeon these is 100% already.

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
i'll fix these but we would need a list with these gameobjects

**Comment by thestranger064** [comment]
I can confirm here again.
Objects seem to be lootable by 1 person at a time and waiting does not help it respawn.

**Comment by Nagykiraly** [comment]
Those 4 i wrote should be fixed then but if it will be more i know i will add those too

**Comment by Stadics** [comment]
Tested on PTR. The above listed quest objects respawn instantly. Tested another dungeon quest object 91138 for quest 1654, didn't respawn (not sure if it should).

**Comment by Nagykiraly** [comment]
It should all quest objects in the instances should just not even despawn to everybody could loot it. But if it spawn instantly back its also perfect solution.

**Comment by JunkyBulgaria** [comment]
needs re-testing as the current issue is already fixed, if there are new ones please make new issues for them
