### ISSUE TITLE
Fishing Daily Dalaran

### ISSUE THREAD

**Issue by Erivanz** [FireFly-WoW/FireFly-IssueTracker#354]
**Fishing Daily**

So far none of the Fishing Dailys worked

**Questmobs dont drop: i.e. fishing for more then 10 minutes for questmob in wintergrasp or sholazar:**

**It should be fairly easy to get: something like 2 mins max:**

Try fishing for any Fishing Daily

1.Go Fishing
2. Fish even more
3. Get frustrated

**Comment by Demmye** [comment]
All the Dalaran fishing dailies work perfectly fine.

**Comment by Erivanz** [comment]
I dont know how it works for you but on horde side its definitly not working for me and some other guys.

**Comment by Siderbas** [comment]
Did you test it after todays update?

**Comment by Erivanz** [comment]
yes. tried Disarmed! for 10+ minutes. nothing dropped.

**Comment by Demmye** [comment]
I tested it on PTR, horde side 5 hours ago, and I am 100% sure it's working as it should.

**Comment by Erivanz** [comment]
i dont know about ptr.

**Comment by Demmye** [comment]
May I ask where are you fishing for the quest "Disarmed!"?

**Comment by Erivanz** [comment]
In front of Violet Hold.

**Comment by Siderbas** [comment]
Maybe a problem with Patches as: "Patch 3.3.3 (2010-03-23): The "Monsterbelly Appetite" daily fishing quest has changed so it now takes place outside the Violet Hold in Dalaran. The quest still requires a [Severed Arm] and has been renamed to "Disarmed!"" A Dev will take a look at it.

**Comment by Siderbas** [comment]
what about other fishing dailys?

**Comment by Erivanz** [comment]
Tried the one in dalaran sewers this morning too.

**Comment by Demmye** [comment]
All 5 dalaran fishing dailies work on PTR, so it only needs to be mirrored to live realm.

**Comment by Erivanz** [comment]
So far none worked for me. Maybe im doing something wrong or its different on Ptr but when i did it on other servers it always worked for me.

**Comment by JunkyBulgaria** [comment]
it could be from our progressive system, i will investigate it on live realm, thank you

**Comment by sarlic1337** [comment]
http://www.wowhead.com/quest=13834/dangerously-delicious

Is not working on Liverealm. Tested in 2 different Locations in Wintergrasp. ~100 Catches no Questfish.

**Comment by thestranger064** [comment]
PTR and Live realm are two different servers. Please understand that what works on PTR is not the same as LIVE realm

Thank you.

**Comment by sarlic1337** [comment]
So when will the fix be applied?

**Comment by JunkyBulgaria** [comment]
live realm fix applied

**Comment by Erivanz** [comment]
I tried Blood is Thicker and Junk in the Sewers. Junk in the Sewers didnt drop anything and Blood is thicker messaged me interupted all the time without giving any loot but somehow the pool disappeared after a few of this messages. Fishing skill 437. Maybe the required fishing lvl to actually get the quest mobs is to high?

**Comment by sarlic1337** [comment]
Can confirm Blood is Thicker not working as Erivanz said, it only Interrupts without loot. Fishing Skill shouldn't be a problem as far as you are over 400.

**Comment by sarlic1337** [comment]
Can confirm Dangerous Delicious is also not working.

**Comment by JunkyBulgaria** [comment]
issue is that the quest items/dailies has been added in higher patch, i have to remove the quest items from the list so they can drop as intended

**Comment by sarlic1337** [comment]
push

**Comment by sarlic1337** [comment]
Is someone working on this?

**Comment by sarlic1337** [comment]
250 Catches no Ghostfish so far. Should be there already, tried 2 different positions

**Comment by JunkyBulgaria** [comment]
fix is not applied on live yet

**Comment by sarlic1337** [comment]
Is it now? I lack alot of communication
The quest where u have to fish in front of Violet Hold, is working, I can confirm that, seems like there was a patch
