### ISSUE TITLE
Gnarlpine Vengeance

### ISSUE THREAD

**Issue by Kakashi93** [FireFly-WoW/FireFly-IssueTracker#355]
**Description:**

CHANGEME: The Gnarlpine NPC's in teldrassil use to often her Vengeance buff, feeling all the time.

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Demmye** [comment]
It is bugged, specific Gnarlpine NPCs have 66% uptime of Gnarlpine Vengeance, but I could not find any information on this buff and how it should be and looking at retail videos, I didn't even see this spell used once(out of ~50 encounters with Gnarlpines).

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/fnt9b4
