### ISSUE TITLE
Ruining game experience.

### ISSUE THREAD

**Issue by hairysiv** [FireFly-WoW/FireFly-IssueTracker#359]
**Description:**

CHANGEME: Describe the issue here
When the player engages a mob equipped with a bow or gun - the mob runs away from the player, allowing it to kite the player. This also happens when spell casters are interrupted. Exceedingly game breaking and removes the fun in leveling.

**Current behaviour:**
When the player engages a mob equipped with a bow or gun - the mob runs away from the player, allowing it to kite the player. This also happens when spell casters are interrupted.

If the player runs away - the mob will follow about 10 yards away to keep shooting/spell cast.
If the player runs towards the mob - it will run away to keep a max distance to allow the mob to shoot.

CHANGEME: Explain to us (if/how) it currently works.
Mobs equipped with bows or guns or spell casters kite players until they die - especially melee.
The mobs probably have a *minimum range* setting - which is set too high.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
When a player comes up to a mob that shoots/ spell casts, the mob should continue to shoot (without putting in a distance) or start doing melee damage when the player is too close for the mob to allow it to shoot.

**Steps to reproduce the problem:**

1. Step 1
Change shooting distance to 0-30 yards.
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
This has been fixed already, will be applied on live realm within 2-3 hours, thank you for your report.
