### ISSUE TITLE
Vote Issue

### ISSUE THREAD

**Issue by Noob1e** [FireFly-WoW/FireFly-IssueTracker#36]
**Description:**

You can have VP just by clicking on "VOTE" buttons.

**Expected behaviour:**

You should complete all steps in those vote websites to vote the server and have/add VP to your account. At the moment, vote points are added but you are not actually voting the server in these websites.

P.S.: It would be good if you could write the remaining time until the next vote.

**Steps to reproduce the problem:**

1. Go to Vote panel (https://firefly.to/vote.php),
2. Click VOTE button,
3. Close the vote website,
4. Go back to main page (https://firefly.to/index.php) and check your VP.

**Screenshots:**

http://imgur.com/a/d0fsp

**Comment by masterfireyy** [comment]
Thank you for the report.
We wil solve that problem asap.
