### ISSUE TITLE
[Ahn'kahet: The Old Kingdom] [Boss] Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#362]
**Description:**

Unable to engage boss.  Upon approaching, waves of adds would continuously re-spawn as the boss remained untouchable.  Worth noting - we attempted this on heroic mode.

**Current behaviour:**

Waves of adds continue re-spawning immediately upon death, while the boss remains inactive.

**Expected behaviour:**

The boss fight should begin automatically after killing the groups of adds surrounding Jedoga Shadowseeker.

**Steps to reproduce the problem:**

Kill the groups of adds and try to engage Jedoga.

**Comment by Stadics** [comment]
Tested on PTR. Can't reproduce the report. Could be that this issue occurred prior to the update.

Tried it multiple times and ended up with two scenarios:
1: Upon clearing the first wave of initiates, the boss descends and becomes targetable as intended. If upon descend the boss is immediately aggroed, new initiates spawn and become immune and untargetable as intended, and the boss fight continues with its normal phases.

2: Upon clearing the first wave of initiates, the boss descends and becomes targetable as intended. However, if the boss is not immediately aggroed, initiates still immediately spawn and and aggro players moving into their proximity without the boss being engaged. The boss does however remain targetable.

**Comment by Ikaros84** [comment]
This problem did occur prior to the update.  We ran this again today and we were able to engage boss.

**Comment by davidmurcia** [comment]
It is still happening. Tested today with a group.

**Comment by Ikaros84** [comment]
Yeah just ran this, and it is happening again

**Comment by frytik** [comment]
Found an problem in script. Testing it guys.

**Comment by Hardcore-FireFly** [comment]
Working fine on PTR.
