### ISSUE TITLE
[Quest] Boiling Blood

### ISSUE THREAD

**Issue by totaemoeggerli** [FireFly-WoW/FireFly-IssueTracker#363]
**Description:**

Drop rate of "Bleeding Hollow Blood" for the quest "Boiling Blood" in Hellfire Peninsula too low.

**Current behaviour:**

Only 6 "Bleeding Hollow Blood"  droped while doing all the other Zeth'Gor quests (Worgmaster, Must burn, Eye, Elite mob). Probably killed 40 mobs.

**Expected behaviour:**

Drop rate from "Bleeding Hollow Blood" should be at least twice as high.

**Steps to reproduce the problem:**

Adjuste drop rate of "Bleeding Hollow Blood".

**Comment by Siderbas** [comment]
6 drops out of ~40 kills (probably less, humans tend to exaggerate)  seems correct if compared to http://www.wowhead.com/item=30425/bleeding-hollow-blood  which states around 20% chance. 6/40=15%.

**Comment by Demmye** [comment]
Drop rate is perfectly fine.
