### ISSUE TITLE
[Get the Key] missing quest item

### ISSUE THREAD

**Issue by iMerdjaoui** [FireFly-WoW/FireFly-IssueTracker#364]
Quest name :  [Get the Key]
ID : 12949
NPC to kill to get the key : Intsructor Hroegar
NPC ID : 29915
Tried killing him 3 times, he doesn't drop any loot.

**Comment by Erivanz** [comment]
can confirm.

**Comment by Demmye** [comment]
Confirmed, the NPC doesn't have any loot table.

**Comment by sarlic1337** [comment]
Can still confirm. Not dropping the Item, would set the Priority Medium since there are alot of Followquests depending on this one.

**Comment by sarlic1337** [comment]
Can someone pls fix this? Want to to the Quests and its really not much work, it's actual content so shouldn't be priority Low imo

**Comment by thestranger064** [comment]
Can confirm, killed twice and nothing. As he said, alot of follow ups after this.
http://imgur.com/a/NqGtW

**Comment by frytik** [comment]
I made a fix, should be applied soon.

**Comment by sarlic1337** [comment]
Tested on live Realm. 3 Kills no Questitem.

**Comment by JunkyBulgaria** [comment]
fix is not applied on live yet

**Comment by warrgazm** [comment]
still broken can confirm.

**Comment by warrgazm** [comment]
hopefully gets fixed in the Big update whenever that is applyed
