### ISSUE TITLE
[Ticket] Quest: It's all fun and games

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#366]
[It's All Fun and Games] I keep trying to use the item from different angles & range, always tells me it's out of range.

**Comment by philoudu16** [comment]
Imo, this should have a slightly higher priority than the other tickets, since if the quest bugs for you, it blocks access to about a third of the quests in Icecrown, and the Knights of the Ebon Blade quartermaster.

**Comment by Demmye** [comment]
Couldn't reproduce on PTR, seems to be working here.

**Comment by Siderbas** [comment]
Needs testing on live Realm.

**Comment by sarlic1337** [comment]
I made this Quest yesterday. You can't see the Eye before u really fly high to him, I first thought its bugged too. If u get in Range it starts to attack you (what makes u dismount and probably is deadly). U can also use the Item on the Eye do DMG it.

**Comment by Siderbas** [comment]
thank you for the info @sarlic1337. - closed
