### ISSUE TITLE
[Ticket] Problems with "Charge"

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#367]
"Charge on a monster when on a bridge at DarkCloud Pinnacle (thousands needles) is completly broken, made me fall off bridge and then fly back to bridge."

**Comment by Siderbas** [comment]
I also found out that it's currently not possible to charge a monster when beeing mid-air after a jump from higher ground.

**Comment by Demmye** [comment]
Both confirmed, charge seems bugged on certain structures and there is no path available to charge, when warrior is mid-air.
