### ISSUE TITLE
[Ticket] Quest: Taming the Beast

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#368]
"On the quest "Taming the Beast", I used the Taming Rod on a Mistbat. At the end of the cast, the mistbat kept attacking and was not tamed. I tried this 3 times and it did not work."

**Comment by Demmye** [comment]
Couldn't reproduce, the Taming Rod worked 10 out of 10 times on Mistbats and after the cast they were tamed.
