### ISSUE TITLE
Dungeon: The Nexus: Boss Commander Kolurg is not frozen

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#37]
**Description:**

Boss Commander Kolurg is not frozen

**Current behaviour:**

Boss Commander Kolurg is not frozen

**Expected behaviour:**

Boss Commander Kolurg is supposed to be frozen,

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/exhy8n

**Comment by JunkyBulgaria** [comment]
Both horde/alliance versions has been fixed.

**Comment by Deathtremor** [comment]
Re-tested. Confirmed. It work!
