### ISSUE TITLE
[Ticket] Quest: Gurubashi Arena

### ISSUE THREAD

**Issue by Siderbas** [FireFly-WoW/FireFly-IssueTracker#374]
Hi got the gurubashi arena trinket, use it for the quest. Couldnt talk to the guy so i abadoned the quest, hence losing the trinket aswell....

http://i.imgur.com/9fmNAJ2.png

**Comment by Demmye** [comment]
The quest itself is working perfectly. However, I lack info if you should or should not lose this quest item after abandoning the quest.
