### ISSUE TITLE
[Quest Item] Unidentified Plant Parts

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#376]
**Description:**

Hey guys, doing this quest "Plants of Zangarmarsh" for the 2nd time now on an alt toon and I seem to be experiencing the same problem as the first time I did it.  The item "Unidentified Plant Parts" should drop from most (if not all) mobs in the zone.  Check here for a full list of mobs that is supposed to drop this item - http://www.wowhead.com/item=24401/unidentified-plant-parts.  The issue I am having is that I can only seem to get them from "Young Sporebats".

This item is also part of a repeatable quest turn-in called "Identify Plant Parts" which is one of the best ways to raise reputation with the Cenarion Expedition.

**Current behaviour:**

Quest item only drops from one mob in the zone.

**Expected behaviour:**

Quest item should drop from all mobs in Zangarmarsh.

**Steps to reproduce the problem:**

1. Try looting different kinds of mobs in the zone.
2. Loot Young Sporebats.
3. Compare drop rates.

Item should have about a 20-25% drop chance on all mobs so I'm certain I would have gotten some by now if this was not a bug.

**Screenshots:**

url...
url...
url...

**Comment by Ikaros84** [comment]
**Update**

I was just able to get one of these items from the "Marsh Dredger" and "Marsh Lurker" mobs.  Some examples of mobs that won't drop them are the "Umbraglow Stingers" and "Fen Striders".

I'll keep an eye out for mob types that aren't dropping the item and update this thread as I go.

**Comment by Demmye** [comment]
Lagoon Walkers and any kind of Sporebats seem to drop them as well, but various types of mobs that should drop Unidentified Plant Pars do not drop them in PTR.

**Comment by Siderbas** [comment]
Can you get a list of mobs who are not dropping them but should. Thank you

**Comment by Ikaros84** [comment]
**Update**

Seems all the Naga are dropping the item, but not getting any drops from Fungal Giants or Bog Lords.
