### ISSUE TITLE
Vault of Archavon - Archavon, the Stone Watcher

### ISSUE THREAD

**Issue by Demmye** [FireFly-WoW/FireFly-IssueTracker#377]
**Description:**

Some mechanics of Vault of Archavon boss Archavon are really broken.
**Current behaviour:**

1. Stomp - when the boss uses Stomp, he only picks up the main tank for a second and then throws him right under himself, stunning him again for ~6 seconds.
2. Crushing Leap - boss ability is not scripted at all, doesn't occur ever.
3. Choking Cloud - this is created in place that Crushing Leap have occured, but since it is not scripted, this is not working as well.

 **Expected behaviour:**

1. Stomp - boss should pick up the main tank for ~10 seconds and then throw him ~30 yards from the raid.
2. Crushing Leap - it should randomly jump/charge towards a random raid member and leave a white cloud on the floor which will do ~2k nature damage per tick if you are standing in it. After he spawns the cloud he should stand still for a couple seconds then run back towards the main tank.
3. Choking Cloud - should be placed when Crushing Leap is used, and should do ~2k per tick aoe damage and reduce hit chance by 50%.

Video footage of working encounter (tank point of view): https://www.youtube.com/watch?v=hAv07d_PRCI

**Comment by Soockee** [comment]
Just did VoA.
Stomp can be confirmed.
He DID use the Leap and also casted the Cloud.

**Comment by Demmye** [comment]
My apologies, upon some research I found out that crushing leap has minimal range of 10 yards, that's why  I did not experience it while testing alone.

**Comment by JunkyBulgaria** [comment]
took over the issue and fixed it as it's high prio release-pending
