### ISSUE TITLE
Dungeon: Deadmine - 3 Patrols are missing.

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#38]
**Description:**

3 patroling groups are missing.

**Current behaviour:**

After you kill any of the first 3 bosses no patrol spawns.

**Expected behaviour:**

After you kill any of the first 3 bosses, 2-3 elite Defias mobs are supposed to spawn and start patroling the area. 

From wowwiki: 

_After defeating each of the first three bosses, 2-3 elite Defias mobs will wander and patrol that room and the mine around the boss room. Be careful when backtracking to a room, or running back after a death. These patrols can be evaded by hiding until they pass; the Shredder's ramp is one such hiding place (even though it does not look like you are hidden.)_ 

Source: http://wowwiki.wikia.com/wiki/Deadmines_(original) 
Video: https://www.youtube.com/watch?v=nOPK5IRv4kg

**Comment by JunkyBulgaria** [comment]
Thanks!

**Comment by JunkyBulgaria** [comment]
Applied Fixes:
- Rewritten from SmartAI > C++
- Sniffed and Implemented all(3) boss texts.
- Creature group (2x Wizzards, 1x Taskmaster) will now spawn as they are supposed to on boss death.

Todo: 
- Sniff waypoints and implement them.

**Comment by JunkyBulgaria** [comment]
waypoints sniffed and implemented, works as intended now
