### ISSUE TITLE
Naxxramas - Anub'Rekhan's Impale

### ISSUE THREAD

**Issue by Demmye** [FireFly-WoW/FireFly-IssueTracker#380]
**Description:**

Impale is an area-of-effect ability that targets a random player and hits everyone in a straight line between Anub'Rekhan and the player, causing 5688 to 7312 physical damage and launching the affected players high in the air, who then suffer 50% fall damage when they hit the ground.

**Current behaviour:**

If everyone in the raid get Impaled, the boss resets.

**Expected behaviour:**

It definetly should not.

**Steps to reproduce the problem:**

1. Start the encounter
2. Stack up.
3. Wait until the boss casts Impale.

**Comment by Demmye** [comment]
Tested again today, the issue is still there.

**Comment by frytik** [comment]
@Demmye It is still done ? With my new mmaps, it looks like no.

**Comment by JunkyBulgaria** [comment]
should be working on ptr, there was two issues about this, could be duplicate

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Fixed.
