### ISSUE TITLE
[Dungeon] Gundrak - Eck the Ferocious

### ISSUE THREAD

**Issue by Demmye** [FireFly-WoW/FireFly-IssueTracker#382]
**Description:**

Eck the Ferocious, a gorloc, is an optional boss in Gundrak, only accessible in Heroic mode.

**Current behaviour:**

It is accessible in Normal mode.

**Expected behaviour:**

It should not show up in Normal mode after you clear trash in his room.

**Steps to reproduce the problem:**

1. Enter Gundrak on Normal Difficulty.
2. Go to Shrine of Eck.
3. Clear the trash mobs.

**Comment by philoudu16** [comment]
Eck still shows up on normal mode on PTR.

**Comment by JunkyBulgaria** [comment]
will be fixed after restart, instead of heroic i wrote normal :^)

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Fixed.
