### ISSUE TITLE
[Quest][Northrend][The Storm Peaks]The Drakkensryd

### ISSUE THREAD

**Issue by Soockee** [FireFly-WoW/FireFly-IssueTracker#386]
### Current Behaviour:
Tried to reaccept the quest.
Just a Blue questionmark but not able to accept the quest.

## Expected behaviour:
After the restart yesterday, the quest should be automtically completed when you accept it.

## Video of current Situation:

https://www.youtube.com/watch?v=1YOZLFDfpGw&feature=youtu.be

Edit: Checked out thorim unusual behaviour aswell:
Yellow Questionmark, but nothing to turn in
![wowscrnshot_052717_145133](https://cloud.githubusercontent.com/assets/24325735/26521577/190e1b3c-42ec-11e7-8d33-45c7f71e73a1.jpg)

![wowscrnshot_052717_145149](https://cloud.githubusercontent.com/assets/24325735/26521578/1a8c8192-42ec-11e7-93e2-0073710a9c96.jpg)

**Comment by Siderbas** [comment]
#274
