### ISSUE TITLE
[Item] Book of Glyph Mastery

### ISSUE THREAD

**Issue by Nasuuna** [FireFly-WoW/FireFly-IssueTracker#387]
Neither the guilds Karma[A] or Dathraki[H] have seen a single one of the glyph books drop.

Both have double digit 80s and do regular runs, neither have seen one.

**Comment by Demmye** [comment]
Not sure if intentionally, but it might be disabled. The server is progressive and the current patch is 3.0.3. Book of Glyph Mastery has been added in patch 3.1.0.

**Comment by Nasuuna** [comment]
Ahhhh, that'll do it

**Comment by JunkyBulgaria** [comment]
Correct, it was added in 3.1.0
