### ISSUE TITLE
[Mob] Marshfang Ripper

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#389]
**Description:**

The Marshfang Ripper mob in Zangarmarsh is missing its model.  It appears as a very small squared checkered box.  It seems to still use all of its abilities and functions properly but the 3D model of the mob itself is missing.

**Current behaviour:**

Mob shows up as a small blue and white checkered box.

**Expected behaviour:**

Mob should look like the screenshot located on http://www.wowhead.com/npc=18130/marshfang-ripper

**Steps to reproduce the problem:**

1. Locate a Marshfang Ripper in Zangarmarsh (very difficult to see, check screenshot below)

**Screenshots:**

https://anonimag.es/i/WoWScrnShot_052717_12310470bd1.jpg

**Comment by Stadics** [comment]
Client side issue.

http://imgur.com/a/eQ7Wk
