### ISSUE TITLE
Brotherhood of Thieves | | Defias Thug and Garrick Padfoot

### ISSUE THREAD

**Issue by svedizz** [FireFly-WoW/FireFly-IssueTracker#39]
**Description:**

They are passive.

**Current behaviour:**

The same as mentioned in the description.

**Expected behaviour:**

These NPCs were aggressive before patch 3.3.

**Screenshots:**

http://wowwiki.wikia.com/wiki/Defias_Thug
http://wowwiki.wikia.com/wiki/Garrick_Padfoot

**Comment by JunkyBulgaria** [comment]
fixed

**Comment by svedizz** [comment]
Oh, I also noticed that the same thing goes for these mobs in Coldridge Valley. 
http://db.vanillagaming.org/?npc=706#wh-comments

**Comment by svedizz** [comment]
I'll go around and check in the other starter zones for Alliance as well.

**Comment by svedizz** [comment]
Yup, I found these as well: http://wowwiki.wikia.com/wiki/Webwood_Spider
http://wowwiki.wikia.com/wiki/Blood_Elf_Scout
http://wowwiki.wikia.com/wiki/Surveyor_Candress

**Comment by svedizz** [comment]
It actually appears that every mob that's connected to the same kind of quest in every starter zone have been changed to neutral in 3.3.

**Comment by JunkyBulgaria** [comment]
Make new report for them because this one will get extremely long please, thanks for your reports!
