### ISSUE TITLE
Quest bug 

### ISSUE THREAD

**Issue by davidup111** [FireFly-WoW/FireFly-IssueTracker#393]
Hello Firefly team!

I find a buged quest in Feralas. The quest name is (Freedom for All Creatures). 
I rescue all  Captured Sprite Darter, but the quest didn't complated. Please repair it how else not take problem.

Thanks in advance the help.

Good job!

**Comment by Shrizz** [comment]
I've managed to complete this entire chain and have the pet. Can you elaborate on the issue? I didn't have any issues and I completed it over a week ago I believe. There is, however, a bugged quest in Feralas that I found after doing everything else in the zone: Wandering Shay. I'm going to make a bug report for it now, while I'm doing reports :)

**Comment by JunkyBulgaria** [comment]
sai was a bit odd, now works as intended

**Comment by Hardcore-FireFly** [comment]
Tested on PTR today.
I opened the cage, all **Sprite Darters** came out and despawned.
Went to **Kindal Moonweaver** and tried talking to her, no option was available. 
The quest was not completed.

**Comment by Axxee** [comment]
I've reported this qt to a gm long time ago, like 2 months or even more...
it still doesn't work hmm... darn it

**Comment by Hardcore-FireFly** [comment]
@Axxee : You should report all bugs regarding quests or anything else here. It will be processed alot faster and easier :)

**Comment by frytik** [comment]
Can't see issue with that quest. Work's for me, maybe because junky change's, i just will revert it back. Soon fix applied.
