### ISSUE TITLE
[Quests] Frenzyheart Tribe

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#396]
**Description:**

In Sholazar Basin the quest "Playing Along" is picked up from "Tracker Gekgek" and leads you to the Frenzyheart Tribe.  Upon turning this quest in it should unlock a whole chain of quests from the Frenzyhearts including some daily quests that can be completed to raise reputation with the Tribe and earn rewards.  However, no other quests become available after turning in the Playing Along quest.  This is somewhat of a major bug because it blocks access to an entire faction and 20 or so quests, 8 of which are dailys.

**Current behaviour:**

Playing Along quest does not unlock further quests from the Frenzyheart Tribe.

**Expected behaviour:**

The quest should lead to "The Ape Hunter's Slave" and many more quests from the Frenzyhearts.

**Steps to reproduce the problem:**

1. Kill "Pitch" located at 50,77 in Sholazar Basin.
2. Accept the quest "Playing Along" from Tracker Gekgek located nearby.
3. Turn in "Playing Along" and check for follow-up quests.

**Comment by Erivanz** [comment]
Worked as intended for me. Did  you click on the Item you get to summon the guy who actually Gives you the quest? Looks like a bracer.

**Comment by Ikaros84** [comment]
I think you are right.  I don't recall receiving the item, but I was just able to get the shackles from Elder Harkek and start the next quest.  Thanks..

**Comment by Demmye** [comment]
Could not reproduce on PTR, seems to be working as intended.
