### ISSUE TITLE
[Quest]  [A Sample of Slime...]

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#397]
Description:

On the quest Quest A Sample of Slime... I cannot loot more than 15  [Felwood Slime Sample] at a time.

Current behaviour:

Once you have looted 15  [Felwood Slime Sample] you cannot pick up anymore. Since I usually gather around 30 when doing this quest this is oddly behaviour. Even tough you should be able to get enough to be safe once you start the process, it wont pick up extra even if you see them.

Expected behaviour:
You are supposed to gather as many as you want. (If you decide that)

Steps to reproduce the problem:

Go to Felwoods, bloodvenom river
2. Kill the oozes, gather 15 [Felwood Slime Sample]
3. Notice how you cannot get anymore.

Note: The chance of getting 5 from 15 is low, since you can go through 5 without getting 1 point in quest credit, making 15 [Felwood Slime Sample] if you are unlucky , 3/5 completion, thus you will have to return and farm again as you are unable to be prepared with this limit.

**Comment by Demmye** [comment]
This is definetly not a bug. 15 is the limit since patch 3.2.2. The drop rate should be 100% though(and it is on PTR).
