### ISSUE TITLE
[Quest] Whelps of the Wyrmcult

### ISSUE THREAD

**Issue by totaemoeggerli** [FireFly-WoW/FireFly-IssueTracker#398]
**Description:**

Quest "Whelps of the Wyrmcult" in Blades Edge Mountains doesn't work.

**Current behaviour:**

Blackwhelp Net loses 1 charge when used on Wyrmcult Blackwhelp. Animation on Whelps works fine. Whelps despawn without being placed in Inventory.

**Expected behaviour:**

Whelps should be palced in inventory after using Blackwhelp Net.

**Steps to reproduce the problem:**

1. Step 1 Start quest Wyrms of the Wyrmcult
2. Step 2 Go to Blackwing Coven
3. Step 3 Target Wyrmcult Blackwhelp and use Blackwhelp Net

**Comment by Demmye** [comment]
Couldn't reproduce on PTR, seems to work fine.
