### ISSUE TITLE
Burning Blade Coven (starter spot)

### ISSUE THREAD

**Issue by Plantfusion** [FireFly-WoW/FireFly-IssueTracker#4]
**Description:**

Problem when moving inside the burning blade coven (starter spot for Orc/Troll)

Current behaviour:

I get several disc./crash at some places.

Expected behaviour:

Not suppose to get disc/crash while running inside the cave.

Quest: None

**Comment by JunkyBulgaria** [comment]
TODO: False positive (from anticheat), FloorZ instantly turns to -20,000.00

**Comment by JunkyBulgaria** [comment]
Hotfix applied, please test again after restart.

**Comment by Plantfusion** [comment]
Tried again and same problem.
