### ISSUE TITLE
Dungeon: Azjol Nerub (Normal): Krik'thir the Gatewatcher - Pre-fights

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#40]
**Description:**

* Broken linking mechanic of group of spiders in from of Krik'thir the Gatewatcher. ( Boss event )

**Current behaviour:**

* When you enter the room and you automatickly pull random group or just one or two spiders without even going close to them or pulling them.

**Expected behaviour:**

* When you enter the room none of the group should be pulled unless you pull them or go too close to them. You should be able to pull each group of 3 spiders ONE by ONE.

**Comment by frytik** [comment]
Soon big update comming. aprox. 1 day

**Comment by frytik** [comment]
Fix done. Soon will be applied.

**Comment by frytik** [comment]
https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/415
