### ISSUE TITLE
Bug Quest: "Plaged Lands"

### ISSUE THREAD

**Issue by JeremyCC95** [FireFly-WoW/FireFly-IssueTracker#400]
**Description:**

CHANGEME: Hello, the quest "Plaged Lands" on Darkshore have a bug and is it not possible complete the quest, the video explain perfectly what happen: https://www.youtube.com/watch?v=j67JjUoj3tw

**Current behaviour:**

CHANGEME: The bear doesnt get trapped.

**Expected behaviour:**

CHANGEME: The bear must be get trapped on the item quest.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Demmye** [comment]
Confirmed on PTR, the trap does not function.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Works fine.
