### ISSUE TITLE
[Quest] [... and a Batch of Ooze]

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#402]
Description:

As the previous A sample of slime -
Quest  [... and a Batch of Ooze]. I cannot loot more than 15 [ [Un'Goro Slime Sample]] at a time.

Current behaviour:

Once you have looted 15  [Un'Goro Slime Sample] you cannot pick up anymore. Since I usually gather around 30 when doing this quest this is oddly behaviour. Even tough you should be able to get enough to be safe once you start the process, it wont pick up extra even if you see them.

Expected behaviour:
You are supposed to gather as many as you want. (If you decide that)

Steps to reproduce the problem:

Go to Un'Goro
2. Kill the oozes, gather 15 [Un'Goro Slime Sample]
3. Notice how you cannot get anymore.

Note: The chance of getting 5 from 15 is low, since you can go through 5 without getting 1 point in quest credit, making 15 [Un'Goro Slime Sample] if you are unlucky , 3/5 completion, thus you will have to return and farm again as you are unable to be prepared with this limit.

A note: the travel time from uc, to either ungoro or felwoods ,and return twice is extremely time consuming, because of this limit. I had to abondon this quest as I just didnt feel like going back after the unlucky range of 4/5.

**Comment by Siderbas** [comment]
#397
