### ISSUE TITLE
[NPC] Dark Ranger Vorel

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#403]
This NPC is the one that starts the FoS/PoS quest chain for the horde side, and she is currently in Dalaran giving her quest. She was added in the game in 3.3.0 according to Wowhead:
http://fr.wowhead.com/npc=37780/forestier-sombre-vorel

**Comment by Demmye** [comment]
Confirmed on PTR, I guess Dark Ranger Vorel(npcID=37780) and Apprentice Nelphi(npcID=37776) should be disabled until we progress to 3.3.0.

**Comment by philoudu16** [comment]
I think the whole of Dalaran got patched somehow. There are all the emblem vendors, archimage Lan'dalock gives her weekly raid quests, the engi ah bots are there (they were added in 3.2), the tournament guy is on Krasus' Landing, and some other stuff... These were not there a few days ago.

**Comment by JunkyBulgaria** [comment]
They are just spawned, you can't complete the quests neither you can do the dungeons.

**Comment by philoudu16** [comment]
Dark Ranger Vorel is correctly removed from Dalaran on PTR.
However, the fountain in the center of Dalaran is still there, the engineer AH bots are still there, Minigob Manabonk aswell, Rhonin  gives the quest that leads to the "Assault on the Sanctum" quest (which is also available at the Wyrmrest Temple), and the tournament guy on Krasus landing is also there.

**Comment by JunkyBulgaria** [comment]
Assault on the Sanctum - removed, rest is just cosmetic (non-important) i guess.
