### ISSUE TITLE
[Weapon] - Blade of the Unyielding

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#405]
**Description:**

Despite the fact that it isn't in the description of the weapon, this sword can actually summon two Unyielding Knights to fight alongside you for a brief amount of time.
This is a hidden function inside the weapon.

**Current behaviour:**

While testing the One handed sword, nothing except a regular attack happens.

**Expected behaviour:**

While attacking a enemy, randomly it should spawn 2 npc that helps out and attacks the targeted monster. 

**Steps to reproduce the problem:**

Complete the quest Honor the Fallen, horde.
2. Equip the one handed weapon Blade of the Unyielding
3. Keep attacking mobs, and you will notice nothing is spawning and helping you out.

No screenshots as its a trigger from autoattacks.

**Comment by Demmye** [comment]
Confirmed, the weapon doesn't proc at all.
More information about the weapon: http://www.wowhead.com/item=29108/blade-of-the-unyielding#comments

**Comment by JunkyBulgaria** [comment]
Unyielding Knights
- Procs only if your target is Grillok Darkeye(19457)

that's what we have from sniffs thats how it works, needs testing

**Comment by Hardcore-FireFly** [comment]
Tested on PTR and against **Grillok "Darkeye"**.

Procs 2 **Unyielding Knight**s. Works fine.
