### ISSUE TITLE
Quest: Arelion's Secret

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#407]
**Description:**

This quest works - but it can be completed without fighting him.

**Current behaviour:**

Just find him on the road between Falcon Watch and Zangamarsh. He will simple accept the quest.

**Expected behaviour:**

You are supposed to interact with him, then start a fight. Bring him to low hp and then he will turn into a friendly npc where you can talk to him and hand over the quest and get the next in line.

**Steps to reproduce the problem:**

Have the quest Arelion's Secret
2. Find him
3. Notice how you dont have to fight him.

Note: the quest works but with this minor inconvinence.

**Screenshots:**

http://imgur.com/a/nXj12

**Comment by Demmye** [comment]
Confirmed on PTR, interrogation event does not work at all.
