### ISSUE TITLE
Dungeon: Azjol Nerub (Normal): Hadronox Boss - Pre-fights + Boss itself

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#41]
**Description:**

Pre-fights:

* Some of mobs are not at spots there are supposed to be. - Anub'ar Crusher is at wrong spot.
* Some Mobs are missing - 2x Anub'ar Champion
* Mobs in Hedronos's Lair keeps respawning after a while you kill them
* Two groups of Anub'ar Crusher and Anub'ar Champion spawns too fast after you pull the first group of  Anub'ar Crusher and Anub'ar Champion in the middle of Hedronos's Lair. 

Boss itself:

* Boss event seems to restart at some point. 

**Expected behaviour:**

* There is supposed to be 1x Anub'ar Crusher and **2x Anub'ar Champion** in the middle of Hedronos's Lair.

* After you pull them you should have about 10 sec to go to safe distance before two other groups of 1x Anub'ar Crusher and 2x Anub'ar Champion are spawned.

* 2 groups 1x Anub'ar Crusher and 2x Anub'ar Champion must be enough from each other so you can pull them one by one. 

* Mobs are not supposed to keep respawning after you kill them. 

Video: https://youtu.be/mTlJn8oGTJ0?t=1m48s

**Comment by JunkyBulgaria** [comment]
@frytik you can take the entire dungeon

**Comment by frytik** [comment]
I will

**Comment by frytik** [comment]
Soon big update comming.

**Comment by frytik** [comment]
Fix done. Soon will be applied.

**Comment by frytik** [comment]
https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/415
