### ISSUE TITLE
The Drakkensryd

### ISSUE THREAD

**Issue by Shadoki** [FireFly-WoW/FireFly-IssueTracker#410]
**Description:**

The Drakkensryd quest is bugged.

**Current behaviour:**

The problem is if you have the preq and go to Gretta to accept the Drakkensryd q, you wont get sent flying, when you are mounted, so i cancelled the quest and tried to accept it again, but you cant accept it anymore now.

**Expected behaviour:**
You should be sent flying to in order to kill the 10 dragons by jumping from dragon to dragon.

**Screenshots:**

url...
![wowscrnshot_053117_202246](https://cloud.githubusercontent.com/assets/28987926/26647244/f982096c-463e-11e7-8a02-a7f90c309fe3.jpg)

Im sorry for the Screenshot being german, it shouldnt be a problem though.

**Comment by Siderbas** [comment]
There are already severl open issues about this quest, thank you for reporting, but please use the search function next time and if there already is an open issue comment on it with your findings. closed and referenced.

**Comment by Shadoki** [comment]
oh, im sorry, i used the tool and didnt find anything, must have typed something wrong...

**Comment by Siderbas** [comment]
np! thanks for the report!
