### ISSUE TITLE
Quest - Root Samples

### ISSUE THREAD

**Issue by Sponkz** [FireFly-WoW/FireFly-IssueTracker#411]
**Description:**

CHANGEME: Describe the issue here

In the quest Root Samples, you are able to pick up the root samples from herbs in durotar.

**Current behaviour:**

You simply pick up herbs in durotar and u get the root samples. Haven't tested in other zones due to low herb, but i bet ya 5$ it will work on herbs from stonetalon too. 

**Expected behaviour:**

You are supposed to get Root samples ONLY from barrens. It says so in the quest

**Screenshots:**
Not needed, pretty self-explanatory

**Comment by Demmye** [comment]
Confirmed on PTR, Root Samples can be picked in plenty other zones and it should only be available in Barrens.

**Comment by frytik** [comment]
Should be fixed at next restart.
