### ISSUE TITLE
[Quest] WarChief's Blessing.

### ISSUE THREAD

**Issue by MummieSenpai** [FireFly-WoW/FireFly-IssueTracker#412]
**Description:**

as a player you don't feel the disrespect towards you as a Death Knight.

**Current behavior:**

first of all you get teleported in The Vally of Spirits (not supposed to happen)
second of all Gamon doesn't attack you he stays neutral 
third on the list no disrespect towards you.

**Expected behaviour:**

Players will find themselves outside the gates of a very unfriendly Orgrimmar. Any and all NPCs will show their displeasure and call for a rope or spit or throw rotten food, while Gamon will actively attack you, provided he's not dead. Thrall himself tells the player that it is an interesting turn of events before handing in the letter.

**Steps to reproduce the problem:**

1. Take The portal to Orgrimmar
2. Step 2 walk around in the city
3. Step 3 noting happens 

**Screenshots:**

I Don't have screen shots but i have some links to sources of what sould happen.
http://wowwiki.wikia.com/wiki/Quest:Warchief%27s_Blessing
https://www.youtube.com/watch?v=m8M4puZftTE

**Comment by MummieSenpai** [comment]
On completion:

Thrall yells: Horde, hear the call of your Warchief!
Thrall yells: Today marks the first of many defeats for the Scourge! Death knights, once in service of the Lich King, have broken free of his grasp and formed a new alliance against his tyranny!
Thrall yells: You will welcome these former heroes of the Horde and treat them with the respect that you would give any ally of Orgrimmar!
Thrall yells: For the Horde! 

doesn't happen 
http://i.imgur.com/pOXmcfm.png

**Comment by Demmye** [comment]
Can confirm, the event is not scripted.
