### ISSUE TITLE
Gnome Improvement

### ISSUE THREAD

**Issue by sting1080** [FireFly-WoW/FireFly-IssueTracker#414]
**Description:**

Can not turn in quest

**Current behaviour:**

Have all items in inventory still wont let me turn in.

**Expected behaviour:**

Allow user to finish quest

**Steps to reproduce the problem:**

Abandoned quest and picked it back up again still same issue. 
Had another friend try this and same problem occurred.

**Screenshots:**

url...
![wowscrnshot_053117_192237](https://cloud.githubusercontent.com/assets/28846981/26655828/1109cc12-4637-11e7-990f-6b3fbfd156f3.jpg)

url...
url...

**Comment by Demmye** [comment]
Could not reproduce on PTR, turned in the quest without any issues.
