### ISSUE TITLE
[Quest] Missing Quest: Poisoned Water

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#416]
**Description:**

The quest, Poisoned Water, is not being offered by Duke Hydraxis in Azshara. This quest should be available, as well as the rest of the chain he offers, until patch 3.0.8 (we are currently on patch 3.0.2). As such, it's not possible to complete his chain and earn the Feat of Strength, The Fifth Element, even though you should be able to until patch 3.0.8.

**Current behaviour:**

Duke Hydraxis does not offer the quest, Poisoned Water.

**Expected behaviour:**

Duke Hydraxis should offer the quest, Poisoned Water. When the player completes that as well as the quest, Stormers and Rumblers (he does offer this), the next quest in the sequence should become available. The whole chain is: Poisoned Water + Stormers and Rumblers -> Eye of the Emberseer -> The Molten Core -> Agent of Hydraxis ->Hands of the Enemy ->A Hero's Reward.

When you complete Hands of the Enemy, you can obtain an Aqual Quintessence and thus earn the Feat of Strength, The Fifth Element. The final quest, A Hero's Reward, completes by choosing a reward from Hydraxis' Coffer (a choice of 2 rings: Ocean's Breeze or Tidal Loop). Additionally, when you reach Revered reputation, you should be able to obtain an Eternal Quintessence from Duke Hydraxis. If memory serves, he has a new dialogue option at that point, which you can select to obtain it.

http://wowwiki.wikia.com/wiki/Quest%3APoisoned_Water

**Steps to reproduce the problem:**

1. Visit Duke Hydraxis in Azshara (79.3, 73.7).
2. Confirm that he does not offer the quest, Poisoned Water.

**Screenshots:**

N/A

**Comment by Demmye** [comment]
Confirmed on PTR, the quest is not available.

**Comment by Hardcore-FireFly** [comment]
Available on PTR.
