### ISSUE TITLE
[Quest] [Howling Fjord] [71] Adding Injury to Insult (Part 2 of 2)

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#417]
**Description:**

_"Read the Vrykul Insult to Bjorn Halgurdsson in Baleheim, then lead him back to Lydell's ambush and help slay him."_

This quest isn't working properly for me.  I am able to read the insult which instigates Bjorn Halgurdsson into chasing me, however, once we get close to the ambush site Bjorn turns around and goes back.  This happens even if I stay close to Bjorn.

I was able to complete the quest only because I popped CDs and solo'd him before he reset.

**Current behaviour:**

Bjorn resets just before reaching ambush site.

**Expected behaviour:**

Bjorn should continue chasing until reaching ambush site, then NPCs should engage Bjorn.

**Steps to reproduce the problem:**

1. Accept the quest
2. Read the insult to Bjorn
3. Lead Bjorn to ambush site

**Screenshots:**

url...
url...
url...

**Comment by Demmye** [comment]
Could not reproduce, seems to work fine.

**Comment by Siderbas** [comment]
need testing on live.

**Comment by Tr4dY** [comment]
Hello, I can confirm having issues on this quest too on 06/04/2017.
I engage the NPC with the scroll, he follows me, and reset before I can get to the ambush camp.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Works fine.
