### ISSUE TITLE
Quest: By Any Means Necessary

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#418]
Description:

This quest works - but it can be completed without fighting him.

Current behaviour:

In Terokkar Forest, Outland
Just find him on the road between Shattrath and Tuurem. He will simple accept the quest.

Expected behaviour:

You are supposed to interact with him, then start a fight. Bring him to low hp and then he and his guard will turn into a friendly npc where you can talk to him and hand over the quest and get the next in line.

Steps to reproduce the problem:

Have the quest By Any Means Necessary
2. Find him
3. Notice how you dont have to fight him.

Note: the quest works but with this minor inconvinence.

**Comment by Demmye** [comment]
Confirmed on PTR, the conviction event does not function at all.
