### ISSUE TITLE
Quest: Ishanah

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#419]
**Description:**

Once you completed City Of Light and gotten the follow up Allegiance to the Aldor and turned that in, you do not get the follow up quest Ishanah from Khadgar.

**Current behaviour:**

Currently Khadgar is not offering the quest.

**Expected behaviour:**

He should immediately offer the quest Ishanah to you if you align yourself with aldor.

**Steps to reproduce the problem:**

Complete the quest City Of Light
2. Accept and turn in Allegiance to the Aldor 
3. You will see that he does not offer any follow up quest.

**Screenshots:**

http://imgur.com/a/aV6pB

**Comment by Demmye** [comment]
Confirmed, Khadgar in Shattrath City does not offer any quest.

**Comment by JunkyBulgaria** [comment]
Requires http://www.wowhead.com/quest=10551/allegiance-to-the-aldor , please test again.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Fixed and working.
