### ISSUE TITLE
Mobs Blighted Elk and Rapid Grizzly seems to fall down through the texture (ground) into the room with Ahn'Kahet portal.

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#42]
**Description:**

Mobs Blighted Elk and Rapid Grizzly seems to fall through ground into the room with Ahn'Kahet portal. You can't even attack them.

![wowscrnshot_041617_121611](https://cloud.githubusercontent.com/assets/27430839/25068211/5b66837e-229f-11e7-8755-39c185a6b412.jpg)
![wowscrnshot_041617_121612](https://cloud.githubusercontent.com/assets/27430839/25068212/5e003fd0-229f-11e7-8e10-fb426a8c9e44.jpg)

**Comment by JunkyBulgaria** [comment]
Couldn't find these npcs http://prntscr.com/exi9md

Also this may happen only if you used high speed and the "map" wasn't loaded yet so they fell trough, it wouldn't happen without it. Please test again, thanks.

**Comment by Deathtremor** [comment]
I logged in, teleported to Dragonblight, use high speed to get there, above that area i used normal speed and when i get there i found tt like this. I tried to restart game, even delete cache folder but nothing happend. So i don't know. 

![wowscrnshot_041817_191215](https://cloud.githubusercontent.com/assets/27430839/25123468/c4793f1e-246b-11e7-8f84-89c732c8e66d.jpg)

**Comment by JunkyBulgaria** [comment]
Issue merged into #93
