### ISSUE TITLE
Shattrah City: Choosing Aldor

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#420]
**Desciption.**

Theres a few things I noticed while checking with aldor vs scryer aligning.

**Current behaviour:**

1. If you choose aldor side and you are either flying or going over to scryer side no guards will attack you.

2. When you align yourself with Aldor or Scryer different quests are opened to you.
But choosing Aldor I get a Scyer quest "Strained Supplies."
When I should be getting "A Cure for Zahlia." 

**Expected behaviour:**

1. Guards and npcs on either side should turn hostile to you and attack you. if you choose Aldor, then Scryer's will attack you.

2. You should be offered "A Cure for Zahlia." as Aldor.

**Steps to reproduce the problem:**

Align yourself with Aldor
2. Go to Scryer's place and see that no guards attacks.
3. Try pick up the faction quest "A Cure for Zahlia."  and you will only get offered "Strained Supplies."

**Screenshots:**

http://wowwiki.wikia.com/wiki/Aldor
http://imgur.com/a/vkYqe

**Comment by Demmye** [comment]
Guards are not attacking when you're hostile on PTR, that's a bug. But I could not find a bug with the quests, it work as it should on PTR - when you are friendly with Aldor, you get A Cure for Zahlia, and when you are hostile with Aldor you get Strained Supplies.
