### ISSUE TITLE
[Quest] [Howling Fjord] [71] Mutiny on the Mercy

### ISSUE THREAD

**Issue by Ikaros84** [FireFly-WoW/FireFly-IssueTracker#421]
**Description:**

_"Captain Ellis aboard the Sister Mercy in the Howling Fjord has asked that you recover 5 barrels of Blasting Powder from the ship's hold."_

The barrels that you are supposed to recover come from killing the ghouls in the lower level of the ship.  But the ghouls seem to be glitched into the water way below the ship instead of being on the lower level.  They still seem to move with the ship but are so far underneath that they usually are in the ground most of the time.  They also still attack you when you go to the lower level, but you can't attack them back and are not visible.

**Current behaviour:**

Mobs are located underneath the ship in the water.

**Expected behaviour:**

Mobs should be on the lower level of the ship.

**Screenshots:**

https://anonimag.es/i/WoWScrnShot_060117_13503864574.jpg

**Comment by Demmye** [comment]
Could not reproduce on PTR, all the mobs seem to be on the ship.

**Comment by Siderbas** [comment]
Needs testing on Live

**Comment by thestranger064** [comment]
Can confirm here - they attack below the deck, and if you walk slowly you can get them above ground.
But I was only able to get 4/5. Needs optimization.

http://imgur.com/a/09Z96 - this just reveals I manage to get them to above the ground deck. Its not much to go on.
