### ISSUE TITLE
[Northrend] [Enemy]: Coldarra Mage Slayer

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#427]
**Description:**

This enemy cannot be killed and is constantly evading.

**Current behaviour:**

When trying to attack it always evade, but will not leave combat with you. You are forced to run away far before you leave combat.

**Expected behaviour:**

Its supposed to be attackable and killed.

**Steps to reproduce the problem:**

Find a Coldarra Mage Slayer in Coldarra, they walk with Coldarra Spellbinder's
2. Attack the group
3. Notice how it cannot be killed.

**Screenshots:**
http://imgur.com/a/z6MXc

**Comment by thestranger064** [comment]
Noticed just now another is made like this.
https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/284

However as you can see on screenshot it still does not work - this is on live realm.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Working fine. Tried on dozens of Mage Slayers.
