### ISSUE TITLE
NPC: Den Mother & Thisle cubs are not linked

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#43]
**Description:**

Den Mother & Thisle cub are not linked.

**Current behaviour:**

Whatever you attack one of the cubs or Den Mother alone it wont pull the rest of cubs or Den Mother.

**Expected behaviour:**

Whatever you attack one of the cubs or Den Mother alone, all of them are supposed to be pulled at once and try to kill you.

**Comment by Deathtremor** [comment]
There is a progress, however.

* When you pull Thisle Cub it wont pull Den Mother
* When you pull Den Mother it still wont pull  Thisle Cubs.

**Comment by JunkyBulgaria** [comment]
Thought only the mom is linked to the cubs, will fix it.
