### ISSUE TITLE
Rejek: First Blood

### ISSUE THREAD

**Issue by thompz** [FireFly-WoW/FireFly-IssueTracker#430]
**Description:**

CHANGEME: Objective won't complete

**Current behaviour:**

CHANGEME: Using Quest item on hardknuckle charger doesn't work - tried over 20 times and not coming up as objective complete.

**Expected behaviour:**

CHANGEME: Should come up as complete.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Condrios** [comment]
Same issue for me.
Kill monkey
use item => no trigger 
can keep using the item on the mob but no trigger

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

Works fine.
