### ISSUE TITLE
[Northrend] [Enemy] Gjalerbron Sleep-Watcher

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#433]
**Description.**

This particulary enemy is evading when trying to kill. Most does not evade and can be killed, but this cannot.

**Current behaviour:**

This one just evades when trying to kill it.

**Expected behaviour:**

You should be able to defeat it like the rest of them.

**Steps to reproduce the problem:**

Go to Gjalebron to coords 34.15.
2. Enage this particular Gjalerbron Sleep-Watcher 
3. See how it evades

**Screenshots:**

http://imgur.com/a/xxVQr

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Works fine.
