### ISSUE TITLE
Bloodsail Raider teleporting

### ISSUE THREAD

**Issue by Magnetrans** [FireFly-WoW/FireFly-IssueTracker#437]
The Bloodsail Raider closest to the Booty Bay entrance is teleporting, i think he's missing a 
walking animation. 

CHANGEME: Describe the issue here

Teleports to you immediatly and sometimes teleports away.

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

I tried for 3 spawns and the mob showed the same behaivior each time. Doesn't seem like other 
mobs of the same name do the same

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/fzIy6
url...
url...

**Comment by frytik** [comment]
Fixed.
