### ISSUE TITLE
[Naxx] Gluth 10 man

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#444]
During Gluth's encounter, Zombie Chows spawn and need to be kited away from Gluth.

Two issues here:
 - On 10 man, the adds should all spawn from the middle grate as you can see on this video or any other 10 man Gluth encounter footage: https://www.youtube.com/watch?v=KNN4ZYZuu2o . However on Firefly, the adds will randomly spawn from one of the three grates, making it extremely hard to do with only one kiter.

 - Also, the adds give you a stacking debuff (http://www.wowhead.com/spell=29306/infected-wound) every time they hit you. This debuff is shared by all the adds, resulting in just one debuff with many stacks if several mobs hit you. On firefly however, each add gives you a separate debuff, resulting in many debuffs with few stacks. This means that your stacks will get reset more easily than they should (and maybe also that the mob only deals the damage from the stacks it gave you itself rather than the damage of all the stacks combined, didn't really have time to check).

**Comment by philoudu16** [comment]
On PTR:

The adds still stack the debuff separately (several debuffs with few stacks each rather than one massive debuff).

The adds are spawning from a single grate, but the wrong one: currently the southern one (on the left as you enter the room from the pipe) rather than the middle one.

**Comment by JunkyBulgaria** [comment]
should be working as intended now, if it doesn't then it is the last gate, needs testing after restart
(they are numeric, i don't know which number where belongs so it will be by guessing)

**Comment by Hardcore-FireFly** [comment]
Tested on PTR.

The spawn point of adds is fine. The stacking debuff problem (Infected Wound from Zombie Chow) yet persists.
