### ISSUE TITLE
Quest: Warsong Supplies 

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#447]
**Description:**

Warsong Axe Shipment respawn time is horrible long

**Current behaviour:**

My friend had to wait horrible many time more than an hour after i looted it.

**Expected behaviour:**

Should respawn much faster

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
will respawn in one minute now, it was 15min before

**Comment by bassuraaj** [comment]
Working on Live Realm, Spawn time is working properly.
