### ISSUE TITLE
Titanium Powder

### ISSUE THREAD

**Issue by Somerix** [FireFly-WoW/FireFly-IssueTracker#448]
Hi there,

When i'm prospecting my titanium ores, i should drop some titanium powders http://www.wowhead.com/item=46849/titanium-powder  but actually, after prospecting about 50 ores, havent seen any powder.

How it should work: It should drop by prospecting Titanium ores with a rate of 57% according to wowhead.

How to reproduce the bug; Prospecting titanium ores with a 450 JewelCrafter.

Plz fix it for the sake of my Dalaran Jewelcrafter tokens <3

**Comment by Shrizz** [comment]
According to http://wowwiki.wikia.com/wiki/Titanium_Powder, Titanium Powder was not added to the game until 3.2.0. :(

**Comment by Somerix** [comment]
Oh didnt remember about that, it's my miss :o 
Sorry for the disturbance !
