### ISSUE TITLE
Quest: Projections and Plans

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#449]
**Description:**

This quest is not working I cannot get it to complete or give me quest credit.

**Current behaviour:**

You teleport to the platform using  [Surge Needle Teleporter] and nothing happens.

**Expected behaviour:**

When you teleport to the platform using  [Surge Needle Teleporter] from the Moonrest Gardens - and go to the middle of the platform , the quest should get updated and you get the quest completed.

**Steps to reproduce the problem:**

Get the quest Projections and Plans
2. Go to Moonrest Gardens in Dragonblight and use the item [Surge Needle Teleporter].
3. Go to the middle or around the platform and you will see nothing happens.

There is a heavy quest chain  that follows after this, so its basically locked if you cant do this.

**Screenshots:**

http://imgur.com/a/xHuhD

**Comment by JunkyBulgaria** [comment]
should be working

**Comment by bassuraaj** [comment]
Working on Live Realm.
