### ISSUE TITLE
Dungeon: Halls of Stone (Normal): NPC: Brann Bronzebeard :  issues

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#45]
**Description:**

* Issue 1: Brann Bronzebeard is supposed to wait you at the gate that leads to the final boss. 
* Issue 2 : When he runs on the stairs that leads to the room with the gate that leads to the final boss he start kinda flying instead of running. (screenshot below)

**Current behaviour:**

Issue 1: When he gets to the gate the gate automatickly opens. 
Issue 2: When he runs on the stairs that leads to the room with the gate that leads to the final boss he start kinda flying instead of running. (screenshot below)

**Expected behaviour:**

* Issue 1:  Brann Bronzebeard is supposed to wait you at the gate that leads to the final boss. You need to talk to him first so he can open the gate.
* Issue: 2: Brann Bronzebeard is not supposed to fly & strangely walk. (lol) 

![wowscrnshot_041617_152921](https://cloud.githubusercontent.com/assets/27430839/25069131/9ffde25e-22bb-11e7-9285-d187c3e3ff42.jpg)

**Comment by Deathtremor** [comment]
Both issues seems to be fixed, however there are still issues: 

* Animation how he opening the gate is missing - Currently he just walk through the gate after you tell him to open it.

* When he enters the room with boss you can still tell him to open the gate. (screenshot)

* His HP won't restart when he gets out of combat where he lost some heath - Pretty much the same issue like with npcs in Zul'farrak dungeon.

![wowscrnshot_041817_193826](https://cloud.githubusercontent.com/assets/27430839/25124637/a9dd6db6-246f-11e7-9200-6c2f6a2d522b.jpg)

**Comment by JunkyBulgaria** [comment]
is this on a different encounter?

**Comment by Deathtremor** [comment]
As we spoke on Discord. These issues are all related to this NPC.

**Comment by JunkyBulgaria** [comment]
gossip fixed, emote should be active for few secconds
