### ISSUE TITLE
[Quest] The Battle of Darrowshire is Not Working

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#456]
**Description:**

The quest, The Battle of Darrowshire, in Eastern Plaguelands is not working. As such, it and the follow up quest, cannot be completed.

**Current behaviour:**

When you place the Bundle of Relics, the NPC Davil Lightfire spawns, but he does nothing (he despawns after 5 minutes or so). No enemies spawn and no event occurs.

**Expected behaviour:**

I don't recall the exact sequence of events, but from what I remember and the wowhead comments, several waves of enemies are meant to spawn (quite a few actually, I remember the event taking over 5 minutes to do in vanilla). In the first phase, you are defending Davil Lightfire. Horgus shows up near the end and Davil should die. Kill Horgus to get into the second phase. In the second phase, you are defending Captain Redpath. At some point, Captain Redpath will die as part of the event and despawn (if he dies from enemies, the quest fails). This occurs by Marduk the Black showing up and corrupting him, causing a Corrupted Redpath to spawn (nearby I think). Killing him and receiving forgiveness from Redpath should mark the end of the sequence and grant you quest credit. Starting with the second phase, tougher undead Bloodletters should be among the spawning waves.

http://db.vanillagaming.org/?quest=5721#wh-comments

Bogsie's comment was quite informative for details and the sequence rings true to my memories of doing it this last year on vanilla servers.

**Steps to reproduce the problem:**

1. Acquire the quest, The Battle of Darrowshire.
2. Place the Bundle of Relics in the Darrowshire town square.
3. Observe that the event sequence that should happen, does not occur, and the quest cannot be completed.

**Screenshots:**

1) https://ufile.io/9y6vh

**Comment by JunkyBulgaria** [comment]
event coded, needs testing
