### ISSUE TITLE
[Dalaran] Forge for smelting

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#457]
**Description:**

There is a problem finding forges. In all the places of my screenshots those areas should be counted as forges, but only the mining one has one.

**Current behaviour:**

Right now 1 of 4 places is able to be used as a forge.

**Expected behaviour:**

All places in my screenshots should work. 
1. 2 in bs area on the wall , 
2. in the middle room on the wall between mining area and the miningtrainer
3. the only area working is near the mining trainer.

**Steps to reproduce the problem:**

Try smelting at bs trainer location
2. middle between bs and mining trainer.

**Screenshots:**

http://imgur.com/a/7IYbv

**Comment by JunkyBulgaria** [comment]
those aren't forges, just cosmetic on the wall and the other thing you went to is an "Anvil"
