### ISSUE TITLE
Quest: Betrayal

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#461]
**Description:**

First, upon entering the skull is on the floor and cannot be interacted with , yet. It shouldnt lie around there if Drakuru is still up and not dead. 
Second, the portal Drakurus Last wish is not there either so you have to improvise to get down there.

**Current behaviour:**

You can see the skull on the floor, but not be able to interact with him. After you kill him, you can interact with it and complete it.

**Expected behaviour:**

You are not supposed to see the skull before hes dead
And you are supposed to be able to tele out of there with Drakurus last wish.

**Steps to reproduce the problem:**

Get the last quest in the chain Betrayal
2. Talk to Drakuru to be teleported up the platformm you will see the skull but unable to pick it up.
3. Once hes dead, you can loot it, but you are missing the portal down - forcing you to improvise how to get down. Up to you heh.

**Screenshots:**

http://imgur.com/a/vRe7j

**Comment by Siderbas** [comment]
#342

**Comment by frytik** [comment]
Also made fix for that, should be applied and needed to test soon.
