### ISSUE TITLE
Quest: The Bait for Lar'korwi

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#465]
**Description:**

Cannot kill the mob cuz the item not spawns it

**Current behaviour:**

You can use the item on the correct space and the character places it down but the mob never appears which you have to kill.

**Expected behaviour:**

It should spawn the or just place the mob there.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by Siderbas** [comment]
worked last time i did it on live. - needs testing

**Comment by JunkyBulgaria** [comment]
recoded the spell, should work 100% now
