### ISSUE TITLE
Quest: Venomhide Eggs

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#466]
**Description:**

You cannot pick up any Eggs there.

**Current behaviour:**

I see eggs there (not broken) but you cannot loot them.

**Expected behaviour:**

Make the Eggs lootable.

(Also the you can pick up this quest before the prequest Toxic Tolerance i've done it order but i was able to pick up)

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
need more information, wowhead links, ids, etc
