### ISSUE TITLE
Private Hendel

### ISSUE THREAD

**Issue by balazskvr** [FireFly-WoW/FireFly-IssueTracker#467]
**Description:**

NPC is stuck and 36% HP and evading any form of hostile abilities. (checked 3 times in 1,5 days)

**Current behaviour:**

Probably someone did the quest and logged out or something like that and the NPC is now "unaccessible".

**Expected behaviour:**

Should reset it's position and HP after a while.

**Steps to reproduce the problem:**

IDK, but a server restart would probably fix it.... for a while.

**Screenshots:**

![hendel](https://cloud.githubusercontent.com/assets/25955517/26805723/918937dc-4a4d-11e7-87e7-5aed1fe27cbd.jpg)

**Comment by JunkyBulgaria** [comment]
worked fine for me, needs testing
