### ISSUE TITLE
Dungeon: Halls Of Lightning (Normal): Volkhan Boss

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#47]
**Description:**

* Issue 1: When he runs to his foirge, he runs way to fast.

* Issue 2: He runs to his forge and cast "**Temper**" too offen. - He is supposed to run to his forge at every 20% of his health.

Issue 3 : When you kill Molten Golem and it become Frozen they just desepire. - They are not supposed to desepire, they are supposed to stay there for the whole fight so when he cast  "**Shattering Stomp**" the "frozen goles" shatter for ~5k damage each. 

Issue: 4 : He is not casting:  "**Shattering Stomp**" He is supposed to use it once he has cast "**Temper**"several times.

Source: 

http://wowwiki.wikia.com/wiki/Volkhan / 
http://www.wowhead.com/guides/dungeons/timewalking/halls-of-lightning-strategy-guide

Video: https://www.youtube.com/watch?v=vxu2sfmfaTc

**Comment by frytik** [comment]
Working on it.

**Comment by frytik** [comment]
Issue 1: It's normal speed. I don't see any problem. Can' confirm.
Issue 2: I can' see any problem, work's perfectly, core is set to run to forge on every -20% of health.
Issue 3 and Issue 4 are linked and they are beign fixed.

**Comment by Deathtremor** [comment]
Re-tested.

Issue 1: Seems to work properly now.
Issue 2: Seems to work properly **except** one thing. Currently he runs to his forge first time right after pull (100%/99% HP] He is supposed to run to to his forge when he is about 80%!

**Comment by frytik** [comment]
https://www.youtube.com/watch?v=vxu2sfmfaTc

https://youtu.be/RLcQ825QiJw?t=3m50s

What's the true from that now ? @Deathtremor

**Comment by Deathtremor** [comment]
https://youtu.be/RLcQ825QiJw?t=3m50s is from retail patch 7.x.x. A lot of is different now. You need to look at how things were back then to make it properly balanced. Mixing things how they work now into old patches would't be wise. Not everything would be propely optimazed. ^^

**Comment by frytik** [comment]
@Deathtremor Some video's and wiki's talking about he should cast Shattering Stomp every -20% health, and some wiki's say's it should cast only one time at 20% HP

**Comment by Deathtremor** [comment]
If every wikis's says something different than video from 2008 will not like ^^. I would say it's pretty clear evidence.

**Comment by frytik** [comment]
If you can, please post me clear evidence how it should work one more time please.

**Comment by Deathtremor** [comment]
Oh sorry. You're talking about Shattering Stomp. I was talking about when he is supposed to run to his forge. 

I didn't find exactly when he cast Shattering Stomp. wowiky says he cast it after he run couple of time to his forge.

According to this video he cast it around 20-30% of his hp.

**Comment by frytik** [comment]
@Deathtremor Can you re-test ?

**Comment by Demmye** [comment]
Confirmed on PTR, works perfectly fine now, thanks for the report!
