### ISSUE TITLE
Quest: Scalps!

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#471]
**Description:**

You cannat use the knife on Heb'Drakkar Striker.

**Current behaviour:**

Right now only Heb'Drakkar Headhunter's can be scalped with the knife.

**Expected behaviour:**

Both mobs should work

**Steps to reproduce the problem:**

Get the quest Scalps!
2. Try use the knife on a Heb'Drakkar Striker.
3. Observe

**Screenshots:**

http://imgur.com/a/pHVHZ

**Comment by bassuraaj** [comment]
Tested. Working on Live Realm.
