### ISSUE TITLE
Quest "Overlord"

### ISSUE THREAD

**Issue by Nussbaumerli** [FireFly-WoW/FireFly-IssueTracker#478]
**Description:**

I am unable to accept the Quest "Overlord" in Honor Hold, grey exclamation mark persistent
**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
if its grey then it requires higher level than your current one, needs testing / more information
