### ISSUE TITLE
Quest: A Bear of an Appetite

### ISSUE THREAD

**Issue by thestranger064** [FireFly-WoW/FireFly-IssueTracker#479]
**Description:**

Missing the necessary school of Northern Salmon

**Current behaviour:**

There is no school of Northern Salmon

**Expected behaviour:**

There should be plenty of them

**Steps to reproduce the problem:**

Get the quest A Bear of an Appetite
2. Go to Eastwind Shore
3. Search for school of Northern Salmon and find out they are missing

**Screenshots:**

http://imgur.com/a/4HFZo

**Comment by Tr4dY** [comment]
Still no salmon on ptr

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/fo1k5k

**Comment by bassuraaj** [comment]
Working on Live Realm.
