### ISSUE TITLE
Dungeon: Halls of Lightning (Normal): Hallway with Statues leading out of Volkhan's room

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#48]
**Description:**

In this hallway when you pass one of the thresholds a bunch of statues is supposed to come alive.

Issue 1: When you pass first threshold, too many statues will come to life. = wipe for group

Issue 2: When you pass next thresholds nothing happen. - A bunch of statues is supposed to come alive.

Issue 3: Statutes are not supposed to be targetable.

![wowscrnshot_041617_165110](https://cloud.githubusercontent.com/assets/27430839/25069518/81763164-22c6-11e7-86d6-39c30d759cc7.jpg)

**Comment by frytik** [comment]
Taking it.

**Comment by Demmye** [comment]
Confirmed, it's not that too many statues come alive at first pull, i tested it few times and the statue rate per room varies from 0 to 4 and according to retail footage, it should be 1 to 3 per room. Also, as Deathtremor said, the statues shouldn't be targetable unless activated.

**Comment by frytik** [comment]
Taking it again.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR couple of times. Statues are targetable, though not attackable.
Statue rate per room does vary from 0 to 4.
