### ISSUE TITLE
Quest The Drakkensryd (Can't accept the quest)

### ISSUE THREAD

**Issue by Pmav123** [FireFly-WoW/FireFly-IssueTracker#481]
I accepted the quest the drakkensryd and abandoned it cause i thought it was bugged.
And now i cant retake the quest. So i cant finish the sons of hodir questline :( 
![wowscrnshot_060817_203338](https://user-images.githubusercontent.com/29286859/26945124-20914d5e-4c8b-11e7-9470-0ba8cf7d2bad.jpg)

**Comment by frytik** [comment]
@Siderbas

**Comment by Soockee** [comment]
#386
