### ISSUE TITLE
Princess doesn't patrol

### ISSUE THREAD

**Issue by nfals** [FireFly-WoW/FireFly-IssueTracker#482]
**Description:**

Princess and her two bodyguards do not patrol the Brackwell Pumpkin Patch, but instead remain in place wherever they spawn.

**Current behaviour:**

Princess and her guards stand still after spawning.

**Expected behaviour:**

Princess and her guards should patrol the pumpkin patch.

**Steps to reproduce the problem:**

1. Travel to the Brackwell Pumpkin Patch
2. Look at Princess

**Comment by Shrizz** [comment]
I recall that she doesn't seem to be aggro-linked to her guards either (this was weeks ago I did this quest, mind you, so it may have changed by now). You can pull any of them separately, thus making this quest very trivial. I believe that they should all be linked - pulling any of them should cause all 3 to engage. A minor thing, but hey, it's the little things that make the experience more immersive, no? :)

**Comment by JunkyBulgaria** [comment]
please include more info like wowhead quest links, npc links etc
