### ISSUE TITLE
Bugged NPC. quest - Missing diplomat 

### ISSUE THREAD

**Issue by mayumayux** [FireFly-WoW/FireFly-IssueTracker#483]
**Description:**

Quest can not be completed. 

**Current behaviour:**
Mob is stuck

**Expected behaviour:**
There should be event with Jaina. 

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/jzOTJ

**Comment by balazskvr** [comment]
Duplicate of https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/467
