### ISSUE TITLE
[Quest] Scouring the Desert Quest and Silithyst Geysers Don't Work (Silithus)

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#486]
**Description:**

In Silithus, there is a quest, Scouring the Desert, that asks you to go out and find one of the many Silithyst Geyser objects, loot it, and carry it back to the camp (deliver it to a transporter-like object, similar to the one that takes you to Booty Bay from outside Gnomeregan); however, when you interact with one of the geysers, it despawns and you obtain no Silithyst. Thus, you cannot complete the quest or gain the damage buff from turning it in.

**Current behaviour:**

Silithyst Geysers spawn can can be interacted with; however, they do not give you the Silithyst like they're meant to. Thus, you cannot complete the quest, Scouring the Desert, nor can you turn it in to gain a damage buff or help towards your faction control the zone. As a result, you also can't get the zone-wide rep boost buff from turning in 200 Silithyst.

**Expected behaviour:**

While carrying Silithyst, you should not be able to mount (and still carry it), your movement speed should be reduced to 75% and you cannot be made to go faster by talents, abilities, spells or items. If you mount up, you drop your Silithyst and it turns into a Silithyst Mound. You can simply loot this to pick your Silithyst back up. Note that some people have said that certain abilities can counter this to an extent, but I don't believe that they're meant to. The intention is that you're meant to be slowed to make it more challenging (world PvP risk). Carrying Silithyst also flags you for PvP, however, we're on a PvP realm, so it's on by default in contested zones like Silithus.

Turning in Silithyst has the following effects: -

- You gain a 30-minute 5% damage buff, Traces of Silithyst;
- 1 is added to the counter for your faction in the zone (starts at 0 / 200);
- You gain 20 Cenarion Circle reputation (some say 10; others say 20 - the wiki says 20 so I'll go with this one);
- You gain 19 Honor points;
- When the 200th Silithyst for your faction is turned in, a zone-wide buff, Cenarion Favor, goes into effect. This lasts until the other faction collects 200 Silithyst or until a server restart. This buff gives 25% more Cenarion Circle reputation from kills. It persists through death, fades if you leave the zone, but is re-applied when you re-enter the zone (as long as the other faction hasn't turned in 200 Silithyst or the server hasn't restarted, of course).

**Steps to reproduce the problem:**

1. Go to Silithyst and try to loot a Silithyst Geyser.
2. Observe that it despawns and you get no Silithyst. This means the quest, Scouring the Desert, can't be completed, nor can you get the associated rewards related to Silithyst turn-ins (mentioned above).

**Screenshots:**

N/A

**Sources:**

http://wowwiki.wikia.com/wiki/The_Silithyst_Must_Flow
http://db.vanillagaming.org/?object=181598#wh-comments

**Comment by JunkyBulgaria** [comment]
quest is coded, needs to be tested by with gm mode on PTR
