### ISSUE TITLE
[Quest] Rescue from Jaedenar Quest (Escort) is Bugged

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#488]
**Description:**

The escort quest, Rescue from Jaedenar, in Feralas cannot be completed currently, due a bug.

**Current behaviour:**

The first part of the quest works fine. You can escort the NPC through the caverns to her equipment chest; however, when she reaches it, she gets stuck in a do-nothing state. If you engage in combat near her, she will glitch as if she's trying to come to your aid but won't be able to move from her spot. She returns to her do-nothing state after combat ends.

**Expected behaviour:**

When she reaches her equipment chest, she is meant to change into her gear. Shortly after she has re-armed herself, 3 mobs should spawn and attack (I believe it's 3 of the large blue felguard demons, the ones that are dotted throughout the cavern). After that, she starts making her way back the way you came, heading for the exit (the one with the corrupted green moonwell outside it). When she gets outside, she is attacked by the Spirit of Trey Lightforge. When you kill him, the quest should register as complete and she should despawn soon after (there is probably some script to thank you etc). You can then go hand it in at Jessir Moonbow and continue the quest chain.

**Steps to reproduce the problem:**

1. Go to Jaedenar and acquire the quest, Rescue from Jaedenar (chain from A Strange Red Key);
2. Escort Captured Arko'narin to her equipment chest.
3. Notice that she gets in a bugged state next to it. Thus, the quest cannot be completed.

**Screenshots:**

https://ufile.io/2n04o

**Sources:**

http://db.vanillagaming.org/?quest=5203#wh-comments

**Comment by frytik** [comment]
Fix soon will be applied.
