### ISSUE TITLE
[Quest][Dungeon] The Scepter of Celebras Quest is Bugged (Maraudon)

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#489]
**Description:**

The quest, The Scepter of Celebras, in Maraudon cannot be completed due to a bug.

**Current behaviour:**

When you take the quest, The Scepter of Celebras, from Celebras the Redeemed, the event that ultimately leads to its completion, apparently begins. He begins moving, starts saying dialogue, but then ends up in a stuck state. He seems to keep continuing with his dialogue but the actual event doesn't complete, and so you cannot interact with the book or stone objects, and thus cannot complete the quest. Note that I've only tested this once, so the specifics of the bug might be subject to change. I will get around to testing again soon though and will include a screenshot then, if it's not fixed yet.

**Expected behaviour:**

When you start the quest, Celebras is meant to run over to where the stone is and I believe a book is meant to spawn (the book spawned in my test but you couldn't interact with it). You interact with it and the event continues. Eventually the ritual completes and you can loot the stone to complete the quest and receive your reward.

**Steps to reproduce the problem:**

1. Go to Maraudon.
2. With the pre-quest acquired (Legends of Maraudon) and both halves of the scepter in your possession, kill Celebras to "redeem" him.
3. Speak with Celebras the Redeemed and turn in Legends of Maraudon.
4. Start The Scepter of Celebras quest that is now available.
4. Observe that he gets stuck and the event doesn't complete. Thus, the quest cannot be completed.

**Screenshots:**

None (I will get one if it's still bugged when I next test this; I forgot to take one originally).

**Comment by frytik** [comment]
Bad SAI. Fix will be applied soon.

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. 

Still bugged. He doesn't do the channeling.

**Comment by frytik** [comment]
For me it's working. You need to click on the book.

**Comment by Hardcore-FireFly** [comment]
I will try it again tonight and let you know about it.
