### ISSUE TITLE
 The Drakkensryd  Quest bugged

### ISSUE THREAD

**Issue by hotshot1992** [FireFly-WoW/FireFly-IssueTracker#492]
**Description:**

When i first took quest, the npc didnt give me the drake as it should give i went for the quest i thought i missed to click on drake so i abandon to retake it. The Quest giver then was not giving the quest  The Drakkensryd  

**Current behaviour:**

The current stage is i am stucked there cant take that quest as it is long chain quest for son of hordir

**Comment by frytik** [comment]
Fix applied soon.

**Comment by frytik** [comment]
Works for me.
