### ISSUE TITLE
[NPC] Franclorn Forgewright

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#494]
This NPC is the one that gives the quest for the Shadowforge Key which is used to open some of the doors in Black Rock Depth.

The issue with this NPC is that you should only be able to see him when you are dead. However on Firefly, you are able to see him even when you are alive.

**Comment by frytik** [comment]
Fix applied.

**Comment by philoudu16** [comment]
Fixed on PTR.

**Comment by Hardcore-FireFly** [comment]
Fixed on PTR.
