### ISSUE TITLE
[Item][Dungeon] Missing Item: Frostwhisper's Embalming Fluid (Scholomance)

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#495]
**Description:**

Inside the Scholomance dungeon, near Ras Frostwhisper, there is an object, Frostwhisper's Embalming Fluid which, when looted, is meant to give you 1x Frostwhisper's Embalming Fluid. Currently, the object is empty when looted.

https://wotlk-twinhead.twinstar.cz/?object=175965

On a side note, I remember having this item from retail in my bags during WotLK so I know with absolute certainly it should be there. You do not need to have the associated crafting-related quest in your log to be able to loot the item; it's just treated as a regular item. It just happens to be missing currently.

**Current behaviour:**

The game object, Frostwhisper's Embalming Fluid, is empty and doesn't give you the item it's meant to (of the same name).

**Expected behaviour:**

Looting the object should give you 1x Frostwhisper's Embalming Fluid.

https://wotlk-twinhead.twinstar.cz/?item=12736

**Steps to reproduce the problem:**

1. Go into Scholomance.
2. Go to Ras Frostwhisper's room and loot the Frostwhisper's Embalming Fluid object. It should be on the left as you face the boss from the entrance, near him.
3. Observe that it's empty.

**Screenshots:**

None (I can get one when I go in again; autoloot was on and I wasn't expecting it to be missing).

**Comment by JunkyBulgaria** [comment]
object is spawned at coords: http://prntscr.com/fnh87z

**Comment by Hardcore-FireFly** [comment]
Tested on PTR. Confirmed. Using the item will only make it disappear. No loot.
