### ISSUE TITLE
[Item] Oozing Bag Drop Table is Missing Coin

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#497]
**Description:**

The item, Oozing bag, doesn't always give you items and has yet to yield any coin either. You should always, at the very least, get a couple of silver (up to around 20, but typically around 10) from this bag, and usually either some lower level potions and/or herbs. Rarely, it contains a Disgusting Oozeling pet.

https://wotlk-twinhead.twinstar.cz/?item=20768

**Current behaviour:**

When you open an Oozing Bag, it is sometimes empty. I'm guessing this would be the case when you receive no items and it should just only give coin; however, since no coin is being awarded, in the scenario where you receive no item when you open the bag, it will appear as completely empty. While it _appears_ that the item side of the loot table works, the fact that the coin is missing makes me hesitant to farm this for the pet, as it could be missing. This is reinforced by the fact that several other pets are missing from the game, although the ones in question are from lootable objects in the world (will make another issue for that after this).

While you're at it, can you also check other bags like Slimy Bag, as I believe they are also similarly bugged, although the coin amount from lower level bags should be far lower.

**Expected behaviour:**

The Oozing Bag should never be empty; it should contain, at the very least, some silver (around 5-20 if memory serves, and based on comments I could find on database sites). It should also be possible to acquire multiple items in the bag, for example, some Greater Healing Potions can appear along with Greater Mana Potions; they aren't exclusive. I don't know the specifics of all the loot groupings, but I'm not aware of any exclusions. The drop rates for any particular item is somewhat low, which does explain why a lot of the bags I've opened have been empty (they should have contained coin).

**Steps to reproduce the problem:**

1. Acquire some Oozing Bags (kill Living Decay in Eastern Plaguelands, for example).
2. Open the bags.
3. Observe that you don't get coin and they're sometimes totally empty (usually, in my experience).

**Screenshots:**

None (I can get some when I next acquire some bags).

**Comment by JunkyBulgaria** [comment]
loot seems to be fine, needs testing http://prntscr.com/fnh8rw
