### ISSUE TITLE
Im a crow

### ISSUE THREAD

**Issue by jfreky** [FireFly-WoW/FireFly-IssueTracker#499]
**Description:**
In zangar marism, in the quest "as the crow flies", when Ysiel windsingger give you a item to transform in a crow to fly around the lake, you retunr but your form not, i relogged, close the game and open it again but not works...
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://subefotos.com/ver/?cf25234922d46374c38f674e67db4c29o.jpg
url...
url...

**Comment by JunkyBulgaria** [comment]
duplicate, whenever you die the morph will be removed
