### ISSUE TITLE
Pathfinding in Deadmines need polishing!

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#5]
Pathfinding need polishing!

When i pulled some mob(s) and jumped from ledge they went straight towards me (flying in the air) instead of trying to find a proper path. Also they sometimes went through texture. 

Mobs always should find a proper path towards you no matter what.

**Comment by JunkyBulgaria** [comment]
Hello and thanks for your report, can you include screenshot where exactly it happened?

**Comment by Deathtremor** [comment]
It happened in all over Ironclad Cove. 
![wowscrnshot_041417_005810](https://cloud.githubusercontent.com/assets/27430839/25010568/1da51f40-209d-11e7-8ff4-63e5a54ce675.jpg)

**Comment by JunkyBulgaria** [comment]
It worked fine for me, pm me once you are ingame or in discord "LucifeR" -discord / "Luciferr" -ingame

**Comment by JunkyBulgaria** [comment]
Should be working as intended now, once you jump off the platform they will evade.

**Comment by Deathtremor** [comment]
Ok confirmed.
