### ISSUE TITLE
Character creation, undead's lower jaw invisible

### ISSUE THREAD

**Issue by Moshtash** [FireFly-WoW/FireFly-IssueTracker#50]
**Description:**

CHANGEME: In character creation, try creating an undead character, one of the cosmetic features deletes the undead's jaw.

**Current behaviour:**

CHANGEME: Undead's jaw becomes invisible.

**Expected behaviour:**

CHANGEME: Supposed to see the jaw

**Steps to reproduce the problem:**

1. In character creation, select undead.
2. Cycle through "Features", one of them will delete the undead's jaw

**Screenshots:**

![wowscrnshot_041617_195946](https://cloud.githubusercontent.com/assets/27637301/25073135/26d10af8-22e0-11e7-8d19-54ac6bb803be.jpg)

**Comment by JunkyBulgaria** [comment]
This is a client issue from your custom mpq patches for word models, not releated to the server.

**Comment by Moshtash** [comment]
Okay my bad
