### ISSUE TITLE
[Quest]Gods like Shiny Things

### ISSUE THREAD

**Issue by Condrios** [FireFly-WoW/FireFly-IssueTracker#500]
**Description:**

**ID info**
Sholazar Basin: zone=3711
Item to summon Lafoo: item=38622
Lafoo(Quest Start npc): npc=28120
Quest: quest=12572
lootable item (6): item=38575
High-Oracle Soo-say(Quest Endsnpc) npc=28027

Gods like Shiny Things is a quest located in Sholazar Basin and is a part of the chain to start the Reputation farm for Frenzyheart or Oracle. You search for sparkling dots in the area where Lafoo can dig up a questitem (6 pieces)

**Current behaviour:**
No questitem is been found by Lafoo (visual lootable)

You walk around and Lafoo is jumping behind you. When approaching a sparkling dot, Lafoo walks towards it and start digging + giving his talk about it. He digs up something (2 options)
- critter (what is normal since the questitem "Shiny Treasures" isn't 100% found on retail either)
- Nothing ... i think this should be the questitem "Shiny Treasures" but nothing appears in game to loot.

**Expected behaviour:**
Lafoo should always found something: Critters or the questitms "Shiny Treasures"

You walk around and Lafoo is jumping behind you. When approaching a sparkling dot, Lafoo walks towards it and start digging + giving his talk about it. He digs up something 2 options
- critter (what is normal since the questitem isn't 100% found on retail either)
- Questitem "Shiny Treasures"

**Steps to reproduce the problem:**

1. Summon Lafoo in Sholazar Basin by clicking on "lafoos-bug-bag" you gain in the questline
2. Accept Quest: Gods like Shiny Things
3. Walk around in Sholazar basin at the correct questlocation and get close to the sparkling dots on the ground.
4. Wait for Lafoo to interact and see what he digged up.
5. Redo multiple times to see various loots (critters and currently nothing (should by questitem "Shiny Treasures")

**Screenshots:**
will follow
url...
url...
url...

**Comment by sarlic1337** [comment]
I had problems with that Quest too but there is only 1 Minorbug and that is the Spawntime between "finding" the Shiny Thing and the Spawn of the Gameobject that can be looted.

To complete this Quest:
- Use Lafoo on the Shiny Objects
- Remeber where u did that
- Come back in about 2-3 Minutes (to the places with the Shiny Critters)
- Loot all spawned objects.

**Comment by Condrios** [comment]
indeed works with delay 

shorten the spawn time to instant?

**Comment by frytik** [comment]
Can be closed ?

**Comment by Condrios** [comment]
i don't need to do the quest again so it is ok to close is, ... but the issue isn't solved for other players.
If you can shorten the time to instant instead of after 1-2-3 minutes it is all solved.
you may close this
