### ISSUE TITLE
[class talent] Hunter

### ISSUE THREAD

**Issue by mayumayux** [FireFly-WoW/FireFly-IssueTracker#501]
**Description:**

Hunter Talent Longevity doesnt lower Bestial Wrath behavior

**Current behaviour:** does nothing

**Expected behaviour:**
Lower BW CD to 1.4 min at 3 points.

**Comment by mayumayux** [comment]
Please fix it ASAP. Its a very very crucial talent. Tooltip says its 1.4min as per 3/3 Longevity, but in fact it's still 2 min.

**Comment by frytik** [comment]
Tested by me, working.

**Comment by frytik** [comment]
If no confirmation comes in 3 days, then i will close that issue.
