### ISSUE TITLE
Goblin Engineer

### ISSUE THREAD

**Issue by Bonlaw** [FireFly-WoW/FireFly-IssueTracker#502]
**Description:**

I am lvl 47 with Engineering 300 and want to take Goblin Engineering but can't seem to start the quest line

**Current behaviour:**

All NPCs that should give the quest simply don't have it for me, but I can take a quest from Oglethorpe in Booty Bay, I have visited Undercity and Ratchet but none of them have the quest.

**Expected behaviour:**

I should be able to obtain the Goblin engineering quets line from Tinkerwiz (Ratchet) or any of the capital engineering trainers

**Steps to reproduce the problem:**

1. Step 1 Be a lvl 30+ engineer with 200+ lvls in engineering
2. Step 2 Go to Tinkerwiz or any other capital city engineer trainer
3. Step 3 Quest should appear or not

**Comment by JunkyBulgaria** [comment]
should be working
