### ISSUE TITLE
Quest [Finding the Phylactery] 

### ISSUE THREAD

**Issue by davidup111** [FireFly-WoW/FireFly-IssueTracker#503]
Hello FireFly team!

I find a bug in Borean Tundra. [Finding the Phylactery] mission can not be done, because the dust is missing in the pull. Hear some screenshot. If you see I wait close 10 miute but is don't respawned. 

**Screenshots:**
![wowscrnshot_061417_160220](https://user-images.githubusercontent.com/29010880/27137279-c7770870-511d-11e7-9866-a81a2bb5cc6d.jpg)

![wowscrnshot_061417_161042](https://user-images.githubusercontent.com/29010880/27137294-d4ca6aa8-511d-11e7-8d19-bba68e4b1a28.jpg)

Thank you for your response

**Comment by Shrizz** [comment]
I've heard numerous people complain about this over the past few weeks. Might be one of those ones that only respawn on a server restart. :(

**Comment by frytik** [comment]
Fix will be applied soon.

**Comment by bassuraaj** [comment]
Not working on Live realm. The Item which should be underwater, but It's not here. (image of Item from Wowhead)
![261255-finding-the-phylactery](https://user-images.githubusercontent.com/29519573/27983515-9052455a-63db-11e7-91b8-cdde9c4b1292.jpg)
