### ISSUE TITLE
The Ghostfish

### ISSUE THREAD

**Issue by PiotrSzejna** [FireFly-WoW/FireFly-IssueTracker#504]
**Description:**

http://www.wowhead.com/quest=13830/the-ghostfish

**Current behaviour:**

It took me 2h of fishing and no phantom ghostfish

**Expected behaviour:**
When you take quest, fish should be possible to be fished, but it's like it doesn't exist and it's impossible to fish it

**Comment by sarlic1337** [comment]
Use Searchfunction. There is already a entry about all Fishdailys.
