### ISSUE TITLE
Quest: Evil Draws Near

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#505]
**Description:**

CHANGEME: Describe the issue here

The Dragon not appears if you use the item

CHANGEME: Explain to us (if/how) it currently works.

So at the moment the item works and it uses  the 20 Doom Skulls but the dragon not appears after that but uses all the 20 Skulls.

CHANGEME: Explain to us how the issue is supposed to work.

Well yeah the dragon should appear after you used the item.

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by frytik** [comment]
Fix will be applied soon.

**Comment by Tr4dY** [comment]
Confirm fixed on PTR

**Comment by bassuraaj** [comment]
Working on Live Realm.
