### ISSUE TITLE
Quest: A Spirit Ally?

### ISSUE THREAD

**Issue by Nagykiraly** [FireFly-WoW/FireFly-IssueTracker#506]
**Description:**

You cannot use the item on the correct spot at the stairs

**Current behaviour:**

Nothing happens if you use it.

**Expected behaviour:**

Huh for this i'm not sure i dont really remember for this quest but shomething should appear.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by sarlic1337** [comment]
For me I remember that Quest working as I leveled

**Comment by JunkyBulgaria** [comment]
should be working

**Comment by bassuraaj** [comment]
It is working the only glitch here is as per wowhead you need to stand in between third stair(red marked) but at our server we need to stand up the stair (where I'm standing). So considered It's working on Live realm.
![ss](https://user-images.githubusercontent.com/29519573/27983439-c475a310-63d9-11e7-88d2-afe19e95a3f2.jpg)
