### ISSUE TITLE
Venomhide Eggs

### ISSUE THREAD

**Issue by Bonlaw** [FireFly-WoW/FireFly-IssueTracker#508]
**Description:**

For the quest Venomhide Eggs in Un'goro, you need to collect eggs but while the eggs are present, they are not interactables.

**Current behaviour:**

Can't interact with eggs, they are no entities

**Expected behaviour:**

Eggs should be interactable entities for collection

**Comment by JunkyBulgaria** [comment]
should be working

**Comment by Tr4dY** [comment]
Confirmed working now.

**Comment by bassuraaj** [comment]
Working on Live Realm.
