### ISSUE TITLE
Utgarde Pinnacle(hc)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#51]
**Description:**
Skadi can be taken to the target in the first phase and damage from the cannon can not be displayed. In the second phase, the dragon simply disappears.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Skadi_the_Ruthless

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/VIB1a
http://imgur.com/a/y76EP
url...

**Comment by JunkyBulgaria** [comment]
Works as intended, 2+ players required http://prntscr.com/exe6wi
