### ISSUE TITLE
Instructor Razuvious (25 man)

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#510]
There should not be any orbs of domination on the 25 man version of this encounter. At the moment there are two orbs.
http://wowwiki.wikia.com/wiki/Instructor_Razuvious
"In the 10-man version these understudies can be mind-controlled through the Orbs of Domination by the stairs; a 25-man raid will have to bring enough priests to mind-control them directly."

**Comment by philoudu16** [comment]
Fixed on PTR.

**Comment by Tr4dY** [comment]
Yep it's ok on PTR

**Comment by Hardcore-FireFly** [comment]
Fixed on PTR.
