### ISSUE TITLE
[Item/Quest][World Event] Midsummer Quest/Item Issue with Torches

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#512]
**Important:** Due to the short time window for Midsummer, it would be nice if this was treated as high-priority, because it will take another year for it to become available again and thus get the associated achievements, if this issue isn't fixed.

**Description:**

The Unlit Torches you get for the quest, Torch Catching, doesn't seem to do anything. You cannot complete the quest as a result. This also prevents getting access to the daily quest and throwing torches, both needed for achievements.

**Current behaviour:**

Nothing happens when you get near the bonfire like you're meant to. If you're not close enough, you get an error message about requiring the bonfire (even if you're right on top of it) but when you get close enough and use it, it changes to a different message (you can't do that yet).

**Expected behaviour:**

I believe it's meant to cause a torch to spawn and be thrown into the air, and you're supposed to catch it as part of the quest. If you catch it (stand under it as it lands), it will re-launch itself in a random direction behind you and to a random height, and this continues until you fail to catch it. Catching 4 in a row grants quest completion credit.

**Steps to reproduce the problem:**

1. Acquire the Torch Catching quest during Midsummer (on for the next 2 weeks).
2. Go to the bonfire and use the Unlit Torches.
3. Observe the nothing happens.

**Screenshots:**

1) https://ufile.io/yarh3 (being too far from bonfire with error message)
2) https://ufile.io/05qpd (being close enough yet still getting another, different error message)

**Comment by frytik** [comment]
Fix will be applied soon.

**Comment by Shrizz** [comment]
Thank you. Keep up the good work :)

**Comment by sarlic1337** [comment]
Still got the same problem. Same Error Messages as described above.

**Comment by philoudu16** [comment]
Still an issue on PTR.
