### ISSUE TITLE
[Item/Quest][World Event] Twilight Correspondence Item Not Dropping (Midsummer)

### ISSUE THREAD

**Issue by Shrizz** [FireFly-WoW/FireFly-IssueTracker#513]
**Important:** Please treat this as high-priority due to the limited time window of the Midsummer World Event.

**Description:**

The item, Twilight Correspondence, for the quest, Unusual Activity, doesn't seem to be dropping. It's meant to be a guaranteed drop on the quest, but having cleared the camp, no mob dropped it. The mobs also seem to have a rather long respawn timer, instead of ~5 minutes.

**Current behaviour:**

Twilight Correspondence seems to be missing from the game; it's not dropping like it should. It should be a guaranteed drop from any of the 3 applicable mobs when you're on the quest, Unusual Activity. Additionally, the mobs seem to have an unusually long respawn timer. I cleared the camp twice and both times zero drops. This is not how it should be.

**Expected behaviour:**

Twilight Correspondence should be a 100% drop rate when you're on the quest, Unusual Activity. The 3 mobs that can drop it should also have ~5 minute respawn timer, but currently it's a lot longer. More like 10 minutes.

**Steps to reproduce the problem:**

1. Acquire the quest, Unusual Activity.
2. Kill the mobs at the Twilight Hammer camp in Ashenvale at the Zoram Strand.
3. Observe no drop.

**Screenshots:**

N/A

**Comment by frytik** [comment]
Fix will be applied soon.

**Comment by Shrizz** [comment]
Thank you :) I also put info in that Feralas ticket someone made. Basically, the bonfire is missing so you can't complete the achievement for honoring all the Kalimdor flames.

**Comment by philoudu16** [comment]
Check out that issue, it's not missing, you're just looking in the wrong place ;)

**Comment by philoudu16** [comment]
Fixed on PTR.
