### ISSUE TITLE
quest bug

### ISSUE THREAD

**Issue by mazzda3000** [FireFly-WoW/FireFly-IssueTracker#517]
**Description:**A quest in Terrorkar Forest called "Evil Draws Near" doesn't turn in once completed. 

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url... http://imgur.com/4YHvxc9
url...
url...

**Comment by frytik** [comment]
Working on it as high priority, because more quest's can't be turned in

**Comment by Hardcore-FireFly** [comment]
Confirmed. Quest can't be turned in after it's completed. It acts like the quest item is not present in your inventory.

**Comment by frytik** [comment]
Are you tested it on PTR or where ?

**Comment by frytik** [comment]
Because i can normally turn quest.

**Comment by Hardcore-FireFly** [comment]
Yes I tested that on PTR.
