### ISSUE TITLE
Naxxramas teleporter to Sapphiron

### ISSUE THREAD

**Issue by philoudu16** [FireFly-WoW/FireFly-IssueTracker#518]
Once you have cleared all four wings, you should get teleported to Sapphiron when standing on the center part of the instance.
It doesn't happen on 10 man or 25 man and we need help of a GM every time we do naxxramas.

**Comment by JunkyBulgaria** [comment]
worknig on a hotfix

**Comment by Hardcore-FireFly** [comment]
As of now, you can be teleported to **Frostwyrm Lair** regardless of the fact that you may have not cleared the 4 wings.
There should also be an orb to get teleported to **Frostwyrm Lair** and back.
