### ISSUE TITLE
Icecrown arena getting completed automatically.

### ISSUE THREAD

**Issue by bassuraaj** [FireFly-WoW/FireFly-IssueTracker#519]
**Description:**
In Icecrown arena questchain, Im just dieing by hands of mob and not releasing the corpse until he despawn and my quest getting completed. 
CHANGEME: Describe the issue here

**Current behaviour:**
It's getting completed without killing Enemy.
CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**
It should not get completed if you died in battle.
CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by frytik** [comment]
Can you give link to chain /Wowhead/ ? @bassuraaj

**Comment by bassuraaj** [comment]
@frytik here you go http://www.wowhead.com/quest=13213/battle-at-valhalas

**Comment by Hardcore-FireFly** [comment]
Confirmed. If you die and wait till the opponent despawns, the quest gets automatically completed.
