### ISSUE TITLE
Sunwell

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#52]
**Description:**
The boss for the fight never uses the ability of "Spectral Realm", which is required for his murder.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Kalecgos_(tactics)

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/4A4U6
url...
url...

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/exe0v7 Works as intended, you need 2+ players for it.
