### ISSUE TITLE
Stonetalon Mountains quest credit not working

### ISSUE THREAD

**Issue by Okktopod** [FireFly-WoW/FireFly-IssueTracker#520]
**Description:**

Quest item for the quest "Boulderslive Ravine" taken from Mor'rogal in Sun Rock Retreat isn't registering

**Current behaviour:**

I have all 10 quest items but cannot "continue" the quest to complete it

**Expected behaviour:**

The "continue" button should not be grayed out since i have the required quest item and the required quantity

**Screenshots:**

url...
url...
url...
![screenshot_1](https://user-images.githubusercontent.com/18753895/27553993-50f26e9e-5aad-11e7-9569-42c8e5cb4d63.png)

**Comment by Condrios** [comment]
worked fine for me.
delete q and take q again, perhaps items even stay in your bag and you can turn in.
common bug on private server

**Comment by frytik** [comment]
It can be, like bad packet sending, about quest status.

**Comment by frytik** [comment]
https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/517
