### ISSUE TITLE
Grunt Ragefist

### ISSUE THREAD

**Issue by Bonlaw** [FireFly-WoW/FireFly-IssueTracker#521]
**Description:**

I did the quest objectives for both her quests ''Put them to rest' and 'The honored dead' but I can't complete them, she has no dialogue

**Expected behaviour:**

She should have dialogue to complete the quests.

**Steps to reproduce the problem:**

1. Step 1 Accept quests
2. Step 2 Complete objectives
3. Step 3 Can't complete

**Comment by frytik** [comment]
https://github.com/FireFly-WoW/FireFly-IssueTracker/issues/517

**Comment by Hardcore-FireFly** [comment]
Both quests working fine on PTR.

Also did both on live realm back then when I was leveling my own character.

For **[Put Them To Rest](http://www.wowhead.com/quest=11594/put-them-to-rest)** you just need to kill the spirits.

For **[The Honored Dead](http://www.wowhead.com/quest=11593/the-honored-dead)** you just need to use the quest item on dead bodies.

**Comment by frytik** [comment]
Because fix was pushed +1 :)
