### ISSUE TITLE
We Strike!

### ISSUE THREAD

**Issue by Bonlaw** [FireFly-WoW/FireFly-IssueTracker#522]
**Description:**

Quest bugged, ovjective completed, can't turn in quest

**Current behaviour:**

After completing the objectives, he still just yells at you

**Expected behaviour:**

Should be able to complete quests when objective is completed

**Steps to reproduce the problem:**

1. Step 1 accept quest
2. Step 2 complete objective
3. Step 3 can't complete

**Comment by Hardcore-FireFly** [comment]
I remember doing this quest on my main on live realm. As soon I accepted the quest, the quest-giver started the event and I finished it with no trouble.
