### ISSUE TITLE
25 Man global Raid issue

### ISSUE THREAD

**Issue by Condrios** [FireFly-WoW/FireFly-IssueTracker#527]
**Description:**

Summary 25man raids

**Current behaviour:**
different errors in 25 man raids
there is perhaps already a post about this but i make summary here

Test done on server and PTR

25 KT => only dropping 1 x head token and no 226lvl items

OS => OS 3D only dropping 213 lvl items. Means he only drops loot that is equal to 1D
OS => 0 Valor tokens 
OS => Bags => 1 Heroism emblem

EoE => drops 1 Valorous Dreadnaught Legguards, No token, no 226 items
EoE => can't exit on drake

Summary, 226 not dropping, Valor tokens incorrect, EoE drop wrong

i'm not sure about the amount of armor tokens per kill

**Comment by JunkyBulgaria** [comment]
> 25 KT => only dropping 1 x head token and no 226lvl items
Fixed.


OS => OS 3D only dropping 213 lvl items. Means he only drops loot that is equal to 1D
OS => 0 Valor tokens
OS => Bags => 1 Heroism emblem

EoE => drops 1 Valorous Dreadnaught Legguards, No token, no 226 items
EoE => can't exit on drake

Summary, 226 not dropping, Valor tokens incorrect, EoE drop wrong

**Comment by Hardcore-FireFly** [comment]
Tested all NR Raids (except for VoA) on PTR. Here are the results :

**OS 10/25 - X Drakes** : Sartharion should drop 2x EoH (10man) / 2x EoV (25man) + 1 emblem for each of the drakes left alive and killed during the encounter. But he's dropping only 2 emblems.

**Naxx 10** : All encounters seem to be fine regarding loot-table and emblems.

**Naxx 25** : The only issue was the Four Horsemen Chest which is supposed to drop EoV, but it's giving EoH instead.

EoE 10/25 : Everything seemed to be alright.

**Comment by JunkyBulgaria** [comment]
all above fixed
