### ISSUE TITLE
Gammoth 

### ISSUE THREAD

**Issue by Tr4dY** [FireFly-WoW/FireFly-IssueTracker#528]
**Description:**

Weakened gammoth magnataurs huntress deals 1 damage per strike.

**Expected behaviour:**

They should deal high damage as elite and average damage (probably around 150 per melee strike) as normal. 

Combat log copypasta : 

Weakened Magnataur Huntress casts Tusk Strike at Tradyz.
**Weakened Magnataur Huntress's Tusk Strike hits Tradyz for 1 Physical.**
Weakened Magnataur Huntress suffers 115 Holy damage from Tradyz's Righteous Vengeance.
**Weakened Magnataur Huntress's melee swing hits Tradyz for 1 Physical.**

**Comment by Hardcore-FireFly** [comment]
Confirmed (PTR).

Weakened version of the mobs deal 1 physical damage per hit.
