### ISSUE TITLE
Reclusive Runemaster

### ISSUE THREAD

**Issue by Tr4dY** [FireFly-WoW/FireFly-IssueTracker#529]
**Description:**

NPC is not attacking

**Current behaviour:**

If you engage Dregmar Runebrand, you can attack him and he won't defend

**Expected behaviour:**

CHANGEME: The enemy should attack you.

**Steps to reproduce the problem:**

Get to Dragonblight, in a cave between Venomspite and Wintergarde keep, and engage the NPC.
It should be a strong lvl 74 elite magnataur who hits for 1+k

**Screenshots:**

http://i64.tinypic.com/rvw0uq.jpg

As you can see on my combat log : no attacks

**Comment by Hardcore-FireFly** [comment]
Works fine on PTR :

http://oi63.tinypic.com/2rr81g3.jpg

Though back on main realm when I was lvling, I encountered the same situation.
