### ISSUE TITLE
Blackrock Spire.

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#53]
**Description:**
There is an opportunity to skip this boss, as well as no waves of mobs and after the time the boss does not descend into the room.

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wow.gamepedia.com/Rend_Blackhand_(tactics)
**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/o8uRf
url...
url...

**Comment by JunkyBulgaria** [comment]
You are testing as level 80 - most mobs ignore you, it works fine if you are the level for the dungeon.

**Comment by Fearevius** [comment]
Mobs and the boss must spawn independently of the level of the player and the door to the last dungeon boss must be closed.

**Comment by JunkyBulgaria** [comment]
Closed as it should be working now, if there are any issues feel free to reply here.
