### ISSUE TITLE
 Blackwing Lair

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#54]
**Description:**
Razorgore the Untamed - When you try to break an egg, the player is given a debuff, no mobs appear, and the boss has an immune to magical and physical damage.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://wowwiki.wikia.com/wiki/Razorgore_the_Untamed

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/CBDuJ
http://imgur.com/a/uRFd1
url...

**Comment by JunkyBulgaria** [comment]
Encounter works as intended. http://prntscr.com/exdqun

Player "CAN NOT" break eggs, the controlled boss does.
Adds spawn as intended.
You "CAN NOT" kill the boss unless you destroyed their eggs.

**Comment by Fearevius** [comment]
Sorry for my english. The boss must be able to kill, but if there is at least one whole egg - after the death of the boss whole eggs explode, killing the raid. And I for some reason, using the ability to "destroy the egg" hung debuff, which is seen in the first screenshot.

**Comment by Fearevius** [comment]
Columns do not work.
http://imgur.com/a/VHeCO

**Comment by JunkyBulgaria** [comment]
make a new issue for this report please
