### ISSUE TITLE
Dk last quest orgrimmar teleport 

### ISSUE THREAD

**Issue by Crinia** [FireFly-WoW/FireFly-IssueTracker#55]
**Description:**
well the last quest for death knight to teleport in orgrimmar to be part of horde don't work well
CHANGEME: Describe the issue here
the orgrimmar teleprot doens't work no matter how many times u click or relog 
**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.
well when u click on portal u shall be insta teleported to orgrimmar to go thrall and complete the quest 
**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
I tested it and it worked for me, need confirmation from more people.

**Comment by frytik** [comment]
I tested it too and it worked for me.
