### ISSUE TITLE
Complete list of mobs that were changed to neutral in patch 3.3

### ISSUE THREAD

**Issue by svedizz** [FireFly-WoW/FireFly-IssueTracker#56]
**Description:**

These mobs are neutral in 3.3.

**Current behaviour:**

Same as description tells you.

**Expected behaviour:**

They are all supposed to be aggressive pre-3.3.

**Links**

http://db.vanillagaming.org/?npc=3101
http://db.vanillagaming.org/?npc=3102
http://db.vanillagaming.org/?npc=3183
http://db.vanillagaming.org/?npc=1505
http://db.vanillagaming.org/?npc=1688
http://db.vanillagaming.org/?npc=2952
http://db.vanillagaming.org/?npc=2954
http://db.vanillagaming.org/?npc=2953
http://db.vanillagaming.org/?npc=8554
http://wowwiki.wikia.com/wiki/Arcane_Wraith
http://wowwiki.wikia.com/wiki/Tainted_Arcane_Wraith
http://www.wowdb.com/npcs/15367-felendren-the-banished
http://wowwiki.wikia.com/wiki/Blood_Elf_Scout
http://wowwiki.wikia.com/wiki/Surveyor_Candress
http://wowwiki.wikia.com/wiki/Webwood_Spider
http://wowwiki.wikia.com/wiki/Frostmane_Troll_Whelp
http://wowwiki.wikia.com/wiki/Frostmane_Novice
http://wowwiki.wikia.com/wiki/Grik'nir_the_Cold

**Comment by svedizz** [comment]
You've already changed the Defias Thug and Garrick Padfoot which I made a report of earlier.

**Comment by JunkyBulgaria** [comment]
yeah, thanks a lot! :)

**Comment by JunkyBulgaria** [comment]
Fix applied

**Comment by svedizz** [comment]
I noticed this mob is still pasive: http://wowwiki.wikia.com/wiki/Surveyor_Candress

**Comment by JunkyBulgaria** [comment]
done

**Comment by svedizz** [comment]
These changed have all been changed back to their previous state, why?

**Comment by JunkyBulgaria** [comment]
Affected rows: 0  Found rows: 0  Warnings: 0  Duration for 1 query: 0.002 sec. 

the reported ones are set to hostile, if there are more to add feel free to do it
