### ISSUE TITLE
Warlock Pet

### ISSUE THREAD

**Issue by Plantfusion** [FireFly-WoW/FireFly-IssueTracker#59]
**Description:**

Warlock send pet to attack the monster. Once the pet attack the mob, the mob get to the caster immediatly instead of attacking the pet. I want to precise that my warlock did not attack the mob yet.

**For now it only happens with Greater Plainstrider monster.

**Expected behaviour:**

Should be attacking the warlock pet and getting aggro.

**Comment by svedizz** [comment]
Define "Warlock Pet". I'm assuming you're referring to the voidwalker in which case you need to enable its ability "Suffering".

**Comment by Plantfusion** [comment]
Sorry I was using Imp at that time. I will do further test once I get back home.

**Comment by JunkyBulgaria** [comment]
You used the Imp ability called "Phase Shift" which will make it invisible and the mob will attack warlock instead.
