### ISSUE TITLE
path

### ISSUE THREAD

**Issue by rayes93** [FireFly-WoW/FireFly-IssueTracker#6]
when i was in some instances today, wotlk and bc ones with the speed modifier i pulled much trash mobs that chased me tru walls and air , not going on the paths t\hat are ment to be _

**Comment by masterfireyy** [comment]
"with the speed modifier" --> do it without and it will be like a wonder :) 

Please test with normal speed like in the release date.

**Comment by JunkyBulgaria** [comment]
Please open another issue and use the form for issues.
