### ISSUE TITLE
Ruins of Ahn'Qiraj 

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#60]
**Description:**
Missing npc - Lieutenant General Andorov
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://www.wowhead.com/npc=15471/lieutenant-general-andorov
**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

url...
url...

**Comment by JunkyBulgaria** [comment]
he is now spawned
