### ISSUE TITLE
Temple of Ahn'Qiraj

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#61]
**Description:**
Missing boss - Ouro
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
http://www.wowhead.com/npc=15517/ouro

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/ZMmyb
url...
url...

**Comment by JunkyBulgaria** [comment]
You must defeat the Twin Emperors and clear through the trash afterwards to reach Ouro. It is not required that you defeat C'thun first.

Information about this fight can be found at http://www.wowwiki.com/Ouro_the_Sandworm

**Comment by Fearevius** [comment]
The emperors are dead, but and what mobs do you say?

**Comment by JunkyBulgaria** [comment]
all the trash mobs in the cave

**Comment by JunkyBulgaria** [comment]
closing as it works
