### ISSUE TITLE
Broken damage to battle pets

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#62]
**Description:**
Broken damage to battle pets
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
idk, but the damage dealt should be much higher

**Steps to reproduce the problem:**

1. 
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/7rn2w
url...
url...

**Comment by JunkyBulgaria** [comment]
include npc id, name etc

**Comment by Fearevius** [comment]
No, it's not normal. Can not pet 80ur, do 50 damage on a 19ur moor. And it's not only in this pet, but in all.

**Comment by JunkyBulgaria** [comment]
It might be 80 but the item and formula is for 60

**Comment by Fearevius** [comment]
This is not entirely correct proof, but - https://www.youtube.com/watch?v=E2j4ly2OAgY
