### ISSUE TITLE
Mannequin to krasus

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#68]
**Description:**

CHANGEME: Describe the issue here
Mannequin to krasus

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
Should not be standing there
**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/vQAz0
url...
url...

**Comment by JunkyBulgaria** [comment]
it's for the beta only
