### ISSUE TITLE
Naxxramas(25)

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#69]
**Description:**
1. Patchwerk - Mobs do not attack if they attack the boss.
2. Instructor Razuvious - No control crystals.
3. 4 Horsemen - Unable to open chest.
4. Missing teleportation crystal.

CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
1. If you attack the boss without killing all the mobs, they also attack the raid.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/s1CGy
http://imgur.com/a/2eubR
http://imgur.com/a/PtVNU
http://imgur.com/a/Jo1vn

**Comment by JunkyBulgaria** [comment]
2) works http://prntscr.com/ey90mu

**Comment by Fearevius** [comment]
If you have time, please check the mode for 25 ppl. I had 100% no crystals and no chest opened.

**Comment by JunkyBulgaria** [comment]
There is no such thing as "crystal", you get automatically teleported once you reached the 2nd level, the "crystal" you talk about is an orb at Frostwyrm lair. However, the issue has been fixed now. About the chest include the mode you tested on next time.

**Comment by Fearevius** [comment]
I was talking about the control crystals in the room instructor razuvious.

**Comment by JunkyBulgaria** [comment]
i'm sorry, my bad.. fix applied for it as well

**Comment by darzeon** [comment]
You still can't teleport to the last two bosses.
