### ISSUE TITLE
DK Starting Zone - Pretty polished

### ISSUE THREAD

**Issue by cplanter** [FireFly-WoW/FireFly-IssueTracker#7]
**Description:**

Did the DK starter zone. Map was an issue and aggro coming out to see Lich King

**Current behaviour:**

When you take the Eye of Archerus to scope out the four areas the map shows you in the incorrect place. Not a deal breaker. But would be helpful!

When you take the quest to go down and see the Lich King there is aggro from the elites as you arrive and you die instantly (thank you for .cheat God!)

**Expected behaviour:**

Map would show the correct location of the player so the ?s that show up let you fly to the right place.

Aggro from the elites shouldn't be there so you can do the quest.

**Comment by masterfireyy** [comment]
We will test again and come back to you. 
I think its because of use of speed or fly mods.

**Comment by frytik** [comment]
Starting work on it.

**Comment by JunkyBulgaria** [comment]
1) markeres are placed on the correct locations, the minimap/map thing is not important as the eye is already flying to the location you have to scout at

2) fixed in older issue
