### ISSUE TITLE
Zul'aman

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#71]
**Description:**
Bonus loot chest can not be opened (can not be targeted)
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/onMX3
url...
url...

**Comment by JunkyBulgaria** [comment]
Any info about this chest?

**Comment by Fearevius** [comment]
http://wowwiki.wikia.com/wiki/Zul%27Aman_timed_event

**Comment by JunkyBulgaria** [comment]
fix applied
