### ISSUE TITLE
Naxxarams teleport orb

### ISSUE THREAD

**Issue by Crinia** [FireFly-WoW/FireFly-IssueTracker#72]
**Description:**
Well hello there the problem here is about the orb on naxxarams this orb teleport u to fight last 2 boss's ( sapheron/ killthuzad) but it not there
CHANGEME: Describe the issue here
The issue here is that the orb is not in it place at all which like that we cant teleport to the last 2 boss's and we cant fight them
**current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.
well atm there is no orb to use it to teleport at all so ppl cant fight last 2 boss's
**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.
well the players shall find orb on the place i show u photo on when player go to orb and click it they get teleported to fight " sapheron then killthuzad
**Steps to reproduce the problem:**
Well in my opinion admin's shall shut down the server to analyze the whole raid from first boss to last one to check all bugs after that they should put and orb to it place so players can teleport to last 2 boss's
1. Step 1
2. Step 2
3. Step 3

**Screenshots:**
http://imgur.com/a/sb6vJ
url...
url...
url...

**Comment by darzeon** [comment]
Yeah that should be fixed easily, I hoped I will get my immortal title for once in my life xd

**Comment by JunkyBulgaria** [comment]
fixed
