### ISSUE TITLE
Seek Out Neltharaku

### ISSUE THREAD

**Issue by svedizz** [FireFly-WoW/FireFly-IssueTracker#74]
**Description:**

Neltharaku doesn't appear to exist.

**Expected behaviour:**

He's supposed to fly around the Netherwing Fields so you can return the quest.

http://wowwiki.wikia.com/wiki/Neltharaku
http://wowwiki.wikia.com/wiki/Quest:Seek_Out_Neltharaku

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/ez5i3t

**Comment by svedizz** [comment]
So you didn't have to fix anything? I looked for quite a while, I'll log in later today and check.

**Comment by JunkyBulgaria** [comment]
yeah, i increased my view graphics to max and found him, also used .go creature on him and he's there flying arround

**Comment by svedizz** [comment]
Checked again, he's not there for me or my friend :(

**Comment by JunkyBulgaria** [comment]
he might be in a phase, and you should have the required quests, idk.. he's there tho
