### ISSUE TITLE
Dungeon: Ahn'kahet: The Old Kingdom : Boss: Jedoga Shadowseeker

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#76]
**Description:**

Jedoga Shadowseeker has broken mechanic which makes her unbeatable.

**Doesn't work on both NORMAL and HEROIC!**

**Current behaviour:**

When she go immune and float into the air no minion will become active.

CHANGEME: Explain to us (if/how) it currently works.

_Every so often she will go immune and float back into the air. Then a random minion will become active and walk toward the center of the room. If the minion reaches the circle of light below the boss, they will "sacrifice" themselves and their health will be added to the bosses. The boss will gain a buff (Gift of the Herald) that increases damage by 200%. Therefore, burst down the minion as quickly as possible before it reaches the center._ (source: http://wowwiki.wikia.com/wiki/Jedoga_Shadowseeker )

Video:  https://youtu.be/mv2za_0R2Ds?t=17m36s ( minion sacrifice part )

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/f0tcl7 it became active, needs testing.

**Comment by Deathtremor** [comment]
@JunkyBulgaria 

Re-tested!

minion becomes active works so this part is fixed.

I also encounter 2 other issues:

1. When she goes to air she kinda jumping there instead of properly floting up there. The same applies when she is going down...she is kinda swimming instead of floating down.

2. When she had about 10 % hp and went up she instantly died. I couldn't loot here afterwards. No damage boosts...etc were used. Don;t know what happened really.

**Comment by JunkyBulgaria** [comment]
couldn't reproduce, tested it twice on both normal and heroic (4 times total), seems fixed
