### ISSUE TITLE
Magtheridon's Lair

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#77]
**Description:**
You can not attack the boss
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/cf1Tg
url...
url...

**Comment by darzeon** [comment]
You can, just do not rush with chanelers. Do not slay when you enter, attack one and they will all charge towards you. (this part is prolly optional - let them summon minions first). Aftere you they charge towards you, kill them. And wait few moments, you will get some message that he is breaking out of his chains and shorty after he will become targetable.

**Comment by JunkyBulgaria** [comment]
just did it and it works as intended, you shouldn't use damage/speed and wait for the events to proceed
