### ISSUE TITLE
Serpentshrine Cavern

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#78]
**Description:**
I fell 4 times under the texture and died trying to get off the elevator. The speed of the character did not change.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://imgur.com/a/xFsOd
url...
url...

**Comment by JunkyBulgaria** [comment]
Duplicate issue
