### ISSUE TITLE
 Karazhan

### ISSUE THREAD

**Issue by Fearevius** [FireFly-WoW/FireFly-IssueTracker#79]
**Description:**
You can go through the door to the last boss without playing chess. The problem with the doors is relevant in all the dungeons in which I was.
CHANGEME: Describe the issue here

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**
http://imgur.com/a/SscT6
url...
url...

**Comment by JunkyBulgaria** [comment]
Thats how it works?

**Comment by Fearevius** [comment]
The door must be closed if you do not win chess.

**Comment by JunkyBulgaria** [comment]
Tested, when we script the chess event (probably in the next few weeks) it will be closed as intended.
