### ISSUE TITLE
Molten Core Last Boss Not Spawning Correctly

### ISSUE THREAD

**Issue by darzeon** [FireFly-WoW/FireFly-IssueTracker#81]
After killing Executus, he won't be at the Ragnaros's spawn place to summon him.

**Comment by JunkyBulgaria** [comment]
You missed a boss(es), works as intended.

**Comment by darzeon** [comment]
I don't think that is the case, executus wouldn't spawn either if I missed any of the serpants. I will check again and delete the post if I am wrong,
