### ISSUE TITLE
Tempest Keep - The Eye - Last Boss Kael not working properly.

### ISSUE THREAD

**Issue by darzeon** [FireFly-WoW/FireFly-IssueTracker#82]
Sometimes he is getting bugged between phases and won't proceed to the next phase, for example after killing all 4 minibosses next to him, or he won't go into the last phase at all. He will just stand there and be unattackable.

PS. English is not my brightest side.

**Comment by JunkyBulgaria** [comment]
couldn't reproduce, please kill them without damage modifiers / modify speed/fly.
