### ISSUE TITLE
wolves of humanity 

### ISSUE THREAD

**Issue by mumbozjumboz** [FireFly-WoW/FireFly-IssueTracker#83]
**Description:**

the wolves of northshire abbey (even though they are yellow colored) will attack you as soon as you (so much as) right click on another wolf.
still haven't tested to see if all mobs have this problem .

**Comment by JunkyBulgaria** [comment]
my mistake with tags, it was global core issue, should be fixed now

**Comment by Deathtremor** [comment]
**Re-tested! Still issues!**

Currently the mob you targated won't attack you however all wolfs near and very far from him will attack you anyway.

**Comment by svedizz** [comment]
Yeah, they are not supposed to attack in packs.

**Comment by mumbozjumboz** [comment]
I'm sorry .seems like I found a headache for you guys instead of a bug

**Comment by JunkyBulgaria** [comment]
I'd need a video of  patch <=3.2x of these wolves because i think that nearby should attack as well because they are "family linked"

**Comment by mumbozjumboz** [comment]
Stand near a wolfie .and right click on another wolfie that is far away from you .they still attack you

**Comment by JunkyBulgaria** [comment]
This is bugged, yes, i was talking about family relations.

**Comment by Deathtremor** [comment]
Didn't find any videon on that. That would be very hard. 

They might be family linked however it doesn't change the fact that every wolf you come across in the whole map will attack you no matter how far you are from the wolf you only targeted. If its family linked than only NEARby wolves should attack you not all mobs in the area.

Also. They attack you even tho you didn't even do any damage to them. You just "right click" on one wolf and have like 20ft distance.

**Comment by starrheld** [comment]
## Creature.cpp
> Check against current creature victim, don't check potential victim attacking list.

> Neutral creatures with aggressive **reactstate** are triggered to attack from **MoveInLineOfSight** because of this check.

> Prevents attack from a distance after right clicking an npc.

```diff
- bool Creature::_IsTargetAcceptable(const Unit* target) const
+ bool Creature::_IsTargetAcceptable(Unit const* target) const

- const Unit* myVictim = getAttackerForHelper();
- const Unit* targetVictim = target->getAttackerForHelper();
+ Unit const* targetVictim = target->getAttackerForHelper();

- if (myVictim == target || targetVictim == this || IsHostileTo(target))
+if (GetVictim() == target || IsHostileTo(target))
     return true;

+ // a player is targeting me, but I'm not hostile towards it, and not currently attacking it, the target is not acceptable
+ // (players may set their victim from a distance, and doesn't mean we should attack)
+ if (target->GetTypeId() == TYPEID_PLAYER && targetVictim == this)
+     return false;
```

**Comment by JunkyBulgaria** [comment]
fixed
