### ISSUE TITLE
bugged unit

### ISSUE THREAD

**Issue by mumbozjumboz** [FireFly-WoW/FireFly-IssueTracker#84]
there is a unit in fargodeep mines which is staying there all cool like it's his hood, and i can't attack it,haven't seen anything else so far.
![wowscrnshot_042017_165914](https://cloud.githubusercontent.com/assets/27812654/25230817/ad6a7a6a-25ea-11e7-81b4-e5bcf581543b.jpg)

**Comment by JunkyBulgaria** [comment]
were you running with speed in this mine?

**Comment by mumbozjumboz** [comment]
Nope .running normally

**Comment by JunkyBulgaria** [comment]
couldn't reproduce, might happen once every 100 times if speed was used

**Comment by JunkyBulgaria** [comment]
Issue merged into #93
