### ISSUE TITLE
Channel Names

### ISSUE THREAD

**Issue by Skreem1** [FireFly-WoW/FireFly-IssueTracker#86]
**Description:**

Channel starting letters appear in lowercase letters.

**Expected behaviour**

The first (starting) letters should appear in uppercase.

**Screenshots:**

.http://prnt.sc/eyoxy1
http://prnt.sc/eyoy3b - They do show up as they should under the Chat Channels panel.

**Comment by JunkyBulgaria** [comment]
will be fixed in today's update
