### ISSUE TITLE
Durotar Tiger - NPC Issue

### ISSUE THREAD

**Issue by trapchristian** [FireFly-WoW/FireFly-IssueTracker#88]
**Description:**

The Durotar Tiger's attack speed is too high, resulting in 10-20 hits every 0,5 sec. Luckily I was leveling with heirlooms but most classes wouldnt stand a chance against them as they are atm. Clearly bugged attackspeed

**Current behaviour:**
^

**Expected behaviour:**

**Steps to reproduce the problem:**

1. .tele to senjin 
2. make sure to equip gear to see real dmg on a low lvl toon
3. find a durotar tiger

**Screenshots:**
Pointless here...

**Comment by JunkyBulgaria** [comment]
http://prntscr.com/ez4o74 - 2 attacks per seccond, damage seems normal, where exactly did you find that tiger?

**Comment by JunkyBulgaria** [comment]
i tried over 40 tigers on echo isle, naked and damage seems fine to me as they can cc them as well
