### ISSUE TITLE
Zul'drak Gerk's bugged quest 

### ISSUE THREAD

**Issue by Elgranclan** [FireFly-WoW/FireFly-IssueTracker#89]
**Description:** When encountering the NPC Gerk in Zul'drak, he should give a lone quest called 'Light Won't Grant Me Vengeance' about killing a few enemies around, but he doesn't give anything here. It isn't part of any quest chain so it isn't crucial, still a bug tho.

**Current behaviour:** Gerk just stands in his place, and you can't interact with him

**Expected behaviour:** Gerk should give anyone the aforementioned quest. 

**Steps to reproduce the problem:** Well, just look at him, 'drowning' in his thoughts...

**Screenshots:**

https://pix.sfly.com/b-CSm7

**Comment by JunkyBulgaria** [comment]
Have you completed http://www.wowhead.com/quest=12903/thats-what-friends-are-for before testing?

**Comment by Elgranclan** [comment]
In retail, he should give you the quest even if you're not completing that one (altought normally you encounter him because of that), but yeah, anyways I was doing the quest and even came back after completing,but nothing worked

**Comment by thestranger064** [comment]
Confrimed, I got it after handed in the thats-what-friends-are-for but as he says it should work before. Why is it closed if its not optimized.
