### ISSUE TITLE
Deadmine - Patrols mechanic is missing.

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#9]
When you kill 3 first bosses a patrol is supposed show up and  start patroling.

Currently the patrols are already there even tho any of of the bosses wasn't killed yet.  Also they are not patroling, they just at one spot.

**Comment by JunkyBulgaria** [comment]
https://www.youtube.com/watch?v=nOPK5IRv4kg Is this the encounter?

**Comment by Deathtremor** [comment]
Yea thats what i mean. This is one of 3 patrols.

**Comment by JunkyBulgaria** [comment]
Merge with #10 

> When you pull a mob and the mobs is coming towards you while passing near his "friends" he is not aggroing any of them.

The mobs is supposed to agro any of his "friends" while passing near by them.

**Comment by JunkyBulgaria** [comment]
Added a fix from Mangos-WDB


- All Bosses Are Immune To Crowd Control -- Daze, Horror, Shackle, Banish, Polymorph, Knockout, Freeze, Stun, Snare, Sleep, Silence, Pacify, Root, Fear, Distract, Disarm, Confused, Charm
-  Defias Evoker linked to Defias Overseer
-  Fix an Defias Overseer Pathing (Removed bad waypoint)
-  Remove Random Movement of 2 Miners
-  Add Random NPC Movement to Defias Evoker
-  Defias Evoker linked to Defias Overseer
-  Fix Gilnid Movement
-  Defias Wizard linked to Defias Taskmaster
-  Defias Wizard linked to Defias Overseer
-  Linked Aggro Between Mr. Smite and 2 Defias Blackguards
-  Linked Aggro Between Defias Pirate and Defias Squallshaper Behind Mr. Smite
-  Linked Aggro Between VanCleef and 2 Defias Blackguard Adds
-  VanCleef Adds (Should Not Random Move)


You can test now.

**Comment by JunkyBulgaria** [comment]
Also fixed issue #10 , now they will call for help as intended.

**Comment by Deathtremor** [comment]
Re-tested.

* Still no working patrolls.
* The calling help radius is too gray. They pull to many mobs at once.
* They still dont pull mobs which they are passing around.

**Comment by JunkyBulgaria** [comment]
Patrols now work: 
- http://prntscr.com/ews0iv
- http://prntscr.com/ews0lj
- http://prntscr.com/ews0mo
- http://prntscr.com/ews0pc
- http://prntscr.com/ews0sv
"Call for Help" radius is blizzlike as from sniffs.
Passing mobs will be pulled if your level is equal to theirs or few more higher.

If there is something else bugged please comment/re-open this issue as currently all of it is fixed.
Thanks!
