### ISSUE TITLE
Naxxramas 25man Loot

### ISSUE THREAD

**Issue by RealPrigano** [FireFly-WoW/FireFly-IssueTracker#90]
**Description:**

CHANGEME: Legendary item Splinter of Atiesh drops in Naxxramas 25man normal 

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:** It shouldn't drop in wotlk Naxx at all

CHANGEME: Delete the item from the loot table.

**Steps to reproduce the problem:**

1. Enter Naxx
2. Kill Bosses
3. Loot Bosses. kek

**Screenshots:**

http://www.directupload.net/file/d/4698/8fbwehvj_jpg.htm

**Comment by JunkyBulgaria** [comment]
it's there only for the beta if someone wants to do the chain
