### ISSUE TITLE
Naxx Kel'Thuzad fight

### ISSUE THREAD

**Issue by RealPrigano** [FireFly-WoW/FireFly-IssueTracker#92]
**Description:**

CHANGEME: After the Kel'Thuzad fight the door wont open again.

**Current behaviour:**

CHANGEME: Explain to us (if/how) it currently works.

**Expected behaviour:**

CHANGEME: I'm not sure but it probably should open again after the fight ends.

**Steps to reproduce the problem:**

1. Step 1
2. Step 2
3. Step 3

**Screenshots:**

http://www.directupload.net/file/d/4698/brtiq2ri_jpg.htm

**Comment by JunkyBulgaria** [comment]
i tested it and works fine, if there are any issues feel free to reply
