### ISSUE TITLE
Random NPC's falling trough floor/textures into caves / underground paths.

### ISSUE THREAD

**Issue by JunkyBulgaria** [FireFly-WoW/FireFly-IssueTracker#93]
Title explains the issue for it self.
Merging issues #42 #84 into this one.

Fix applied, both zones needs testing.

Thanks to: @Deathtremor & @mumbozjumboz for reporting.

**Comment by Deathtremor** [comment]
**Re-tested! It work fine now. No pathfinding issues anymore!**

Can be closed!
