### ISSUE TITLE
[Lesser Bloodstone Ore] nodes are missing in Drywhisker Gorge cave in Arathi Highlands

### ISSUE THREAD

**Issue by Deathtremor** [FireFly-WoW/FireFly-IssueTracker#94]
**Description:**

Nodes of [Lesser Bloodstone Ore] are missing in Drywhisker Gorge cave in Arathi Highlands

**Expected behaviour:**

The cave is supposed to be full of [Lesser Bloodstone Ore] nodes.

![wowscrnshot_042217_152945](https://cloud.githubusercontent.com/assets/27430839/25301677/bb05e218-2770-11e7-9f2c-131bc57a277e.jpg)

**Comment by JunkyBulgaria** [comment]
i went in and found 6-7 bloodstone, 1 iron and 1 mithril.. could be bad luck?

**Comment by Deathtremor** [comment]
@JunkyBulgaria 

Yea probably bad luck. I found them there too.
