### ISSUE TITLE
Nelf starting zone

### ISSUE THREAD

**Issue by mrbrokker** [FireFly-WoW/FireFly-IssueTracker#95]
**Description:** to many spiders

to many spiders spawning. and they spawn in groups.: Describe the issue here

**Current behaviour:** and as the spiders use to spawn close to each other this makes it a nightmare :I

 to many spawns: Explain to us (if/how) it currently works.

**Expected behaviour:**

the spawn placements are okay. but some some reason there is 2-3 spiders spawning on each point: Explain to us how the issue is supposed to work.

**Steps to reproduce the problem:**

1. Step 1 go into the cave
2. Step 2 die
3. Step 3 run back and die

**Screenshots:**

url...
![wowscrnshot_042217_112629](https://cloud.githubusercontent.com/assets/24208176/25303227/b87c5a4e-274e-11e7-9cfd-506d39f37c2f.jpg)

url...
url...

**Comment by JunkyBulgaria** [comment]
data sniffed from retail, it is the same

**Comment by Deathtremor** [comment]
I tested to.

 The most of spiders are in groups of 2. I found only 2 groups of 3 spiders. Group of 2 little is ok, but group of 3 is not good, its clear death. On the screenshot you can see one of 2 groups of 3 spiders i mentioned.
