### ISSUE TITLE
The Eye of Eternity

### ISSUE THREAD

**Issue by RealPrigano** [FireFly-WoW/FireFly-IssueTracker#96]
**Description:**

CHANGEME: Probably the same issue as in Naxx at Kel'Thuzad. After you defeated the Boss you cant get out. In this case the portal wont work.
**Current behaviour:**

CHANGEME: 

**Expected behaviour:**

CHANGEME: You're supposed to click on the portal to get back to Kaltarra.
**Steps to reproduce the problem:**

1. Kill Malygos
2. Step 2
3. Step 3

**Screenshots:**

url...
url...
url...

**Comment by JunkyBulgaria** [comment]
it works if you jump off your mount

**Comment by JunkyBulgaria** [comment]
completely fixed
