### ISSUE TITLE
Master of Arms achievement

### ISSUE THREAD

**Issue by Skreem1** [FireFly-WoW/FireFly-IssueTracker#98]
**Description:**

Master of Arms achievement doesn't seem to be working. I have all skills at 400, whereas it only requires 4 in order to get it. 
Is it possible that it didn't work because I used .max skill? 

**Expected behaviour:**

4 skills at 400 and you get it.

**Screenshots:**

http://prnt.sc/ez6xwj
http://prnt.sc/ez6xs7

**Comment by JunkyBulgaria** [comment]
.maxskill doesn't count
